import {useState,type FormEvent} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Archive,ArrowLeft,FileSignature,FileText,Plus,RotateCcw,Trash2,Upload} from 'lucide-react'
import {Link,useParams} from 'react-router-dom'
import {useOrganization} from '../../app/OrganizationProvider'
import {useAuth} from '../../app/AuthProvider'
import {addCandidateEducation,addCandidateEmployment,addCandidateLanguage,addCandidateSkill,addCandidateTag,deleteCandidateDocument,deleteCandidateProfileItem,getCandidateDetail,listCandidateDocuments,listCandidateProfileVersions,listTeamMembers,removeCandidateSkill,removeCandidateTag,setCandidateArchived,updateCandidateProfile} from '../core/commercialRepository'
import {Button} from '../../shared/ui/Button'
import {Field,Input,Select,Textarea} from '../../shared/ui/Field'
import {Modal} from '../../shared/ui/Modal'
import {Badge,Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {candidateStatus,consentStatus,profileStatus} from '../../shared/lib/status'
import {ErrorState,LoadingState} from '../../shared/ui/States'
import {formatCvDate,formatDate,formatSalary} from '../../shared/lib/format'
import {CandidateCvParser} from './CandidateCvParser'
import {CandidateProfileGenerator} from './CandidateProfileGenerator'
import {ActivityFeed} from '../activities/ActivityFeed'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {Table} from '../../shared/ui/Table'
import {listCandidatePipelineAssignments} from '../core/repository'
import {phaseForStage,pipelinePhases} from '../workflow/workflow'
import {AddCandidateToJobModal} from './AddCandidateToJobModal'
import {TaskButton} from '../activities/TaskButton'

type AddMode='employment'|'education'|'language'|'skill'|'tag'|null
export function CandidateDetailPage(){
  const {candidateId=''}=useParams();const {organization}=useOrganization();const {user}=useAuth();const capabilities=useWorkspaceCapabilities();const cache=useQueryClient();const [addMode,setAddMode]=useState<AddMode>(null);const [cvOpen,setCvOpen]=useState(false);const [profileOpen,setProfileOpen]=useState(false);const [editing,setEditing]=useState(false);const [jobOpen,setJobOpen]=useState(false);const [renderedAt]=useState(Date.now)
  const detail=useQuery({queryKey:['candidate-detail',organization?.id,candidateId],enabled:Boolean(organization&&candidateId),queryFn:()=>getCandidateDetail(organization!.id,candidateId)})
  const documents=useQuery({queryKey:['candidate-documents',organization?.id,candidateId],enabled:Boolean(organization&&candidateId),queryFn:()=>listCandidateDocuments(organization!.id,candidateId)})
  const profileVersions=useQuery({queryKey:['candidate-profile-versions',organization?.id,candidateId],enabled:Boolean(organization&&candidateId&&organization.profile_enabled),queryFn:()=>listCandidateProfileVersions(organization!.id,candidateId)})
  const members=useQuery({queryKey:['members',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  const pipelines=useQuery({queryKey:['candidate-pipelines',organization?.id,candidateId],enabled:Boolean(organization&&candidateId),queryFn:()=>listCandidatePipelineAssignments(organization!.id,candidateId)})
  const refresh=()=>Promise.all([cache.invalidateQueries({queryKey:['candidate-detail',organization?.id,candidateId]}),cache.invalidateQueries({queryKey:['candidate-documents',organization?.id,candidateId]}),cache.invalidateQueries({queryKey:['candidate-profile-versions',organization?.id,candidateId]}),cache.invalidateQueries({queryKey:['candidates-page',organization?.id]})])
  const save=useMutation({mutationFn:async(form:HTMLFormElement)=>{const values=new FormData(form);await updateCandidateProfile(organization!.id,candidateId,{full_name:values.get('full_name'),current_company:values.get('current_company'),current_position:values.get('current_position'),location:values.get('location'),linkedin_url:values.get('linkedin_url'),portfolio_url:values.get('portfolio_url'),status:values.get('status'),owner_member_id:values.get('owner_member_id'),source:values.get('source'),availability:values.get('availability'),notice_period_days:values.get('notice_period_days')},{email:values.get('email'),phone:values.get('phone'),current_salary:values.get('current_salary'),expected_salary:values.get('expected_salary'),salary_currency:values.get('salary_currency'),work_authorization:values.get('work_authorization'),consent_status:values.get('consent_status'),consent_expires_at:values.get('consent_expires_at')})},onSuccess:async()=>{setEditing(false);await refresh()}})
  const archive=useMutation({mutationFn:(archived:boolean)=>setCandidateArchived(organization!.id,candidateId,archived),onSuccess:refresh})
  const removeItem=useMutation({mutationFn:({table,id}:{table:'candidate_employment'|'candidate_education'|'candidate_languages';id:string})=>deleteCandidateProfileItem(table,organization!.id,id),onSuccess:refresh})
  const removeSkill=useMutation({mutationFn:(skillId:string)=>removeCandidateSkill(organization!.id,candidateId,skillId),onSuccess:refresh})
  const removeTag=useMutation({mutationFn:(tagId:string)=>removeCandidateTag(organization!.id,candidateId,tagId),onSuccess:refresh})
  if(detail.isLoading||documents.isLoading||members.isLoading||profileVersions.isLoading||pipelines.isLoading)return <LoadingState/>;if(detail.error||documents.error||members.error||profileVersions.error||pipelines.error||!detail.data)return <ErrorState error={detail.error||documents.error||members.error||profileVersions.error||pipelines.error}/>
  const candidate=detail.data;const privateData=Array.isArray(candidate.candidate_private_details)?candidate.candidate_private_details[0]:candidate.candidate_private_details
  const preparedBy=members.data?.find((member)=>member.user_id===user?.id)?.profiles?.full_name||''
  return <Page title={candidate.full_name} eyebrow="Candidate" description={`${candidate.current_position||'Role not recorded'}${candidate.current_company?` at ${candidate.current_company}`:''}`} metadata={<div className="record-metadata"><StatusBadge map={candidateStatus} value={candidate.status}/>{candidate.location&&<span>{candidate.location}</span>}</div>} actions={<><Link className="button button-quiet" to={`/app/${organization?.slug}/candidates`}><ArrowLeft size={15}/>Candidates</Link>{capabilities.data?.canMovePipeline&&<Button onClick={()=>setJobOpen(true)} disabled={Boolean(candidate.deleted_at)||candidate.status==='do_not_contact'}>Add to job</Button>}<TaskButton linkType="candidate" linkId={candidateId}/>{capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setEditing((value)=>!value)}>{editing?'Cancel edit':'Edit candidate'}</Button>}{organization?.profile_enabled&&capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setProfileOpen(true)}><FileSignature size={15}/>Client profile</Button>}{capabilities.data?.canWriteCandidates&&<Button variant={candidate.deleted_at?'secondary':'caution'} disabled={archive.isPending} onClick={()=>archive.mutate(!candidate.deleted_at)}>{candidate.deleted_at?<><RotateCcw size={15}/>Restore</>:<><Archive size={15}/>Archive</>}</Button>}</>}>
    {candidate.deleted_at&&<p className="warning-box">This record is archived and excluded from normal candidate searches.</p>}
    {editing?<form key={candidate.updated_at} className="stack" onSubmit={(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();save.mutate(event.currentTarget)}}>
      <Panel title="Profile and ownership"><div className="form-grid"><Field label="Full name"><Input name="full_name" defaultValue={candidate.full_name} required/></Field><Field label="Owner"><Select name="owner_member_id" defaultValue={candidate.owner_member_id||''}><option value="">Unassigned</option>{members.data?.filter((member)=>member.status==='active').map((member)=><option key={member.id} value={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select></Field><Field label="Current company"><Input name="current_company" defaultValue={candidate.current_company||''}/></Field><Field label="Current position"><Input name="current_position" defaultValue={candidate.current_position||''}/></Field><Field label="Location"><Input name="location" defaultValue={candidate.location||''}/></Field><Field label="Source"><Input name="source" defaultValue={candidate.source||''}/></Field><Field label="LinkedIn"><Input type="url" name="linkedin_url" defaultValue={candidate.linkedin_url||''}/></Field><Field label="Portfolio"><Input type="url" name="portfolio_url" defaultValue={candidate.portfolio_url||''}/></Field><Field label="Availability"><Input name="availability" defaultValue={candidate.availability||''}/></Field><Field label="Notice period (days)"><Input type="number" min="0" name="notice_period_days" defaultValue={candidate.notice_period_days??''}/></Field><Field label="Status"><Select name="status" defaultValue={candidate.status}><option value="active">Active</option><option value="passive">Passive</option><option value="placed">Placed</option><option value="do_not_contact">Do not contact</option><option value="archived">Archived</option></Select></Field></div></Panel>
      <Panel title="Private details and consent"><div className="form-grid"><Field label="Email"><Input type="email" name="email" defaultValue={privateData?.email||''}/></Field><Field label="Phone"><Input name="phone" defaultValue={privateData?.phone||''}/></Field><Field label="Current salary"><Input type="number" min="0" name="current_salary" defaultValue={privateData?.current_salary??''}/></Field><Field label="Expected salary"><Input type="number" min="0" name="expected_salary" defaultValue={privateData?.expected_salary??''}/></Field><Field label="Currency"><Input name="salary_currency" maxLength={3} defaultValue={privateData?.salary_currency||organization?.base_currency}/></Field><Field label="Work authorization"><Input name="work_authorization" defaultValue={privateData?.work_authorization||''}/></Field><Field label="Consent status"><Select name="consent_status" defaultValue={privateData?.consent_status||'unknown'}><option value="unknown">Unknown</option><option value="requested">Requested</option><option value="granted">Granted</option><option value="withdrawn">Withdrawn</option><option value="expired">Expired</option></Select></Field><Field label="Consent expires"><Input type="date" name="consent_expires_at" defaultValue={privateData?.consent_expires_at?.slice(0,10)||''}/></Field></div><p className="muted">Salary and contact details remain behind the candidate-private permission boundary.</p></Panel>
      {save.error&&<p className="form-error" role="alert">{save.error.message}</p>}<div className="form-actions"><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save candidate'}</Button></div>
    </form>:<div className="candidate-overview-grid"><Panel title="Contact details"><dl className="record-summary"><div><dt>Email</dt><dd>{privateData?.email||'Not recorded'}</dd></div><div><dt>Phone</dt><dd>{privateData?.phone||'Not recorded'}</dd></div><div><dt>Notice period</dt><dd>{candidate.notice_period_days!=null?`${candidate.notice_period_days} days`:'Not recorded'}</dd></div><div><dt>Source</dt><dd>{candidate.source||'Not recorded'}</dd></div></dl></Panel><Panel title="Recruitment readiness" subtitle="The one place these facts are stated; every other panel links rather than repeats."><div className="readiness-list"><article><strong>Consent</strong><StatusBadge map={consentStatus} value={privateData?.consent_status||'unknown'}/></article><article><strong>Contactable</strong>{candidate.status==='do_not_contact'?<Badge tone="bad">Do not contact</Badge>:<Badge tone="good">Yes</Badge>}</article><article><strong>CV</strong><span>{documents.data?.length?'Available':'Upload required'}</span></article><article><strong>Availability</strong><span>{candidate.availability||'Not recorded'}</span></article><article><strong>Expected salary</strong><span>{formatSalary(privateData?.expected_salary,privateData?.salary_currency||organization?.base_currency)}</span></article><article><strong>In pipelines</strong><span>{pipelines.data?.length||0}</span></article></div>{capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setCvOpen(true)}><Upload size={14}/>Upload or replace CV</Button>}</Panel></div>}
    <Panel title="In pipelines" subtitle="Every job this candidate is being considered for, with both the recruitment phase and exact working stage.">{pipelines.data?.length?<Table headers={['Job','Client','Phase','Detailed stage','Owner','Added','Days in stage']}>{pipelines.data.map((assignment)=>{const stage=assignment.pipeline_stages;const phase=stage?pipelinePhases.find((item)=>item.key===phaseForStage(stage))?.label:'Unknown';const changed=assignment.stage_history[0]?.occurred_at||assignment.updated_at;const days=Math.max(0,Math.floor((renderedAt-new Date(changed).getTime())/86_400_000));return <tr key={assignment.id}><td><Link className="record-link" to={`/app/${organization?.slug}/jobs/${assignment.job_id}`}>{assignment.jobs?.title||'Job'}</Link></td><td>{assignment.jobs?.companies?.name||'—'}</td><td>{phase}</td><td>{stage?.name||'—'}</td><td>{assignment.jobs?.organization_members?.profiles?.full_name||assignment.jobs?.organization_members?.profiles?.email||'Unassigned'}</td><td>{formatDate(assignment.added_at)}</td><td>{days}</td></tr>})}</Table>:<p className="muted">Not currently in a job pipeline.</p>}</Panel>
    <ActivityFeed links={[{candidate_id:candidate.id}]} subtitle="Every call, email, and meeting with this candidate. Pipeline moves and client feedback are recorded automatically." readOnly={!capabilities.data?.canWriteCandidates}/>
    <div className="two-column"><Panel title="Employment" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setAddMode('employment')}><Plus size={14}/>Add</Button>}><div className="list">{candidate.candidate_employment?.length?candidate.candidate_employment.map((item)=><article className="list-row" key={item.id}><div><strong>{item.title}</strong><span>{item.company_name} · {formatCvDate(item.started_on,item.started_on_precision)} – {item.is_current?'Present':formatCvDate(item.ended_on,item.ended_on_precision)}</span></div>{capabilities.data?.canWriteCandidates&&<Button variant="quiet" aria-label="Remove employment" onClick={()=>removeItem.mutate({table:'candidate_employment',id:item.id})}><Trash2 size={14}/></Button>}</article>):<p className="muted">No employment history.</p>}</div></Panel>
      <Panel title="Education" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setAddMode('education')}><Plus size={14}/>Add</Button>}><div className="list">{candidate.candidate_education?.length?candidate.candidate_education.map((item)=><article className="list-row" key={item.id}><div><strong>{item.institution}</strong><span>{[item.degree,item.field_of_study].filter(Boolean).join(' · ')}</span><span>{formatCvDate(item.started_on,item.started_on_precision)} – {formatCvDate(item.ended_on,item.ended_on_precision)}</span></div>{capabilities.data?.canWriteCandidates&&<Button variant="quiet" aria-label="Remove education" onClick={()=>removeItem.mutate({table:'candidate_education',id:item.id})}><Trash2 size={14}/></Button>}</article>):<p className="muted">No education history.</p>}</div></Panel>
      <Panel title="Languages" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setAddMode('language')}><Plus size={14}/>Add</Button>}><div className="list">{candidate.candidate_languages?.length?candidate.candidate_languages.map((item)=><article className="list-row" key={item.id}><div><strong>{item.language}</strong><span>{item.proficiency||'Proficiency not recorded'}</span></div>{capabilities.data?.canWriteCandidates&&<Button variant="quiet" aria-label="Remove language" onClick={()=>removeItem.mutate({table:'candidate_languages',id:item.id})}><Trash2 size={14}/></Button>}</article>):<p className="muted">No languages recorded.</p>}</div></Panel>
      <Panel title="Skills" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setAddMode('skill')}><Plus size={14}/>Add</Button>}><div className="list">{candidate.candidate_skills?.length?candidate.candidate_skills.map((item)=><article className="list-row" key={item.skill_id}><div><strong>{item.skills?.name||'Skill'}</strong><span>{[item.proficiency,item.years_experience?`${item.years_experience} years`:null].filter(Boolean).join(' · ')||'Details not recorded'}</span></div>{capabilities.data?.canWriteCandidates&&<Button variant="quiet" aria-label="Remove skill" onClick={()=>removeSkill.mutate(item.skill_id)}><Trash2 size={14}/></Button>}</article>):<p className="muted">No skills recorded.</p>}</div></Panel>
      <Panel title="Tags" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setAddMode('tag')}><Plus size={14}/>Add</Button>}><div className="tag-list">{candidate.candidate_tags?.length?candidate.candidate_tags.map((item)=><span className="tag-chip" key={item.tag_id}>{item.tags?.name||'Tag'}{capabilities.data?.canWriteCandidates&&<button type="button" aria-label={`Remove ${item.tags?.name||'tag'}`} onClick={()=>removeTag.mutate(item.tag_id)}>×</button>}</span>):<p className="muted">No tags recorded.</p>}</div></Panel>
      {organization?.profile_enabled&&<Panel title="Client profile history"><div className="list">{profileVersions.data?.length?profileVersions.data.map((profile)=><article className="list-row" key={profile.id}><div><strong>{profile.job_title} · Version {profile.version}</strong><span>{profile.template_name} · {profile.anonymized?'Anonymized':'Named'} · {formatDate(profile.finalized_at||profile.created_at)}</span></div><div><StatusBadge map={profileStatus} value={profile.status}/>{profile.stale&&<Badge tone="warn">Source changed</Badge>}</div></article>):<p className="muted">No generated profiles yet.</p>}</div></Panel>}
      <Panel title="Documents" action={capabilities.data?.canWriteCandidates&&<Button variant="secondary" onClick={()=>setCvOpen(true)}><Upload size={14}/>Upload and parse CV</Button>}><div className="list">{documents.data?.length?documents.data.map((document)=><article className="list-row" key={document.id}><div><strong><FileText size={14}/> {document.original_filename||document.file_name}</strong><span>{document.document_type==='candidate_profile'?'Client profile · ':''}{Math.ceil(document.size_bytes/1024)} KB</span></div><div><a className="button button-secondary" href={document.signedUrl} target="_blank" rel="noreferrer">Open</a>{capabilities.data?.canWriteCandidates&&<Button variant="quiet" aria-label="Archive document" onClick={()=>void deleteCandidateDocument(organization!.id,document.id,document.storage_path).then(refresh)}><Trash2 size={14}/></Button>}</div></article>):<p className="muted">No documents uploaded.</p>}</div></Panel>
    </div>
    <Modal title={`Add ${addMode||'profile item'}`} open={Boolean(addMode)} onClose={()=>setAddMode(null)}><AddProfileItem mode={addMode} organizationId={organization!.id} candidateId={candidateId} onDone={async()=>{setAddMode(null);await refresh()}}/></Modal>
    <Modal title="Upload and parse CV" open={cvOpen} wide onClose={()=>setCvOpen(false)}><CandidateCvParser organizationId={organization!.id} userId={user!.id} targetCandidateId={candidateId} targetCandidateName={candidate.full_name} onCancel={()=>setCvOpen(false)} onAccepted={async()=>{setCvOpen(false);await refresh()}}/></Modal>
    <Modal title="Generate client profile" open={profileOpen} wide onClose={()=>setProfileOpen(false)}><CandidateProfileGenerator organizationId={organization!.id} userId={user!.id} candidate={candidate} organizationName={organization!.name} accent={organization?.primary_color} logoUrl={organization?.logo_url} defaultPreparedBy={preparedBy} onClose={()=>setProfileOpen(false)} onFinalized={refresh}/></Modal>
    <AddCandidateToJobModal open={jobOpen} onClose={()=>setJobOpen(false)} candidates={[{id:candidate.id,full_name:candidate.full_name,current_position:candidate.current_position,status:candidate.status,consent_status:privateData?.consent_status||'unknown'}]}/>
  </Page>
}

function AddProfileItem({mode,organizationId,candidateId,onDone}:{mode:AddMode;organizationId:string;candidateId:string;onDone:()=>Promise<void>}){const mutation=useMutation({mutationFn:async(form:HTMLFormElement)=>{const data=new FormData(form);if(mode==='employment')await addCandidateEmployment(organizationId,candidateId,{company_name:String(data.get('company_name')||''),title:String(data.get('title')||''),started_on:String(data.get('started_on')||''),ended_on:String(data.get('ended_on')||''),is_current:data.get('is_current')==='on',summary:String(data.get('summary')||'')});if(mode==='education')await addCandidateEducation(organizationId,candidateId,{institution:String(data.get('institution')||''),degree:String(data.get('degree')||''),field_of_study:String(data.get('field_of_study')||''),started_on:String(data.get('started_on')||''),ended_on:String(data.get('ended_on')||'')});if(mode==='language')await addCandidateLanguage(organizationId,candidateId,String(data.get('language')||''),String(data.get('proficiency')||''));if(mode==='skill')await addCandidateSkill(organizationId,candidateId,String(data.get('skill')||''),String(data.get('proficiency')||''),data.get('years_experience')?Number(data.get('years_experience')):undefined);if(mode==='tag')await addCandidateTag(organizationId,candidateId,String(data.get('tag')||''))},onSuccess:onDone});return <form className="stack" onSubmit={(event)=>{event.preventDefault();mutation.mutate(event.currentTarget)}}>{mode==='employment'&&<><Field label="Company"><Input name="company_name" required/></Field><Field label="Title"><Input name="title" required/></Field><div className="form-grid"><Field label="Started"><Input type="date" name="started_on"/></Field><Field label="Ended"><Input type="date" name="ended_on"/></Field></div><label><input type="checkbox" name="is_current"/> Current role</label><Field label="Summary"><Textarea name="summary"/></Field></>}{mode==='education'&&<><Field label="Institution"><Input name="institution" required/></Field><Field label="Degree"><Input name="degree"/></Field><Field label="Field of study"><Input name="field_of_study"/></Field><div className="form-grid"><Field label="Started"><Input type="date" name="started_on"/></Field><Field label="Ended"><Input type="date" name="ended_on"/></Field></div></>}{mode==='language'&&<><Field label="Language"><Input name="language" required/></Field><Field label="Proficiency"><Input name="proficiency"/></Field></>}{mode==='skill'&&<><Field label="Skill"><Input name="skill" required/></Field><Field label="Proficiency"><Input name="proficiency"/></Field><Field label="Years of experience"><Input type="number" min="0" step="0.5" name="years_experience"/></Field></>}{mode==='tag'&&<Field label="Tag"><Input name="tag" required/> </Field>}{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<div className="form-actions"><Button disabled={mutation.isPending}>Add</Button></div></form>}
