import {useState} from 'react'
import {useForm} from 'react-hook-form'
import {zodResolver} from '@hookform/resolvers/zod'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {ChevronLeft,ChevronRight,MapPin,Merge,Plus,Search,Users} from 'lucide-react'
import {Link,useNavigate,useSearchParams} from 'react-router-dom'
import type {z} from 'zod'
import {useOrganization} from '../../app/OrganizationProvider'
import {useAuth} from '../../app/AuthProvider'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {candidateSchema} from '../core/schemas'
import {createCandidate,listCandidatesPage,type CandidateListFilters} from '../core/repository'
import {addCandidateEducation,addCandidateEmployment,addCandidateLanguage,addCandidateSkill,listTeamMembers,mergeCandidates} from '../core/commercialRepository'
import {candidateStatus,consentStatus} from '../../shared/lib/status'
import {initials} from '../../shared/lib/format'
import {useOpenOnNewParam} from '../../shared/lib/useOpenOnNewParam'
import {Button} from '../../shared/ui/Button'
import {CollapsibleSection} from '../../shared/ui/CollapsibleSection'
import {Field,Input,Select,Textarea} from '../../shared/ui/Field'
import {Modal} from '../../shared/ui/Modal'
import {Badge,Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {EmptyState,ErrorState,TableSkeleton} from '../../shared/ui/States'
import {useToast} from '../../shared/ui/Toast'
import {SavedViewBar} from '../core/SavedViewBar'
import {csvFilename,downloadCsv,toCsv} from '../../shared/lib/csv'
import {Table} from '../../shared/ui/Table'
import {CandidateCvParser} from './CandidateCvParser'
import {EducationListEditor,EmploymentListEditor,LanguagesListEditor,SkillsListEditor,type EducationItem,type EmploymentItem,type LanguageItem,type SkillItem} from './CandidateProfileEditors'
import {AddCandidateToJobModal,type PlacementCandidate} from './AddCandidateToJobModal'

type FormInput=z.input<typeof candidateSchema>;type FormData=z.output<typeof candidateSchema>;type SelectionMode='none'|'bulk'|'merge'

export function CandidatesPage(){
  const {organization}=useOrganization();const {user}=useAuth();const capabilities=useWorkspaceCapabilities();const cache=useQueryClient();const toast=useToast();const navigate=useNavigate();const [params,setParams]=useSearchParams()
  const [open,setOpen]=useState(false);const [manualMode,setManualMode]=useState(false);const [selectionMode,setSelectionMode]=useState<SelectionMode>('none');const [mergeOpen,setMergeOpen]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [keptId,setKeptId]=useState('');const [mergeReason,setMergeReason]=useState('Duplicate candidate record');const [placementCandidates,setPlacementCandidates]=useState<PlacementCandidate[]>([]);const placementOpen=placementCandidates.length>0||params.get('addToJob')==='1';const pageSize=50
  useOpenOnNewParam(setOpen)
  const page=Math.max(0,Number(params.get('page')||0));const filters:CandidateListFilters={query:params.get('q')||'',status:params.get('status')||'',location:params.get('location')||'',source:params.get('source')||'',ownerMemberId:params.get('owner')||'',tag:params.get('tag')||'',skill:params.get('skill')||'',availability:params.get('availability')||'',consentStatus:params.get('consent')||'',sort:(params.get('sort') as CandidateListFilters['sort'])||'updated',direction:(params.get('dir') as CandidateListFilters['direction'])||'desc'}
  const setFilter=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);next.delete('page');setParams(next,{replace:true});setSelected([])}
  const viewParamKeys=['q','status','location','source','owner','tag','skill','availability','consent','sort','dir']
  /* Export refetches the whole filtered set rather than writing the page on screen -- "export this
   * view" meaning "export the 50 rows you happen to be looking at" is the kind of quiet wrongness
   * that gets discovered in a client meeting. The cap is explicit and reported rather than silently
   * truncating. */
  const EXPORT_LIMIT=5000
  const exportView=useMutation({
    mutationFn:()=>listCandidatesPage(organization!.id,filters,0,EXPORT_LIMIT),
    onSuccess:(result)=>{
      const rows=result.rows.map((row)=>({name:row.full_name,current_position:row.current_position||'',current_company:row.current_company||'',location:row.location||'',status:row.status,source:row.source||'',owner:row.owner_name||'',skills:row.skill_names.join('; '),tags:row.tag_names.join('; '),consent_status:row.consent_status||'',updated_at:row.updated_at}))
      downloadCsv(csvFilename('candidates'),toCsv(rows))
      toast.success(`Exported ${rows.length} ${rows.length===1?'candidate':'candidates'}.`,result.count>rows.length?`This view has ${result.count} candidates; the first ${rows.length} were exported.`:undefined)
    },
    onError:(error)=>toast.error(error,'Nothing was exported.'),
  })
  const query=useQuery({queryKey:['candidates-page',organization?.id,filters,page],enabled:Boolean(organization),queryFn:()=>listCandidatesPage(organization!.id,filters,page,pageSize)})
  const team=useQuery({queryKey:['team',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  const form=useForm<FormInput,unknown,FormData>({resolver:zodResolver(candidateSchema),defaultValues:{full_name:'',email:'',phone:'',current_company:'',current_position:'',location:'',source:'',salary_currency:organization?.base_currency||'USD'}})
  // Manual add used to create an empty-profile candidate that then needed N follow-up trips to add
  // employment/education/etc. These sections are optional and outside the RHF form (candidateSchema
  // doesn't model arrays) -- kept separate here and inserted after the candidate itself is created.
  const [employment,setEmployment]=useState<EmploymentItem[]>([]);const [education,setEducation]=useState<EducationItem[]>([]);const [skills,setSkills]=useState<SkillItem[]>([]);const [languages,setLanguages]=useState<LanguageItem[]>([])
  const resetProfileSections=()=>{setEmployment([]);setEducation([]);setSkills([]);setLanguages([])}
  const mutation=useMutation({mutationFn:async(data:FormData)=>{
    const id=await createCandidate(organization!.id,user!.id,data)
    await Promise.all([
      ...employment.filter((item)=>item.company_name.trim()&&item.title.trim()).map((item)=>addCandidateEmployment(organization!.id,id,item)),
      ...education.filter((item)=>item.institution.trim()).map((item)=>addCandidateEducation(organization!.id,id,item)),
      ...languages.filter((item)=>item.language.trim()).map((item)=>addCandidateLanguage(organization!.id,id,item.language,item.proficiency||'')),
      ...skills.filter((item)=>item.name.trim()).map((item)=>addCandidateSkill(organization!.id,id,item.name,item.proficiency||'',item.years_experience??undefined)),
    ])
    return id
  },onSuccess:async(id,data)=>{setOpen(false);form.reset();resetProfileSections();await cache.invalidateQueries({queryKey:['candidates-page',organization?.id]});navigate(`/app/${organization!.slug}/candidates/${id}`);toast.success(`${data.full_name} was added to the talent database.`)},onError:(error)=>toast.error(error,'The candidate was not saved.')})
  const mergeMutation=useMutation({mutationFn:()=>{const duplicateId=selected.find((id)=>id!==keptId);if(!duplicateId)throw new Error('Select a second candidate to merge');return mergeCandidates(organization!.id,keptId,duplicateId,mergeReason)},onSuccess:async(id)=>{setMergeOpen(false);setSelected([]);await cache.invalidateQueries({queryKey:['candidates-page',organization?.id]});navigate(`/app/${organization!.slug}/candidates/${id}`);toast.success('The duplicate was merged into the kept record.','Stage history and activity from both records were preserved.')},onError:(error)=>toast.error(error,'Nothing was merged.')})
  const selectedRows=(query.data?.rows||[]).filter((item)=>selected.includes(item.id));const openMerge=()=>{setKeptId(selected[0]||'');setMergeOpen(true)};const openPlacement=(rows=selectedRows)=>{setPlacementCandidates(rows.map((item)=>({id:item.id,full_name:item.full_name,current_position:item.current_position,status:item.status,consent_status:item.consent_status})))}
  const closePlacement=()=>{setPlacementCandidates([]);const next=new URLSearchParams(params);next.delete('addToJob');setParams(next,{replace:true})}
  const toggle=(id:string,checked:boolean)=>setSelected((current)=>checked?[...current,id]:current.filter((item)=>item!==id))
  const pages=Math.max(1,Math.ceil((query.data?.count||0)/pageSize));const showPagination=(query.data?.count||0)>pageSize
  return <Page title="Candidates" eyebrow="Talent database" description="Find the right people, check readiness, and place them into a job without exposing private data in the list." actions={<>{selectionMode==='bulk'&&selected.length>0&&<Button variant="secondary" leadingIcon={<Users size={15}/>} onClick={()=>openPlacement()}>Add {selected.length} to job</Button>}{selectionMode==='merge'&&selected.length===2&&<Button variant="secondary" leadingIcon={<Merge size={15}/>} onClick={openMerge}>Merge selected</Button>}{capabilities.data?.canMovePipeline&&<Button variant="secondary" onClick={()=>{setSelectionMode((mode)=>mode==='bulk'?'none':'bulk');setSelected([])}}>{selectionMode==='bulk'?'Done selecting':'Select candidates'}</Button>}{capabilities.data?.canWriteCandidates&&<><Button variant="quiet" onClick={()=>{setSelectionMode((mode)=>mode==='merge'?'none':'merge');setSelected([])}}>{selectionMode==='merge'?'Done':'Manage duplicates'}</Button><Button leadingIcon={<Plus size={15}/>} onClick={()=>{setManualMode(false);setOpen(true)}}>Add candidate</Button></>}</>}>
    <Panel><SavedViewBar resource="candidates" paramKeys={viewParamKeys} params={params} onApply={(next)=>setParams(next,{replace:true})} onExport={()=>exportView.mutate()} exporting={exportView.isPending}/><div className="toolbar"><div className="search-box"><Search size={15}/><Input aria-label="Search candidates" placeholder="Name, company, or position" value={filters.query} onChange={(event)=>setFilter('q',event.target.value)}/></div><Select aria-label="Candidate status" value={filters.status} onChange={(event)=>setFilter('status',event.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="passive">Passive</option><option value="placed">Placed</option><option value="do_not_contact">Do not contact</option><option value="archived">Archived</option></Select><span className="muted">{query.data?.count??0} candidates</span></div>
      <details className="filter-panel"><summary>Filters and sorting</summary><div className="filter-grid"><Field label="Location"><Input value={filters.location} onChange={(event)=>setFilter('location',event.target.value)}/></Field><Field label="Source"><Input value={filters.source} onChange={(event)=>setFilter('source',event.target.value)}/></Field><Field label="Owner"><Select value={filters.ownerMemberId} onChange={(event)=>setFilter('owner',event.target.value)}><option value="">Anyone</option>{team.data?.filter((member)=>member.status==='active').map((member)=><option value={member.id} key={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select></Field><Field label="Tag"><Input value={filters.tag} onChange={(event)=>setFilter('tag',event.target.value)}/></Field><Field label="Skill"><Input value={filters.skill} onChange={(event)=>setFilter('skill',event.target.value)}/></Field><Field label="Availability"><Input value={filters.availability} onChange={(event)=>setFilter('availability',event.target.value)}/></Field><Field label="Consent"><Select value={filters.consentStatus} onChange={(event)=>setFilter('consent',event.target.value)}><option value="">Any</option><option value="granted">Granted</option><option value="requested">Requested</option><option value="unknown">Unknown</option><option value="withdrawn">Withdrawn</option><option value="expired">Expired</option></Select></Field><Field label="Sort"><Select value={`${filters.sort}:${filters.direction}`} onChange={(event)=>{const [sort='updated',dir='desc']=event.target.value.split(':');const next=new URLSearchParams(params);next.set('sort',sort);next.set('dir',dir);next.delete('page');setParams(next,{replace:true})}}><option value="updated:desc">Recently updated</option><option value="created:desc">Newest added</option><option value="name:asc">Name A–Z</option><option value="location:asc">Location A–Z</option></Select></Field></div></details>
      {query.isLoading?<TableSkeleton rows={8} columns={7} label="Loading candidates…"/>:query.error?<ErrorState error={query.error}/>:query.data?.rows.length===0?<EmptyState title="No candidates found" description="Add a candidate or change the filters."/>:<Table className="candidates-table" headers={[...(selectionMode!=='none'?['Select']:[]),'Candidate','Current role','Location','Skills and tags','Owner','Readiness','Action']}>{query.data?.rows.map((candidate)=><tr key={candidate.id} className={candidate.status==='do_not_contact'||candidate.status==='archived'?'candidate-row-muted':''}>{selectionMode!=='none'&&<td><input aria-label={`Select ${candidate.full_name}`} type="checkbox" checked={selected.includes(candidate.id)} disabled={selectionMode==='merge'&&!selected.includes(candidate.id)&&selected.length===2} onChange={(event)=>toggle(candidate.id,event.target.checked)}/></td>}<td><div className="candidate-row-identity"><span className="avatar-sm" aria-hidden="true">{initials(candidate.full_name)}</span><div><Link className="record-link" to={`/app/${organization?.slug}/candidates/${candidate.id}`}><strong>{candidate.full_name}</strong></Link><span>{candidate.source||'Source not recorded'}</span></div></div></td><td>{candidate.current_position||'—'}<span>{candidate.current_company||''}</span></td><td>{candidate.location?<span className="inline-stat"><MapPin size={13}/>{candidate.location}</span>:'—'}</td><td><div className="chip-row">{candidate.skill_names.slice(0,2).map((skill)=><Badge key={skill} tone="neutral">{skill}</Badge>)}{candidate.skill_names.length>2&&<Badge tone="neutral">+{candidate.skill_names.length-2}</Badge>}{candidate.skill_names.length===0&&<span className="muted">No skills tagged</span>}</div><small>{candidate.tag_names.slice(0,3).join(', ')}</small></td><td>{candidate.owner_name||'Unassigned'}</td><td><StatusBadge map={candidateStatus} value={candidate.status}/>{candidate.consent_status&&<StatusBadge map={consentStatus} value={candidate.consent_status}/>}</td><td>{capabilities.data?.canMovePipeline&&<Button size="sm" variant="secondary" disabled={candidate.status==='do_not_contact'||candidate.status==='archived'} onClick={()=>openPlacement([candidate])}>Add to job</Button>}</td></tr>)}</Table>}
      {showPagination&&<div className="pagination"><Button variant="secondary" disabled={page===0||query.isFetching} leadingIcon={<ChevronLeft size={14}/>} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(page-1));setParams(next,{replace:true})}}>Previous</Button><span>Page {page+1} of {pages}</span><Button variant="secondary" disabled={page+1>=pages||query.isFetching} trailingIcon={<ChevronRight size={14}/>} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(page+1));setParams(next,{replace:true})}}>Next</Button></div>}
    </Panel>
    <Modal title={manualMode?'Add candidate manually':'Add candidate from CV'} open={open} wide={!manualMode} onClose={()=>setOpen(false)}>{manualMode?<form className="form-grid" onSubmit={form.handleSubmit((data)=>mutation.mutate(data))}><Field label="Full name" error={form.formState.errors.full_name?.message}><Input {...form.register('full_name')}/></Field><Field label="Email" error={form.formState.errors.email?.message}><Input type="email" {...form.register('email')}/></Field><Field label="Phone"><Input {...form.register('phone')}/></Field><details className="advanced-fields full"><summary>Additional profile details</summary><div className="form-grid"><Field label="Current company"><Input {...form.register('current_company')}/></Field><Field label="Current position"><Input {...form.register('current_position')}/></Field><Field label="Location"><Input {...form.register('location')}/></Field><Field label="Source"><Input {...form.register('source')}/></Field><Field label={`Expected salary (per ${organization?.salary_period==='monthly'?'month':'year'})`}><Input type="number" {...form.register('expected_salary')}/></Field></div></details>
      {/* Optional and collapsed by default -- most candidates still arrive via CV upload, which
        * already collects these richly. This just closes the gap for candidates entered by hand. */}
      <CollapsibleSection className="full" title="Employment" badge={employment.length>0?<Badge>{employment.length}</Badge>:undefined}><EmploymentListEditor value={employment} onChange={setEmployment} showHeading={false}/></CollapsibleSection>
      <CollapsibleSection className="full" title="Education" badge={education.length>0?<Badge>{education.length}</Badge>:undefined}><EducationListEditor value={education} onChange={setEducation} showHeading={false}/></CollapsibleSection>
      <CollapsibleSection className="full" title="Skills" badge={skills.length>0?<Badge>{skills.length}</Badge>:undefined}><SkillsListEditor value={skills} onChange={setSkills} showHeading={false}/></CollapsibleSection>
      <CollapsibleSection className="full" title="Languages" badge={languages.length>0?<Badge>{languages.length}</Badge>:undefined}><LanguagesListEditor value={languages} onChange={setLanguages} showHeading={false}/></CollapsibleSection>
      {mutation.error&&<p className="form-error full" role="alert">{mutation.error.message}</p>}<div className="form-actions full"><Button type="button" variant="quiet" onClick={()=>setManualMode(false)}>Back to CV upload</Button><Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Create candidate'}</Button></div></form>:<CandidateCvParser organizationId={organization!.id} userId={user!.id} onCancel={()=>setOpen(false)} onManual={()=>setManualMode(true)} onAccepted={async(id)=>{setOpen(false);await cache.invalidateQueries({queryKey:['candidates-page',organization?.id]});navigate(`/app/${organization!.slug}/candidates/${id}`)}}/>}</Modal>
    <Modal title="Merge duplicate candidates" open={mergeOpen} onClose={()=>setMergeOpen(false)}><div className="stack"><p className="warning-box">This moves history, documents, tasks, notes, pipeline assignments, and private details into one record. The other record is archived and the action is audit logged.</p><Field label="Record to keep"><Select value={keptId} onChange={(event)=>setKeptId(event.target.value)}>{selectedRows.map((item)=><option value={item.id} key={item.id}>{item.full_name} · {item.current_position||'No current role'}</option>)}</Select></Field><Field label="Reason"><Textarea value={mergeReason} onChange={(event)=>setMergeReason(event.target.value)}/></Field>{mergeMutation.error&&<p className="form-error" role="alert">{mergeMutation.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setMergeOpen(false)}>Cancel</Button><Button variant="danger" disabled={!keptId||mergeMutation.isPending} onClick={()=>mergeMutation.mutate()}>{mergeMutation.isPending?'Merging…':'Merge records'}</Button></div></div></Modal>
    <AddCandidateToJobModal open={placementOpen} onClose={closePlacement} candidates={placementCandidates}/>
  </Page>
}
