import {useEffect,useState,type ReactNode} from 'react'
import {useMutation,useQuery} from '@tanstack/react-query'
import {AlertTriangle,FileSearch,Plus,RotateCcw,Trash2,Upload} from 'lucide-react'
import {acceptCandidateCvParse,cancelCandidateCvParse,getCandidateCvParse,retryCandidateCvParse,startCandidateCvParse} from '../core/commercialRepository'
import {confidenceFor,emptyCandidateCvExtraction,type CandidateCvExtraction} from './cvParsing'
import {Button} from '../../shared/ui/Button'
import {Field,Input,Select,Textarea} from '../../shared/ui/Field'

type CandidateCvParserProps={organizationId:string;userId:string;targetCandidateId?:string;targetCandidateName?:string;onAccepted:(candidateId:string)=>void;onManual?:()=>void;onCancel:()=>void}

export function CandidateCvParser({organizationId,userId,targetCandidateId,targetCandidateName,onAccepted,onManual,onCancel}:CandidateCvParserProps){
  const [parseId,setParseId]=useState('');const [draft,setDraft]=useState<CandidateCvExtraction|null>(null);const [loadedParseId,setLoadedParseId]=useState('');const [localError,setLocalError]=useState('');const [manualFallback,setManualFallback]=useState(false)
  const start=useMutation({mutationFn:(file:File)=>startCandidateCvParse(organizationId,userId,file,targetCandidateId),onSuccess:(id)=>{setParseId(id);setDraft(null);setLoadedParseId('');setLocalError('')},onError:(error)=>setLocalError(error.message)})
  const parse=useQuery({queryKey:['candidate-cv-parse',organizationId,parseId],enabled:Boolean(parseId),queryFn:()=>getCandidateCvParse(organizationId,parseId),refetchInterval:(query)=>['uploaded','processing'].includes(query.state.data?.status||'')?2000:false})
  const retry=useMutation({mutationFn:()=>retryCandidateCvParse(organizationId,parseId),onSuccess:()=>void parse.refetch()})
  const accept=useMutation({mutationFn:(candidateId?:string)=>acceptCandidateCvParse(organizationId,parseId,draft!,candidateId||targetCandidateId),onSuccess:onAccepted})
  const cancel=useMutation({mutationFn:async()=>{if(parseId)await cancelCandidateCvParse(organizationId,parseId)},onSettled:onCancel})
  useEffect(()=>{if(parse.data?.status==='ready'&&parse.data.extraction&&loadedParseId!==parseId){setDraft({...parse.data.extraction,full_name:parse.data.extraction.full_name||targetCandidateName||''});setLoadedParseId(parseId);setManualFallback(false)}},[loadedParseId,parse.data,parseId,targetCandidateName])
  const beginManualFallback=()=>{setDraft({...emptyCandidateCvExtraction,full_name:targetCandidateName||'',source:'CV upload'});setManualFallback(true);setLoadedParseId(parseId)}
  if(!parseId)return <div className="cv-upload-flow"><label className="cv-dropzone"><Upload size={26}/><strong>{start.isPending?'Uploading CV…':'Upload CV to autofill'}</strong><span>PDF up to 25 MB or DOCX up to 10 MB. Scanned CVs are supported.</span><input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" disabled={start.isPending} onChange={(event)=>{const file=event.target.files?.[0];if(file)start.mutate(file)}}/></label>{(localError||start.error)&&<p className="form-error" role="alert">{localError||start.error?.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={onCancel}>Cancel</Button>{onManual&&<Button variant="secondary" onClick={onManual}>Enter manually</Button>}</div></div>
  const status=parse.data?.status
  if(parse.isLoading||status==='uploaded'||status==='processing')return <div className="cv-processing" aria-live="polite"><FileSearch size={30}/><strong>{status==='processing'?'Reading and structuring the CV…':'Preparing the CV…'}</strong><span>This usually takes under a minute. Keep this window open while the CV is processed.</span><Button variant="quiet" disabled={cancel.isPending} onClick={()=>cancel.mutate()}>Cancel parsing</Button></div>
  if(parse.error)return <div className="stack"><p className="form-error" role="alert">{parse.error.message}</p><div className="form-actions"><Button variant="quiet" onClick={()=>cancel.mutate()}>Cancel</Button><Button variant="secondary" onClick={()=>void parse.refetch()}><RotateCcw size={14}/>Check again</Button></div></div>
  if(status==='failed'&&!manualFallback)return <div className="stack"><p className="form-error" role="alert">{parse.data?.errorMessage||'The CV could not be parsed.'}</p>{parse.data?.errorCode&&<p className="muted"><code>{parse.data.errorCode}</code></p>}<p className="muted">Retry the automatic parser or enter the candidate manually and keep this CV attached.</p><div className="form-actions"><Button variant="quiet" onClick={()=>cancel.mutate()}>Cancel</Button><Button variant="secondary" disabled={retry.isPending} onClick={()=>retry.mutate()}><RotateCcw size={14}/>Retry</Button><Button onClick={beginManualFallback}>Attach without parsing</Button></div></div>
  if(!draft)return <p className="form-error" role="alert">The parsed CV preview is unavailable.</p>
  const matched=parse.data?.matchedCandidate
  const update=<K extends keyof CandidateCvExtraction>(key:K,value:CandidateCvExtraction[K])=>setDraft((current)=>current?{...current,[key]:value}:current)
  const updatePrivate=(key:keyof CandidateCvExtraction['private'],value:string|number|null)=>setDraft((current)=>current?{...current,private:{...current.private,[key]:value}}:current)
  const low=(path:string)=>confidenceFor(draft,path)==='low'
  return <div className="cv-review stack">
    <div className="cv-review-heading"><div><strong>{manualFallback?'Manual candidate details':'Review parsed CV'}</strong><span>Check highlighted values before saving. Nothing is created until you confirm.</span></div>{draft.uncertainties.length>0&&<span className="cv-confidence"><AlertTriangle size={13}/>{draft.uncertainties.length} item{draft.uncertainties.length===1?'':'s'} to check</span>}</div>
    {matched&&!targetCandidateId&&<div className="warning-box"><strong>Candidate already exists</strong><p>{matched.full_name}{matched.current_position?` · ${matched.current_position}`:''}{matched.current_company?` at ${matched.current_company}`:''}</p><p>This CV can fill blanks on the existing profile, but a duplicate cannot be created.</p></div>}
    {targetCandidateId&&<p className="warning-box">Only blank profile fields and new history items will be added. Existing consultant-entered values always win.</p>}
    <section><h3>Basic details</h3><div className="form-grid"><ReviewField label="Full name" low={low('full_name')}><Input value={draft.full_name} onChange={(event)=>update('full_name',event.target.value)}/></ReviewField><ReviewField label="Current company" low={low('current_company')}><Input value={draft.current_company||''} onChange={(event)=>update('current_company',event.target.value||null)}/></ReviewField><ReviewField label="Current position" low={low('current_position')}><Input value={draft.current_position||''} onChange={(event)=>update('current_position',event.target.value||null)}/></ReviewField><ReviewField label="Location" low={low('location')}><Input value={draft.location||''} onChange={(event)=>update('location',event.target.value||null)}/></ReviewField><Field label="LinkedIn"><Input type="url" value={draft.linkedin_url||''} onChange={(event)=>update('linkedin_url',event.target.value||null)}/></Field><Field label="Portfolio"><Input type="url" value={draft.portfolio_url||''} onChange={(event)=>update('portfolio_url',event.target.value||null)}/></Field><Field label="Source"><Input value={draft.source||''} onChange={(event)=>update('source',event.target.value||null)}/></Field><Field label="Availability"><Input value={draft.availability||''} onChange={(event)=>update('availability',event.target.value||null)}/></Field><Field label="Notice period (days)"><Input type="number" min="0" value={draft.notice_period_days??''} onChange={(event)=>update('notice_period_days',event.target.value?Number(event.target.value):null)}/></Field></div></section>
    <section><h3>Private details</h3><div className="form-grid"><ReviewField label="Email" low={low('private.email')}><Input type="email" value={draft.private.email||''} onChange={(event)=>updatePrivate('email',event.target.value||null)}/></ReviewField><ReviewField label="Phone" low={low('private.phone')}><Input value={draft.private.phone||''} onChange={(event)=>updatePrivate('phone',event.target.value||null)}/></ReviewField><Field label="Current salary"><Input type="number" min="0" value={draft.private.current_salary??''} onChange={(event)=>updatePrivate('current_salary',event.target.value?Number(event.target.value):null)}/></Field><Field label="Expected salary"><Input type="number" min="0" value={draft.private.expected_salary??''} onChange={(event)=>updatePrivate('expected_salary',event.target.value?Number(event.target.value):null)}/></Field><Field label="Currency"><Input maxLength={3} value={draft.private.salary_currency||''} onChange={(event)=>updatePrivate('salary_currency',event.target.value.toUpperCase()||null)}/></Field><Field label="Work authorization"><Input value={draft.private.work_authorization||''} onChange={(event)=>updatePrivate('work_authorization',event.target.value||null)}/></Field></div></section>
    <ReviewEmployment draft={draft} onChange={(employment)=>update('employment',employment)}/>
    <ReviewEducation draft={draft} onChange={(education)=>update('education',education)}/>
    <ReviewSkills draft={draft} onChange={(skills)=>update('skills',skills)}/>
    <ReviewLanguages draft={draft} onChange={(languages)=>update('languages',languages)}/>
    {draft.uncertainties.length>0&&<section><h3>Parser notes</h3><ul className="cv-uncertainties">{draft.uncertainties.map((item)=><li key={item}>{item}</li>)}</ul></section>}
    {(accept.error||localError)&&<p className="form-error" role="alert">{accept.error?.message||localError}</p>}
    <div className="form-actions"><Button variant="quiet" disabled={cancel.isPending||accept.isPending} onClick={()=>cancel.mutate()}>Cancel</Button><Button disabled={accept.isPending||draft.full_name.trim().length<2} onClick={()=>accept.mutate(matched&&!targetCandidateId?matched.id:undefined)}>{accept.isPending?'Saving…':matched&&!targetCandidateId?'Update existing candidate':targetCandidateId?'Attach CV and fill blanks':'Create candidate'}</Button></div>
  </div>
}

function ReviewField({label,low,children}:{label:string;low:boolean;children:ReactNode}){return <Field label={label}>{children}{low&&<small className="cv-low-confidence"><AlertTriangle size={11}/>Low confidence — check this value</small>}</Field>}

function ReviewEmployment({draft,onChange}:{draft:CandidateCvExtraction;onChange:(items:CandidateCvExtraction['employment'])=>void}){const change=(index:number,key:string,value:unknown)=>onChange(draft.employment.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));return <section><div className="cv-section-title"><h3>Employment</h3><Button variant="secondary" onClick={()=>onChange([...draft.employment,{company_name:'',title:'',location:null,started_on:null,ended_on:null,is_current:false,summary:null,started_on_precision:null,ended_on_precision:null,sort_order:draft.employment.length}])}><Plus size={13}/>Add</Button></div>{draft.employment.map((item,index)=><div className="cv-repeat-card" key={`employment-${index}`}><div className="form-grid"><Field label="Company"><Input value={item.company_name} onChange={(event)=>change(index,'company_name',event.target.value)}/></Field><Field label="Title"><Input value={item.title} onChange={(event)=>change(index,'title',event.target.value)}/></Field><Field label="Started"><Input type="date" value={item.started_on||''} onChange={(event)=>change(index,'started_on',event.target.value||null)}/></Field><Field label="Start precision"><Select value={item.started_on_precision||''} onChange={(event)=>change(index,'started_on_precision',event.target.value||null)}><option value="">Unknown</option><option value="day">Day</option><option value="month">Month</option><option value="year">Year</option></Select></Field><Field label="Ended"><Input type="date" value={item.ended_on||''} onChange={(event)=>change(index,'ended_on',event.target.value||null)}/></Field><Field label="End precision"><Select value={item.ended_on_precision||''} onChange={(event)=>change(index,'ended_on_precision',event.target.value||null)}><option value="">Unknown</option><option value="day">Day</option><option value="month">Month</option><option value="year">Year</option></Select></Field><Field label="Summary"><Textarea value={item.summary||''} onChange={(event)=>change(index,'summary',event.target.value||null)}/></Field><label className="cv-checkbox"><input type="checkbox" checked={item.is_current} onChange={(event)=>change(index,'is_current',event.target.checked)}/>Current role</label></div><Button variant="quiet" aria-label="Remove employment" onClick={()=>onChange(draft.employment.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/></Button></div>)}</section>}

function ReviewEducation({draft,onChange}:{draft:CandidateCvExtraction;onChange:(items:CandidateCvExtraction['education'])=>void}){const change=(index:number,key:string,value:unknown)=>onChange(draft.education.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));return <section><div className="cv-section-title"><h3>Education</h3><Button variant="secondary" onClick={()=>onChange([...draft.education,{institution:'',degree:null,field_of_study:null,started_on:null,ended_on:null,started_on_precision:null,ended_on_precision:null,sort_order:draft.education.length}])}><Plus size={13}/>Add</Button></div>{draft.education.map((item,index)=><div className="cv-repeat-card" key={`education-${index}`}><div className="form-grid"><Field label="Institution"><Input value={item.institution} onChange={(event)=>change(index,'institution',event.target.value)}/></Field><Field label="Degree"><Input value={item.degree||''} onChange={(event)=>change(index,'degree',event.target.value||null)}/></Field><Field label="Field of study"><Input value={item.field_of_study||''} onChange={(event)=>change(index,'field_of_study',event.target.value||null)}/></Field><Field label="Started"><Input type="date" value={item.started_on||''} onChange={(event)=>change(index,'started_on',event.target.value||null)}/></Field><Field label="Start precision"><Select value={item.started_on_precision||''} onChange={(event)=>change(index,'started_on_precision',event.target.value||null)}><option value="">Unknown</option><option value="day">Day</option><option value="month">Month</option><option value="year">Year</option></Select></Field><Field label="Ended"><Input type="date" value={item.ended_on||''} onChange={(event)=>change(index,'ended_on',event.target.value||null)}/></Field><Field label="End precision"><Select value={item.ended_on_precision||''} onChange={(event)=>change(index,'ended_on_precision',event.target.value||null)}><option value="">Unknown</option><option value="day">Day</option><option value="month">Month</option><option value="year">Year</option></Select></Field></div><Button variant="quiet" aria-label="Remove education" onClick={()=>onChange(draft.education.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/></Button></div>)}</section>}

function ReviewSkills({draft,onChange}:{draft:CandidateCvExtraction;onChange:(items:CandidateCvExtraction['skills'])=>void}){const change=(index:number,key:string,value:unknown)=>onChange(draft.skills.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));return <section><div className="cv-section-title"><h3>Skills</h3><Button variant="secondary" onClick={()=>onChange([...draft.skills,{name:'',proficiency:null,years_experience:null}])}><Plus size={13}/>Add</Button></div>{draft.skills.map((item,index)=><div className="cv-inline-row" key={`skill-${index}`}><Input aria-label="Skill" value={item.name} onChange={(event)=>change(index,'name',event.target.value)}/><Input aria-label="Skill proficiency" value={item.proficiency||''} onChange={(event)=>change(index,'proficiency',event.target.value||null)}/><Input aria-label="Years of experience" type="number" min="0" step="0.5" value={item.years_experience??''} onChange={(event)=>change(index,'years_experience',event.target.value?Number(event.target.value):null)}/><Button variant="quiet" aria-label="Remove skill" onClick={()=>onChange(draft.skills.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/></Button></div>)}</section>}

function ReviewLanguages({draft,onChange}:{draft:CandidateCvExtraction;onChange:(items:CandidateCvExtraction['languages'])=>void}){const change=(index:number,key:string,value:unknown)=>onChange(draft.languages.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));return <section><div className="cv-section-title"><h3>Languages</h3><Button variant="secondary" onClick={()=>onChange([...draft.languages,{language:'',proficiency:null}])}><Plus size={13}/>Add</Button></div>{draft.languages.map((item,index)=><div className="cv-inline-row cv-inline-row-short" key={`language-${index}`}><Input aria-label="Language" value={item.language} onChange={(event)=>change(index,'language',event.target.value)}/><Input aria-label="Language proficiency" value={item.proficiency||''} onChange={(event)=>change(index,'proficiency',event.target.value||null)}/><Button variant="quiet" aria-label="Remove language" onClick={()=>onChange(draft.languages.filter((_,itemIndex)=>itemIndex!==index))}><Trash2 size={14}/></Button></div>)}</section>}
