import { useQuery } from '@tanstack/react-query'
import { BriefcaseBusiness, CalendarClock, CircleDollarSign, ListTodo, Send, Users } from 'lucide-react'
import { useOrganization } from '../../app/OrganizationProvider'
import { dashboardSummary } from '../core/repository'
import { ErrorState, LoadingState } from '../../shared/ui/States'
import { Page, Panel } from '../../shared/ui/Page'
import { formatDate, formatMoney } from '../../shared/lib/format'

export function DashboardPage(){const {organization}=useOrganization();const query=useQuery({queryKey:['dashboard',organization?.id],enabled:Boolean(organization),queryFn:()=>dashboardSummary(organization!.id)});if(query.isLoading)return <LoadingState label="Loading agency priorities…"/>;if(query.error||!query.data)return <ErrorState error={query.error} retry={()=>void query.refetch()}/>;const data=query.data;const feeByCurrency=data.placements.reduce<Record<string,number>>((sum,row)=>{const item=row as {placement_fee:number;currency:string};sum[item.currency]=(sum[item.currency]??0)+Number(item.placement_fee);return sum},{});return <Page title="Dashboard" eyebrow={organization?.name} description="What needs attention across delivery and client work today."><div className="kpi-grid"><Kpi icon={<BriefcaseBusiness/>} label="Active vacancies" value={data.activeJobs}/><Kpi icon={<Users/>} label="Candidates" value={data.candidates}/><Kpi icon={<ListTodo/>} label="Overdue actions" value={data.overdueTasks.length} alert={data.overdueTasks.length>0}/><Kpi icon={<CalendarClock/>} label="Interviews · 7d" value={data.interviews}/><Kpi icon={<Send/>} label="Offers in progress" value={data.offers}/><Kpi icon={<CircleDollarSign/>} label="Placement fees · YTD" value={Object.entries(feeByCurrency).map(([currency,value])=>formatMoney(value,currency)).join(' · ')||'—'}/></div><div className="dashboard-grid"><Panel title="Overdue actions"><div className="list">{data.overdueTasks.length===0?<p className="muted">Nothing overdue.</p>:data.overdueTasks.map((task)=><article className="list-row" key={task.id}><div><strong>{task.title}</strong><span>{task.priority} priority</span></div><time>{formatDate(task.due_at)}</time></article>)}</div></Panel><Panel title="Recent activity"><div className="list">{data.activities.length===0?<p className="muted">No recent activity.</p>:data.activities.map((activity)=><article className="list-row" key={activity.id}><div><strong>{activity.subject||activity.activity_type}</strong><span>{activity.summary}</span></div><time>{formatDate(activity.occurred_at)}</time></article>)}</div></Panel></div></Page>}
function Kpi({icon,label,value,alert=false}:{icon:React.ReactNode;label:string;value:React.ReactNode;alert?:boolean}){return <article className={`kpi ${alert?'kpi-alert':''}`}><span>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></article>}

