import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { CalendarPlus,Handshake,Plus } from 'lucide-react'
import { useOrganization } from '../../app/OrganizationProvider'
import { useAuth } from '../../app/AuthProvider'
import { convertOfferToPlacement,createInterview,createOffer,getPipeline,listInterviews,listJobs,listOffers,updateOfferStatus } from '../core/repository'
import type { JobCandidate,Offer } from '../../shared/types/domain'
import { Button } from '../../shared/ui/Button'
import { Field,Input,Select } from '../../shared/ui/Field'
import { Modal } from '../../shared/ui/Modal'
import { Badge,Page,Panel } from '../../shared/ui/Page'
import { EmptyState,ErrorState,LoadingState } from '../../shared/ui/States'
import { formatDate,formatMoney } from '../../shared/lib/format'

export function DeliveryPage(){
  const {organization}=useOrganization();const {user}=useAuth();const cache=useQueryClient();const [interviewOpen,setInterviewOpen]=useState(false);const [offerOpen,setOfferOpen]=useState(false);const [convertOffer,setConvertOffer]=useState<Offer|null>(null);const [jobId,setJobId]=useState('');const [jobCandidateId,setJobCandidateId]=useState('');const [startsAt,setStartsAt]=useState('');const [endsAt,setEndsAt]=useState('');const [location,setLocation]=useState('');const [salary,setSalary]=useState('');const [startDate,setStartDate]=useState('');const [fee,setFee]=useState('');const [currency,setCurrency]=useState(organization?.base_currency||'USD')
  const jobs=useQuery({queryKey:['jobs',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobs(organization!.id)});const job=jobs.data?.find((item)=>item.id===jobId);const pipeline=useQuery({queryKey:['pipeline',jobId],enabled:Boolean(job),queryFn:()=>getPipeline(job!)});const interviews=useQuery({queryKey:['interviews',organization?.id],enabled:Boolean(organization),queryFn:()=>listInterviews(organization!.id)});const offers=useQuery({queryKey:['offers',organization?.id],enabled:Boolean(organization),queryFn:()=>listOffers(organization!.id)})
  const refresh=async()=>{await Promise.all([cache.invalidateQueries({queryKey:['interviews',organization?.id]}),cache.invalidateQueries({queryKey:['offers',organization?.id]}),cache.invalidateQueries({queryKey:['placements',organization?.id]}),cache.invalidateQueries({queryKey:['jobs',organization?.id]})])}
  const interviewMutation=useMutation({mutationFn:()=>createInterview(organization!.id,user!.id,{job_candidate_id:jobCandidateId,starts_at:new Date(startsAt).toISOString(),ends_at:new Date(endsAt).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,interview_type:'client_interview',location}),onSuccess:async()=>{setInterviewOpen(false);await refresh()}})
  const offerMutation=useMutation({mutationFn:()=>createOffer(organization!.id,user!.id,{job_candidate_id:jobCandidateId,salary:Number(salary),currency,start_date:startDate||undefined}),onSuccess:async()=>{setOfferOpen(false);await refresh()}})
  const statusMutation=useMutation({mutationFn:({id,status}:{id:string;status:'accepted'|'declined'|'withdrawn'})=>updateOfferStatus(id,status),onSuccess:refresh})
  const convertMutation=useMutation({mutationFn:()=>convertOfferToPlacement(convertOffer!.id,Number(fee),90),onSuccess:async()=>{setConvertOffer(null);setFee('');await refresh()}})
  const candidates:JobCandidate[]=pipeline.data?.items||[];const resetJob=(value:string)=>{setJobId(value);setJobCandidateId('')}
  if(interviews.isLoading||offers.isLoading)return <LoadingState/>;if(interviews.error||offers.error)return <ErrorState error={interviews.error||offers.error}/>
  return <Page title="Interviews & offers" eyebrow="Delivery milestones" description="Schedule client interviews, record commercial offers, and convert accepted offers into placements." actions={<><Button variant="secondary" onClick={()=>setInterviewOpen(true)}><CalendarPlus size={15}/>Schedule interview</Button><Button onClick={()=>setOfferOpen(true)}><Plus size={15}/>Record offer</Button></>}>
    <div className="two-column"><Panel title="Upcoming interviews"><div className="list">{interviews.data?.length===0?<EmptyState title="No interviews" description="Schedule the next client conversation."/>:interviews.data?.map((interview)=><article className="list-row" key={interview.id}><div><strong>{interview.job_candidates?.candidates?.full_name||'Candidate'}</strong><span>{interview.job_candidates?.jobs?.title} · {interview.location||interview.meeting_url||'Location pending'}</span></div><div><time>{new Date(interview.starts_at).toLocaleString()}</time><Badge tone="info">{interview.status}</Badge></div></article>)}</div></Panel><Panel title="Offers"><div className="list">{offers.data?.length===0?<EmptyState title="No offers" description="Record an offer when a candidate reaches the commercial stage."/>:offers.data?.map((offer)=><article className="list-row" key={offer.id}><div><strong>{offer.job_candidates?.candidates?.full_name||'Candidate'}</strong><span>{offer.job_candidates?.jobs?.title} · {formatMoney(offer.salary,offer.currency)} · start {formatDate(offer.start_date)}</span></div><div><Badge tone={offer.status==='accepted'?'good':offer.status==='declined'?'bad':'warn'}>{offer.status}</Badge>{offer.status==='presented'&&<Button variant="secondary" onClick={()=>statusMutation.mutate({id:offer.id,status:'accepted'})}>Accept</Button>}{offer.status==='accepted'&&<Button onClick={()=>setConvertOffer(offer)}><Handshake size={14}/>Place</Button>}</div></article>)}</div></Panel></div>
    <Modal title="Schedule interview" open={interviewOpen} onClose={()=>setInterviewOpen(false)}><div className="form-grid"><JobCandidateFields jobId={jobId} candidateId={jobCandidateId} jobs={jobs.data||[]} candidates={candidates} onJob={resetJob} onCandidate={setJobCandidateId}/><Field label="Starts"><Input type="datetime-local" value={startsAt} onChange={(event)=>setStartsAt(event.target.value)}/></Field><Field label="Ends"><Input type="datetime-local" value={endsAt} onChange={(event)=>setEndsAt(event.target.value)}/></Field><Field label="Location or call details"><Input value={location} onChange={(event)=>setLocation(event.target.value)}/></Field>{interviewMutation.error&&<p className="form-error full" role="alert">{interviewMutation.error.message}</p>}<div className="form-actions full"><Button variant="quiet" onClick={()=>setInterviewOpen(false)}>Cancel</Button><Button disabled={!jobCandidateId||!startsAt||!endsAt||interviewMutation.isPending} onClick={()=>interviewMutation.mutate()}>Schedule</Button></div></div></Modal>
    <Modal title="Record offer" open={offerOpen} onClose={()=>setOfferOpen(false)}><div className="form-grid"><JobCandidateFields jobId={jobId} candidateId={jobCandidateId} jobs={jobs.data||[]} candidates={candidates} onJob={resetJob} onCandidate={setJobCandidateId}/><Field label="Salary"><Input type="number" min="0" value={salary} onChange={(event)=>setSalary(event.target.value)}/></Field><Field label="Currency"><Input maxLength={3} value={currency} onChange={(event)=>setCurrency(event.target.value.toUpperCase())}/></Field><Field label="Proposed start"><Input type="date" value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></Field>{offerMutation.error&&<p className="form-error full" role="alert">{offerMutation.error.message}</p>}<div className="form-actions full"><Button variant="quiet" onClick={()=>setOfferOpen(false)}>Cancel</Button><Button disabled={!jobCandidateId||!salary||offerMutation.isPending} onClick={()=>offerMutation.mutate()}>Record offer</Button></div></div></Modal>
    <Modal title="Convert accepted offer to placement" open={Boolean(convertOffer)} onClose={()=>setConvertOffer(null)}><div className="stack"><p>{convertOffer?.job_candidates?.candidates?.full_name} · {formatMoney(convertOffer?.salary,convertOffer?.currency)}</p><Field label="Placement fee"><Input type="number" min="0" value={fee} onChange={(event)=>setFee(event.target.value)}/></Field><p className="muted">The default guarantee is 90 days. The conversion records the placement, moves the candidate to Placed, and fills the job transactionally.</p>{convertMutation.error&&<p className="form-error" role="alert">{convertMutation.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setConvertOffer(null)}>Cancel</Button><Button disabled={!fee||convertMutation.isPending} onClick={()=>convertMutation.mutate()}>Create placement</Button></div></div></Modal>
  </Page>
}

function JobCandidateFields({jobId,candidateId,jobs,candidates,onJob,onCandidate}:{jobId:string;candidateId:string;jobs:Array<{id:string;title:string}>;candidates:JobCandidate[];onJob:(id:string)=>void;onCandidate:(id:string)=>void}){return <><Field label="Vacancy"><Select value={jobId} onChange={(event)=>onJob(event.target.value)}><option value="">Select vacancy</option>{jobs.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</Select></Field><Field label="Candidate"><Select value={candidateId} onChange={(event)=>onCandidate(event.target.value)}><option value="">Select candidate</option>{candidates.map((item)=><option key={item.id} value={item.id}>{item.candidates?.full_name}</option>)}</Select></Field></>}
