import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {CalendarPlus,ExternalLink,Handshake,Plus,RefreshCw} from 'lucide-react'
import {useOrganization} from '../../app/OrganizationProvider'
import {useAuth} from '../../app/AuthProvider'
import {cancelInterview,convertOfferToPlacement,createInterview,createOffer,getPipeline,listInterviews,listJobs,listOffers,updateInterview,updateOfferStatus} from '../core/repository'
import {listCalendarConnections,syncInterviewCalendar} from '../core/commercialRepository'
import type {Interview,JobCandidate,Offer} from '../../shared/types/domain'
import {Button} from '../../shared/ui/Button'
import {Field,Input,Select} from '../../shared/ui/Field'
import {Modal} from '../../shared/ui/Modal'
import {Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {calendarSyncStatus,offerStatus} from '../../shared/lib/status'
import {EmptyState,ErrorState,LoadingState} from '../../shared/ui/States'
import {formatDate,formatDateTime,formatMoney} from '../../shared/lib/format'

const emails=(value:string)=>value.split(',').map((item)=>item.trim().toLowerCase()).filter(Boolean)
const localValue=(value:string)=>{const date=new Date(value);const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16)}

export function DeliveryPage(){
  const {organization,memberships}=useOrganization();const {user}=useAuth();const cache=useQueryClient()
  const currentMember=memberships.find((item)=>item.organization_id===organization?.id&&item.user_id===user?.id)
  const [interviewOpen,setInterviewOpen]=useState(false);const [editing,setEditing]=useState<Interview|null>(null);const [offerOpen,setOfferOpen]=useState(false);const [convertOffer,setConvertOffer]=useState<Offer|null>(null)
  const [jobId,setJobId]=useState('');const [jobCandidateId,setJobCandidateId]=useState('');const [startsAt,setStartsAt]=useState('');const [endsAt,setEndsAt]=useState('');const [location,setLocation]=useState('');const [attendeeEmails,setAttendeeEmails]=useState('');const [createMeet,setCreateMeet]=useState(false);const [syncCalendar,setSyncCalendar]=useState(true)
  const [salary,setSalary]=useState('');const [startDate,setStartDate]=useState('');const [fee,setFee]=useState('');const [currency,setCurrency]=useState(organization?.base_currency||'USD')
  const jobs=useQuery({queryKey:['jobs',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobs(organization!.id)});const job=jobs.data?.find((item)=>item.id===jobId)
  const pipeline=useQuery({queryKey:['pipeline',jobId],enabled:Boolean(job),queryFn:()=>getPipeline(job!)});const interviews=useQuery({queryKey:['interviews',organization?.id],enabled:Boolean(organization),queryFn:()=>listInterviews(organization!.id)});const offers=useQuery({queryKey:['offers',organization?.id],enabled:Boolean(organization),queryFn:()=>listOffers(organization!.id)});const connections=useQuery({queryKey:['calendar-connections',organization?.id],enabled:Boolean(organization),queryFn:()=>listCalendarConnections(organization!.id)})
  const calendarConnected=connections.data?.some((item)=>item.member_id===currentMember?.id&&item.status==='connected')||false
  const refresh=async()=>{await Promise.all([cache.invalidateQueries({queryKey:['interviews',organization?.id]}),cache.invalidateQueries({queryKey:['offers',organization?.id]}),cache.invalidateQueries({queryKey:['placements',organization?.id]}),cache.invalidateQueries({queryKey:['jobs',organization?.id]})])}
  const resetInterview=()=>{setEditing(null);setJobId('');setJobCandidateId('');setStartsAt('');setEndsAt('');setLocation('');setAttendeeEmails('');setCreateMeet(false);setSyncCalendar(calendarConnected)}
  const openNewInterview=()=>{resetInterview();setInterviewOpen(true)}
  const openEditInterview=(item:Interview)=>{setEditing(item);setJobCandidateId(item.job_candidate_id);setStartsAt(localValue(item.starts_at));setEndsAt(localValue(item.ends_at));setLocation(item.location||'');setAttendeeEmails(item.attendee_emails.join(', '));setCreateMeet(item.create_google_meet);setSyncCalendar(Boolean(item.organizer_member_id));setInterviewOpen(true)}
  const interviewMutation=useMutation({mutationFn:async()=>{const input={starts_at:new Date(startsAt).toISOString(),ends_at:new Date(endsAt).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,location,attendee_emails:emails(attendeeEmails),create_google_meet:createMeet};let id=editing?.id;if(id)await updateInterview(organization!.id,id,input);else id=await createInterview(organization!.id,user!.id,{...input,job_candidate_id:jobCandidateId,interview_type:'client_interview',organizer_member_id:syncCalendar?currentMember?.id:undefined});if(syncCalendar&&id)await syncInterviewCalendar(organization!.id,id);return id},onSuccess:async()=>{setInterviewOpen(false);resetInterview();await refresh()}})
  const retryMutation=useMutation({mutationFn:(id:string)=>syncInterviewCalendar(organization!.id,id),onSettled:refresh})
  const cancelMutation=useMutation({mutationFn:async(item:Interview)=>{await cancelInterview(organization!.id,item.id);if(item.organizer_member_id)await syncInterviewCalendar(organization!.id,item.id,'cancel')},onSettled:refresh})
  const offerMutation=useMutation({mutationFn:()=>createOffer(organization!.id,user!.id,{job_candidate_id:jobCandidateId,salary:Number(salary),currency,start_date:startDate||undefined}),onSuccess:async()=>{setOfferOpen(false);await refresh()}})
  const statusMutation=useMutation({mutationFn:({id,status}:{id:string;status:'accepted'|'declined'|'withdrawn'})=>updateOfferStatus(id,status),onSuccess:refresh})
  const convertMutation=useMutation({mutationFn:()=>convertOfferToPlacement(convertOffer!.id,Number(fee),90),onSuccess:async()=>{setConvertOffer(null);setFee('');await refresh()}})
  const candidates:JobCandidate[]=pipeline.data?.items||[];const resetJob=(value:string)=>{setJobId(value);setJobCandidateId('')}
  if(interviews.isLoading||offers.isLoading)return <LoadingState/>;if(interviews.error||offers.error)return <ErrorState error={interviews.error||offers.error}/>
  return <Page title="Interviews & offers" eyebrow="Delivery milestones" description="Schedule interviews in the ATS, synchronize them to Google Calendar, and convert accepted offers into placements." actions={<><Button variant="secondary" leadingIcon={<CalendarPlus size={15}/>} onClick={openNewInterview}>Schedule interview</Button><Button leadingIcon={<Plus size={15}/>} onClick={()=>setOfferOpen(true)}>Record offer</Button></>}>
    <div className="two-column"><Panel title="Interviews"><div className="list">{interviews.data?.length===0?<EmptyState title="No interviews" description="Schedule the next client conversation."/>:interviews.data?.map((interview)=><article className="list-row delivery-row" key={interview.id}><div><strong>{interview.job_candidates?.candidates?.full_name||'Candidate'}</strong><span>{interview.job_candidates?.jobs?.title} · {interview.location||interview.meeting_url||'Location pending'}</span><time dateTime={interview.starts_at}>{formatDateTime(interview.starts_at)}</time>{interview.calendar_last_error&&<small className="form-error">Calendar sync failed: {interview.calendar_last_error}</small>}</div><div className="table-actions"><StatusBadge map={calendarSyncStatus} value={interview.calendar_sync_status}/>{interview.calendar_event_url&&<a className="button button-secondary" href={interview.calendar_event_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Calendar</a>}{interview.status!=='cancelled'&&<Button variant="secondary" onClick={()=>openEditInterview(interview)}>Edit</Button>}{interview.calendar_sync_status==='failed'&&<Button variant="secondary" disabled={retryMutation.isPending} leadingIcon={<RefreshCw size={14}/>} onClick={()=>retryMutation.mutate(interview.id)}>Retry</Button>}{interview.status!=='cancelled'&&<Button variant="caution" disabled={cancelMutation.isPending} onClick={()=>cancelMutation.mutate(interview)}>Cancel</Button>}</div></article>)}</div></Panel>
    <Panel title="Offers"><div className="list">{offers.data?.length===0?<EmptyState title="No offers" description="Record an offer when a candidate reaches the commercial stage."/>:offers.data?.map((offer)=><article className="list-row" key={offer.id}><div><strong>{offer.job_candidates?.candidates?.full_name||'Candidate'}</strong><span>{offer.job_candidates?.jobs?.title} · {formatMoney(offer.salary,offer.currency)} · start {formatDate(offer.start_date)}</span></div><div className="table-actions"><StatusBadge map={offerStatus} value={offer.status}/>{offer.status==='presented'&&<><Button variant="secondary" onClick={()=>statusMutation.mutate({id:offer.id,status:'declined'})}>Decline</Button><Button onClick={()=>statusMutation.mutate({id:offer.id,status:'accepted'})}>Accept</Button></>}{offer.status==='accepted'&&<><Button variant="secondary" onClick={()=>statusMutation.mutate({id:offer.id,status:'withdrawn'})}>Withdraw</Button><Button leadingIcon={<Handshake size={15}/>} onClick={()=>setConvertOffer(offer)}>Place</Button></>}</div></article>)}</div></Panel></div>
    <Modal title={editing?'Edit interview':'Schedule interview'} open={interviewOpen} onClose={()=>setInterviewOpen(false)}><div className="form-grid">{!editing&&<JobCandidateFields jobId={jobId} candidateId={jobCandidateId} jobs={jobs.data||[]} candidates={candidates} onJob={resetJob} onCandidate={setJobCandidateId}/>}<Field label="Starts"><Input type="datetime-local" value={startsAt} onChange={(event)=>setStartsAt(event.target.value)}/></Field><Field label="Ends"><Input type="datetime-local" value={endsAt} onChange={(event)=>setEndsAt(event.target.value)}/></Field><Field label="Location or call details"><Input value={location} onChange={(event)=>setLocation(event.target.value)}/></Field><Field label="Attendee emails"><Input value={attendeeEmails} placeholder="client@example.com, candidate@example.com" onChange={(event)=>setAttendeeEmails(event.target.value)}/></Field><label className="check-row full"><input type="checkbox" checked={syncCalendar} disabled={!calendarConnected} onChange={(event)=>setSyncCalendar(event.target.checked)}/><span>Synchronize to my connected Google Calendar and send attendee updates</span></label><label className="check-row full"><input type="checkbox" checked={createMeet} disabled={!syncCalendar} onChange={(event)=>setCreateMeet(event.target.checked)}/><span>Create a Google Meet link</span></label>{!calendarConnected&&<p className="warning-box full">Connect Google Calendar in Settings to enable synchronization. The interview can still be saved in the ATS.</p>}{interviewMutation.error&&<p className="form-error full" role="alert">{interviewMutation.error.message}</p>}<div className="form-actions full"><Button variant="quiet" onClick={()=>setInterviewOpen(false)}>Cancel</Button><Button disabled={(!editing&&!jobCandidateId)||!startsAt||!endsAt||interviewMutation.isPending} onClick={()=>interviewMutation.mutate()}>{interviewMutation.isPending?'Saving…':'Save interview'}</Button></div></div></Modal>
    <Modal title="Record offer" open={offerOpen} onClose={()=>setOfferOpen(false)}><div className="form-grid"><JobCandidateFields jobId={jobId} candidateId={jobCandidateId} jobs={jobs.data||[]} candidates={candidates} onJob={resetJob} onCandidate={setJobCandidateId}/><Field label="Salary"><Input type="number" min="0" value={salary} onChange={(event)=>setSalary(event.target.value)}/></Field><Field label="Currency"><Input maxLength={3} value={currency} onChange={(event)=>setCurrency(event.target.value.toUpperCase())}/></Field><Field label="Proposed start"><Input type="date" value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></Field>{offerMutation.error&&<p className="form-error full" role="alert">{offerMutation.error.message}</p>}<div className="form-actions full"><Button variant="quiet" onClick={()=>setOfferOpen(false)}>Cancel</Button><Button disabled={!jobCandidateId||!salary||offerMutation.isPending} onClick={()=>offerMutation.mutate()}>Record offer</Button></div></div></Modal>
    <Modal title="Convert accepted offer to placement" open={Boolean(convertOffer)} onClose={()=>setConvertOffer(null)}><div className="stack"><p>{convertOffer?.job_candidates?.candidates?.full_name} · {formatMoney(convertOffer?.salary,convertOffer?.currency)}</p><Field label="Placement fee"><Input type="number" min="0" value={fee} onChange={(event)=>setFee(event.target.value)}/></Field><p className="muted">The default guarantee is 90 days. Conversion records the placement, moves the candidate to Placed, and fills the job transactionally.</p>{convertMutation.error&&<p className="form-error" role="alert">{convertMutation.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setConvertOffer(null)}>Cancel</Button><Button disabled={!fee||convertMutation.isPending} onClick={()=>convertMutation.mutate()}>Create placement</Button></div></div></Modal>
  </Page>
}

function JobCandidateFields({jobId,candidateId,jobs,candidates,onJob,onCandidate}:{jobId:string;candidateId:string;jobs:Array<{id:string;title:string}>;candidates:JobCandidate[];onJob:(id:string)=>void;onCandidate:(id:string)=>void}){return <><Field label="Vacancy"><Select value={jobId} onChange={(event)=>onJob(event.target.value)}><option value="">Select vacancy</option>{jobs.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</Select></Field><Field label="Candidate"><Select value={candidateId} onChange={(event)=>onCandidate(event.target.value)}><option value="">Select candidate</option>{candidates.map((item)=><option key={item.id} value={item.id}>{item.candidates?.full_name}</option>)}</Select></Field></>}
