import {supabase} from '../../shared/lib/supabase'
import {AppError} from '../../shared/lib/errors'
import type {CalendarConnection,CandidateDetail,CandidateDocument,ImportBatch,OrganizationInvitation,PipelinePhaseKey,Role,TeamMember} from '../../shared/types/domain'
import type {Json} from '../../generated/database.types'
import {candidateCvExtractionSchema,type CandidateCvExtraction,type CvParseResult} from '../candidates/cvParsing'
import {candidateProfileDraftSchema,candidateProfileTemplateConfigSchema,hasStaleProfileInputs,type CandidateProfileGeneration,type CandidateProfileJob,type CandidateProfileTemplate,type CandidateProfileVersion} from '../candidates/candidateProfile'

function fail(error:{message:string;code?:string}|null,fallback:string):never{throw new AppError(error?.message||fallback,error?.code||'database_error',error)}
async function invoke<T>(name:string,body:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.functions.invoke(name,{body});if(error)throw new AppError(error.message,'function_error',error);if((data as {error?:{message?:string;code?:string}})?.error)throw new AppError((data as {error:{message?:string}}).error.message||'Request failed.',(data as {error:{code?:string}}).error.code||'function_error',data);return data as T}

export async function listTeamMembers(organizationId:string){const {data,error}=await supabase.from('organization_members').select('id,organization_id,user_id,job_title,status,is_vendor_support,profiles:user_id(full_name,email),member_roles(roles(id,name,role_key))').eq('organization_id',organizationId).order('joined_at');if(error)fail(error,'Could not load team members');return (data||[]) as unknown as TeamMember[]}
export async function listOrganizationRoles(organizationId:string){const {data,error}=await supabase.from('roles').select('id,name,role_key,is_system,role_permissions(permission_key)').eq('organization_id',organizationId).order('name');if(error)fail(error,'Could not load roles');return (data||[]) as unknown as Role[]}
export async function listInvitations(organizationId:string){const {data,error}=await supabase.from('organization_invitations').select('id,email,role_id,expires_at,accepted_at,revoked_at,delivery_status,last_sent_at,roles(name)').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)fail(error,'Could not load invitations');return (data||[]) as unknown as OrganizationInvitation[]}
export function sendTeamInvitation(organizationId:string,email:string,roleId:string){return invoke<{invitationId:string;expiresAt:string;deliveryStatus:string;previewUrl?:string}>('send-invitation',{organizationId,email,roleId})}
export async function revokeInvitation(invitationId:string){const {error}=await supabase.rpc('revoke_organization_invitation',{p_invitation_id:invitationId});if(error)fail(error,'Could not revoke invitation')}
export async function updateMemberAccess(organizationId:string,memberId:string,status:'active'|'suspended',roleId:string){const {error}=await supabase.rpc('update_member_access',{p_organization_id:organizationId,p_member_id:memberId,p_status:status,p_role_id:roleId});if(error)fail(error,'Could not update member access')}
export async function updateOrganizationAccent(organizationId:string,primaryColor:string){if(!/^#[0-9a-f]{6}$/i.test(primaryColor))throw new AppError('Choose a valid six-digit hex color.','invalid_accent');const {error}=await supabase.from('organization_settings').update({primary_color:primaryColor,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error)fail(error,'Could not update organization branding')}
export async function uploadOrganizationLogo(organizationId:string,file:File,previousPath?:string|null){const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.type))throw new AppError('Use a PNG, JPG, or WebP logo.','invalid_logo_type');if(file.size>2*1024*1024)throw new AppError('Logo files are limited to 2 MB.','logo_too_large');const extension=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const storagePath=`${organizationId}/logo-${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from('organization-assets').upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(upload.error)fail(upload.error,'Could not upload organization logo');const {error}=await supabase.from('organization_settings').update({logo_path:storagePath,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error){await supabase.storage.from('organization-assets').remove([storagePath]);fail(error,'Could not save organization logo')}if(previousPath&&previousPath!==storagePath)await supabase.storage.from('organization-assets').remove([previousPath]);return storagePath}
export async function removeOrganizationLogo(organizationId:string,logoPath:string){const {error}=await supabase.from('organization_settings').update({logo_path:null,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error)fail(error,'Could not remove organization logo');const removed=await supabase.storage.from('organization-assets').remove([logoPath]);if(removed.error)fail(removed.error,'Logo setting was cleared, but the old file could not be removed')}

export async function listCalendarConnections(organizationId:string){const {data,error}=await supabase.from('google_calendar_connections').select('id,organization_id,member_id,google_email,calendar_id,status,connected_at,last_synced_at,last_error').eq('organization_id',organizationId);if(error)fail(error,'Could not load Calendar connections');return (data||[]) as unknown as CalendarConnection[]}
export function startCalendarConnection(organizationId:string,returnPath:string){return invoke<{authorizationUrl:string}>('calendar-auth-start',{organizationId,returnPath})}
export function disconnectCalendar(organizationId:string){return invoke<{status:string}>('calendar-disconnect',{organizationId})}
export function syncInterviewCalendar(organizationId:string,interviewId:string,action:'sync'|'cancel'='sync'){return invoke<{status:string;eventId?:string}>('calendar-sync',{organizationId,interviewId,action})}
export async function listSubmissionCandidateDocuments(organizationId:string,jobId:string){const {data,error}=await supabase.from('job_candidates').select('id,candidate_id,candidates(id,full_name,current_company,current_position,document_links(documents(id,file_name,original_filename,mime_type,storage_path,size_bytes,created_at,deleted_at)))').eq('organization_id',organizationId).eq('job_id',jobId);if(error)fail(error,'Could not load submission candidates');return data||[]}
export function sendClientSubmission(input:{organizationId:string;jobId:string;contactId?:string;title:string;message?:string;recipientName?:string;recipientEmail:string;expiryDays:number;items:Array<Record<string,unknown>>}){return invoke<{packageId:string;expiresAt:string;deliveryStatus:string;previewUrl?:string}>('send-submission',input)}
export async function revokeSubmissionLink(linkId:string){const {error}=await supabase.rpc('revoke_submission_link',{p_link_id:linkId});if(error)fail(error,'Could not revoke submission link')}

export async function getCandidateDetail(organizationId:string,candidateId:string){const {data,error}=await supabase.from('candidates').select('*,candidate_private_details(*),candidate_employment(*),candidate_education(*),candidate_languages(*),candidate_skills(skill_id,proficiency,years_experience,skills(id,name)),candidate_tags(tag_id,tags(id,name,color))').eq('organization_id',organizationId).eq('id',candidateId).single();if(error)fail(error,'Could not load candidate');return data as unknown as CandidateDetail}
export async function updateCandidateProfile(organizationId:string,candidateId:string,values:Record<string,unknown>,privateValues:Record<string,unknown>){const {error}=await supabase.rpc('update_candidate_profile',{p_organization_id:organizationId,p_candidate_id:candidateId,p_candidate:values as Json,p_private:privateValues as Json});if(error)fail(error,'Could not update candidate')}
export async function setCandidateArchived(organizationId:string,candidateId:string,archived:boolean){const {error}=await supabase.from('candidates').update({deleted_at:archived?new Date().toISOString():null,status:archived?'archived':'active'}).eq('organization_id',organizationId).eq('id',candidateId);if(error)fail(error,archived?'Could not archive candidate':'Could not restore candidate')}
export async function mergeCandidates(organizationId:string,keptCandidateId:string,mergedCandidateId:string,reason:string){const {data,error}=await supabase.rpc('merge_candidates',{p_organization_id:organizationId,p_kept_candidate_id:keptCandidateId,p_merged_candidate_id:mergedCandidateId,p_reason:reason});if(error)fail(error,error.message.includes('merge_conflicting_job_assignments')?'These candidates are both assigned to the same vacancy. Resolve that pipeline conflict before merging.':'Could not merge candidates');return data as string}
export async function listCandidateDocuments(organizationId:string,candidateId:string){const {data,error}=await supabase.from('document_links').select('documents!inner(id,file_name,original_filename,mime_type,storage_path,size_bytes,document_type,created_at,deleted_at)').eq('organization_id',organizationId).eq('candidate_id',candidateId);if(error)fail(error,'Could not load documents');const documents=(data||[]).flatMap((item)=>{const value=item.documents as unknown as CandidateDocument|CandidateDocument[];return Array.isArray(value)?value:[value]}).filter((document)=>document&&!('deleted_at' in document&&document.deleted_at));return Promise.all(documents.map(async(document)=>{const {data:signed}=await supabase.storage.from('candidate-documents').createSignedUrl(document.storage_path,300);return {...document,signedUrl:signed?.signedUrl}}))}
export async function uploadCandidateDocument(organizationId:string,candidateId:string,userId:string,file:File){if(file.size>25*1024*1024)throw new AppError('Documents are limited to 25 MB.','file_too_large');const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/${candidateId}/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:file.type||'application/octet-stream',upsert:false});if(upload.error)fail(upload.error,'Could not upload document');const {data:document,error}=await supabase.from('documents').insert({organization_id:organizationId,file_name:safeName,original_filename:file.name,storage_path:storagePath,mime_type:file.type||'application/octet-stream',size_bytes:file.size,document_type:'resume',uploaded_by:userId}).select('id').single();if(error){await supabase.storage.from('candidate-documents').remove([storagePath]);fail(error,'Could not register document')}const link=await supabase.from('document_links').insert({organization_id:organizationId,document_id:document.id,candidate_id:candidateId});if(link.error){await Promise.all([supabase.from('documents').delete().eq('id',document.id),supabase.storage.from('candidate-documents').remove([storagePath])]);fail(link.error,'Could not link document')}return document.id as string}
export async function uploadCandidateProfileDocument(organizationId:string,candidateId:string,userId:string,file:File){const allowed=['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document'];if(!allowed.includes(file.type))throw new AppError('Candidate profiles must be DOCX or PDF.','invalid_profile_document');const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/${candidateId}/profiles/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:file.type,upsert:false});if(upload.error)fail(upload.error,'Could not upload generated profile');const {data:document,error}=await supabase.from('documents').insert({organization_id:organizationId,file_name:safeName,original_filename:file.name,storage_path:storagePath,mime_type:file.type,size_bytes:file.size,document_type:'candidate_profile',uploaded_by:userId}).select('id').single();if(error){await supabase.storage.from('candidate-documents').remove([storagePath]);fail(error,'Could not register generated profile')}const link=await supabase.from('document_links').insert({organization_id:organizationId,document_id:document.id,candidate_id:candidateId});if(link.error){await Promise.all([supabase.from('documents').delete().eq('id',document.id),supabase.storage.from('candidate-documents').remove([storagePath])]);fail(link.error,'Could not link generated profile')}return {id:document.id as string,storagePath}}
export async function discardCandidateProfileDocument(organizationId:string,document:{id:string;storagePath:string}){await Promise.all([supabase.from('documents').delete().eq('organization_id',organizationId).eq('id',document.id),supabase.storage.from('candidate-documents').remove([document.storagePath])])}
export async function deleteCandidateDocument(organizationId:string,documentId:string,storagePath:string){const {error}=await supabase.from('documents').update({deleted_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',documentId);if(error)fail(error,'Could not archive document');await supabase.storage.from('candidate-documents').remove([storagePath])}
const pdfMime='application/pdf';const docxMime='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
function cvMime(file:File){if(file.type===pdfMime||file.type===docxMime)return file.type;const name=file.name.toLowerCase();if(name.endsWith('.pdf'))return pdfMime;if(name.endsWith('.docx'))return docxMime;throw new AppError('Upload a PDF or DOCX CV.','unsupported_cv_type')}
export async function startCandidateCvParse(organizationId:string,userId:string,file:File,targetCandidateId?:string|null){const mimeType=cvMime(file);const max=mimeType===docxMime?10*1024*1024:25*1024*1024;if(file.size<1||file.size>max)throw new AppError(mimeType===docxMime?'DOCX CVs are limited to 10 MB.':'PDF CVs are limited to 25 MB.','cv_too_large');const parseId=crypto.randomUUID();const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/cv-drafts/${userId}/${parseId}/${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:mimeType,upsert:false});if(upload.error)fail(upload.error,'Could not upload CV');try{await invoke<{parseId:string}>('parse-candidate-cv',{action:'start',organizationId,parseId,storagePath,originalFilename:file.name,mimeType,targetCandidateId:targetCandidateId||null});return parseId}catch(error){await supabase.storage.from('candidate-documents').remove([storagePath]);throw error}}
export async function getCandidateCvParse(organizationId:string,parseId:string){const result=await invoke<CvParseResult>('parse-candidate-cv',{action:'status',organizationId,parseId});if(result.extraction)result.extraction=candidateCvExtractionSchema.parse(result.extraction);return result}
export async function retryCandidateCvParse(organizationId:string,parseId:string){return invoke<{parseId:string}>('parse-candidate-cv',{action:'retry',organizationId,parseId})}
export async function cancelCandidateCvParse(organizationId:string,parseId:string){return invoke<{parseId:string}>('parse-candidate-cv',{action:'cancel',organizationId,parseId})}
export async function acceptCandidateCvParse(organizationId:string,parseId:string,extraction:CandidateCvExtraction,targetCandidateId?:string|null){const payload=candidateCvExtractionSchema.parse(extraction);const {data,error}=await supabase.rpc('accept_candidate_cv_parse',{p_organization_id:organizationId,p_parse_id:parseId,p_payload:payload as unknown as Json,p_target_candidate_id:targetCandidateId||undefined});if(error)fail(error,error.message.includes('duplicate_candidate')?'A candidate with this email already exists.':'Could not save the parsed CV');return data as string}
export async function listCandidateJobs(organizationId:string,candidateId:string):Promise<CandidateProfileJob[]>{const {data,error}=await supabase.from('job_candidates').select('jobs!inner(id,title,deleted_at,companies(name))').eq('organization_id',organizationId).eq('candidate_id',candidateId);if(error)fail(error,'Could not load linked vacancies');return (data||[]).map((row)=>{const job=row.jobs as unknown as {id:string;title:string;deleted_at:string|null;companies:{name:string}|null};return job}).filter((job)=>job&&!job.deleted_at).map((job)=>({id:job.id,title:job.title,company_name:job.companies?.name||null}))}
export async function hasOrganizationPermission(organizationId:string,permission:string){const {data,error}=await supabase.rpc('has_permission',{p_organization_id:organizationId,p_permission:permission});if(error)fail(error,'Could not check workspace permissions');return Boolean(data)}
export async function listCandidateProfileTemplates(organizationId:string):Promise<CandidateProfileTemplate[]>{const {data,error}=await supabase.from('templates').select('id,name,configuration,version,is_default,created_at,updated_at').eq('organization_id',organizationId).eq('template_type','candidate_profile').is('deleted_at',null).order('is_default',{ascending:false}).order('name');if(error)fail(error,'Could not load candidate profile templates');return (data||[]).map((item)=>({...item,configuration:candidateProfileTemplateConfigSchema.parse(item.configuration)}))}
export async function saveCandidateProfileTemplate(organizationId:string,input:{id?:string;name:string;configuration:unknown;isDefault:boolean}){const configuration=candidateProfileTemplateConfigSchema.parse(input.configuration);const {data,error}=await supabase.rpc('save_candidate_profile_template',{p_organization_id:organizationId,p_template_id:input.id||null,p_name:input.name,p_configuration:configuration as unknown as Json,p_is_default:input.isDefault});if(error)fail(error,'Could not save candidate profile template');return data as string}
export async function archiveCandidateProfileTemplate(organizationId:string,templateId:string){const {error}=await supabase.rpc('archive_candidate_profile_template',{p_organization_id:organizationId,p_template_id:templateId});if(error)fail(error,error.message.includes('last_template_required')?'Keep at least one candidate profile template.':'Could not archive candidate profile template')}
export async function generateCandidateProfile(input:{organizationId:string;candidateId:string;jobId:string;templateId:string;anonymize:boolean}):Promise<CandidateProfileGeneration>{const result=await invoke<CandidateProfileGeneration>('generate-candidate-profile',input);return {...result,draft:candidateProfileDraftSchema.parse(result.draft),evaluation:{...result.evaluation,evidence:candidateProfileDraftSchema.shape.requirement_evidence.parse(result.evaluation.evidence)}}}
export async function listCandidateProfileVersions(organizationId:string,candidateId:string):Promise<CandidateProfileVersion[]>{const {data,error}=await supabase.from('candidate_profile_versions').select('id,version,status,candidate_id,job_id,template_id,template_version,generated_content,reviewed_content,input_versions,anonymized,docx_document_id,pdf_document_id,created_at,finalized_at,jobs(title,updated_at),templates(name,version),candidates!candidate_id(updated_at)').eq('organization_id',organizationId).eq('candidate_id',candidateId).order('created_at',{ascending:false});if(error)fail(error,'Could not load candidate profile versions');return (data||[]).map((item)=>{const job=item.jobs as unknown as {title:string;updated_at:string};const template=item.templates as unknown as {name:string;version:number};const candidate=item.candidates as unknown as {updated_at:string};const inputVersions=item.input_versions as Record<string,unknown>;return {...item,jobs:undefined,templates:undefined,candidates:undefined,generated_content:candidateProfileDraftSchema.parse(item.generated_content),reviewed_content:item.reviewed_content?candidateProfileDraftSchema.parse(item.reviewed_content):null,input_versions:inputVersions,job_title:job.title,template_name:template.name,stale:hasStaleProfileInputs(inputVersions,{candidateUpdatedAt:candidate.updated_at,jobUpdatedAt:job.updated_at,templateVersion:template.version})}}) as CandidateProfileVersion[]}
export async function finalizeCandidateProfile(input:{organizationId:string;profileVersionId:string;reviewedContent:unknown;anonymized:boolean;docxDocumentId:string;pdfDocumentId:string;editedFieldCount:number}){const reviewed=candidateProfileDraftSchema.parse(input.reviewedContent);const {data,error}=await supabase.rpc('finalize_candidate_profile',{p_organization_id:input.organizationId,p_profile_version_id:input.profileVersionId,p_reviewed_content:reviewed as unknown as Json,p_anonymized:input.anonymized,p_docx_document_id:input.docxDocumentId,p_pdf_document_id:input.pdfDocumentId,p_edited_field_count:input.editedFieldCount});if(error)fail(error,'Could not finalize candidate profile');return data as string}
export async function recordCandidateProfileExportFailure(organizationId:string,profileVersionId:string,reason:string){const {error}=await supabase.rpc('record_candidate_profile_export_failure',{p_organization_id:organizationId,p_profile_version_id:profileVersionId,p_reason:reason.slice(0,500)});if(error)console.error('Could not record candidate profile export failure',error)}
export async function addCandidateEmployment(organizationId:string,candidateId:string,values:{company_name:string;title:string;started_on?:string;ended_on?:string;is_current:boolean;summary?:string}){const {error}=await supabase.from('candidate_employment').insert({...values,organization_id:organizationId,candidate_id:candidateId,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on?'day':null,ended_on_precision:values.ended_on?'day':null,summary:values.summary||null});if(error)fail(error,'Could not add employment')}
export async function addCandidateEducation(organizationId:string,candidateId:string,values:{institution:string;degree?:string;field_of_study?:string;started_on?:string;ended_on?:string}){const {error}=await supabase.from('candidate_education').insert({...values,organization_id:organizationId,candidate_id:candidateId,degree:values.degree||null,field_of_study:values.field_of_study||null,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on?'day':null,ended_on_precision:values.ended_on?'day':null});if(error)fail(error,'Could not add education')}
export async function addCandidateLanguage(organizationId:string,candidateId:string,language:string,proficiency:string){const {error}=await supabase.from('candidate_languages').insert({organization_id:organizationId,candidate_id:candidateId,language:language.trim(),proficiency:proficiency.trim()||null});if(error)fail(error,'Could not add language')}
export async function addCandidateSkill(organizationId:string,candidateId:string,name:string,proficiency:string,yearsExperience?:number){const normalized=name.trim().toLowerCase().replace(/\s+/g,' ');let skillId:string;const existing=await supabase.from('skills').select('id').eq('organization_id',organizationId).eq('normalized_name',normalized).maybeSingle();if(existing.error)fail(existing.error,'Could not find skill');if(existing.data)skillId=existing.data.id;else{const created=await supabase.from('skills').insert({organization_id:organizationId,name:name.trim(),normalized_name:normalized}).select('id').single();if(created.error)fail(created.error,'Could not create skill');skillId=created.data.id}const {error}=await supabase.from('candidate_skills').upsert({organization_id:organizationId,candidate_id:candidateId,skill_id:skillId,proficiency:proficiency.trim()||null,years_experience:yearsExperience??null});if(error)fail(error,'Could not add skill')}
export async function addCandidateTag(organizationId:string,candidateId:string,name:string){const normalized=name.trim();let tagId:string;const existing=await supabase.from('tags').select('id').eq('organization_id',organizationId).ilike('name',normalized).maybeSingle();if(existing.error)fail(existing.error,'Could not find tag');if(existing.data)tagId=existing.data.id;else{const created=await supabase.from('tags').insert({organization_id:organizationId,name:normalized}).select('id').single();if(created.error)fail(created.error,'Could not create tag');tagId=created.data.id}const {error}=await supabase.from('candidate_tags').upsert({organization_id:organizationId,candidate_id:candidateId,tag_id:tagId});if(error)fail(error,'Could not add tag')}
export async function removeCandidateSkill(organizationId:string,candidateId:string,skillId:string){const {error}=await supabase.from('candidate_skills').delete().eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('skill_id',skillId);if(error)fail(error,'Could not remove skill')}
export async function removeCandidateTag(organizationId:string,candidateId:string,tagId:string){const {error}=await supabase.from('candidate_tags').delete().eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('tag_id',tagId);if(error)fail(error,'Could not remove tag')}
export async function deleteCandidateProfileItem(table:'candidate_employment'|'candidate_education'|'candidate_languages',organizationId:string,id:string){const {error}=await supabase.from(table).delete().eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not remove profile item')}

export async function getCompanyDetail(organizationId:string,id:string){const {data,error}=await supabase.from('companies').select('*,contacts(id,full_name,position,email,phone,contact_status),jobs(id,title,status,priority,updated_at)').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load company');return data as Record<string,unknown>}
export async function updateCompany(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('companies').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update company')}
export async function getContactDetail(organizationId:string,id:string){const {data,error}=await supabase.from('contacts').select('*,companies(id,name),job_contacts(jobs(id,title,status))').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load contact');return data as Record<string,unknown>}
export async function updateContact(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('contacts').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update contact')}
export async function getJobDetail(organizationId:string,id:string){const {data,error}=await supabase.from('jobs').select('*,companies(id,name),job_contacts(contacts(id,full_name,email)),job_team_members(organization_members(id,profiles:user_id(full_name,email)))').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load vacancy');return data as Record<string,unknown>}
export async function updateJob(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('jobs').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update vacancy')}
export async function updatePipelineStagePhase(organizationId:string,id:string,phaseKey:PipelinePhaseKey|null){const {error}=await supabase.from('pipeline_stages').update({phase_key:phaseKey}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update pipeline phase')}
export async function updateJobAssociations(organizationId:string,jobId:string,contactIds:string[],memberIds:string[]){const [contactsDelete,teamDelete]=await Promise.all([supabase.from('job_contacts').delete().eq('organization_id',organizationId).eq('job_id',jobId),supabase.from('job_team_members').delete().eq('organization_id',organizationId).eq('job_id',jobId)]);if(contactsDelete.error)fail(contactsDelete.error,'Could not update vacancy contacts');if(teamDelete.error)fail(teamDelete.error,'Could not update vacancy team');const results=await Promise.all([contactIds.length?supabase.from('job_contacts').insert(contactIds.map((contactId,index)=>({organization_id:organizationId,job_id:jobId,contact_id:contactId,is_primary:index===0}))):Promise.resolve({error:null}),memberIds.length?supabase.from('job_team_members').insert(memberIds.map((memberId)=>({organization_id:organizationId,job_id:jobId,member_id:memberId,team_role:'consultant'}))):Promise.resolve({error:null})]);if(results[0].error)fail(results[0].error,'Could not save vacancy contacts');if(results[1].error)fail(results[1].error,'Could not save vacancy team')}
export async function setRecordArchived(table:'companies'|'contacts'|'jobs',organizationId:string,id:string,archived:boolean){const deletedAt=archived?new Date().toISOString():null;if(table==='jobs'){const {error}=await supabase.from('jobs').update({deleted_at:deletedAt,status:archived?'cancelled':'open'}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status');return}if(table==='companies'){const {error}=await supabase.from('companies').update({deleted_at:deletedAt}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status');return}const {error}=await supabase.from('contacts').update({deleted_at:deletedAt}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status')}

export async function listImportBatches(organizationId:string){const {data,error}=await supabase.from('imports').select('id,entity_type,file_name,source_format,status,total_rows,valid_rows,failed_rows,validation_summary,reconciliation_summary,created_at,completed_at,rolled_back_at').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)fail(error,'Could not load imports');return (data||[]) as unknown as ImportBatch[]}
export async function listImportErrors(organizationId:string,importId:string){const {data,error}=await supabase.from('import_rows').select('row_number,source_data,errors').eq('organization_id',organizationId).eq('import_id',importId).eq('status','invalid').order('row_number');if(error)fail(error,'Could not load import errors');return data||[]}
export function stageImport(organizationId:string,entityType:string,fileName:string,sourceFormat:'csv'|'xlsx',rows:Array<Record<string,unknown>>){return invoke<{importId:string;totalRows:number;validRows:number;failedRows:number;status:string}>('execute-import',{organizationId,action:'stage',entityType,fileName,sourceFormat,rows})}
export function commitImport(organizationId:string,importId:string){return invoke<{status:string;committedRows:number}>('execute-import',{organizationId,action:'commit',importId})}
export function rollbackImport(organizationId:string,importId:string,rollbackReason:string){return invoke<{status:string}>('execute-import',{organizationId,action:'rollback',importId,rollbackReason})}

export async function getAgencyPerformance(organizationId:string,from:string,to:string){const [jobs,history,submissions,interviews,offers,placements,tasks]=await Promise.all([supabase.from('jobs').select('id,status,owner_member_id').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),supabase.from('stage_history').select('id,to_stage_id,pipeline_stages:to_stage_id(stage_type,name)').eq('organization_id',organizationId).gte('occurred_at',from).lte('occurred_at',to),supabase.from('submission_packages').select('id,created_by').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),supabase.from('interviews').select('id,created_by,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),supabase.from('offers').select('id,created_by,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),supabase.from('placements').select('id,created_by,placement_fee,currency,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),supabase.from('tasks').select('id,owner_member_id,status,due_at').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to)]);for(const result of [jobs,history,submissions,interviews,offers,placements,tasks])if(result.error)fail(result.error,'Could not load agency performance');return {jobs:jobs.data||[],history:history.data||[],submissions:submissions.data||[],interviews:interviews.data||[],offers:offers.data||[],placements:placements.data||[],tasks:tasks.data||[]}}

export async function createRevenueSplit(organizationId:string,placementId:string,memberId:string,percentage:number){const {error}=await supabase.rpc('create_placement_revenue_split',{p_organization_id:organizationId,p_placement_id:placementId,p_member_id:memberId,p_percentage:percentage});if(error)fail(error,error.message.includes('split_total_exceeds_100')?'Consultant credits cannot exceed 100%.':'Could not create revenue split')}
export async function createInvoice(organizationId:string,placementId:string,invoiceNumber:string,amount:number,currency:string,dueDate:string){const {error}=await supabase.from('placement_invoices').insert({organization_id:organizationId,placement_id:placementId,invoice_reference:invoiceNumber,amount,currency,due_on:dueDate,status:'draft'});if(error)fail(error,'Could not create invoice')}
export async function updateInvoiceStatus(organizationId:string,invoiceId:string,status:'issued'|'paid'|'void'){const values=status==='issued'?{status,issued_on:new Date().toISOString().slice(0,10)}:status==='paid'?{status,paid_on:new Date().toISOString().slice(0,10)}:{status};const {error}=await supabase.from('placement_invoices').update(values).eq('organization_id',organizationId).eq('id',invoiceId);if(error)fail(error,'Could not update invoice')}
