import {supabase} from '../../shared/lib/supabase'
import {AppError,humanizeRpcError} from '../../shared/lib/errors'
import {row,rows} from '../../shared/lib/rows'
import {calendarConnectionSchema,candidateDetailSchema,candidateJobLinkRowSchema,candidateProfileVersionRowSchema,companyPipelineRowSchema,documentLinkRowSchema,importBatchSchema,organizationInvitationSchema,roleSchema,savedViewSchema,submissionCandidateDocumentRowSchema,teamMemberSchema} from './commercialRepositorySchemas'
import type {CalendarConnection,CandidateDetail,CandidateDocument,CompanyPipelineRow,DeliveryStatus,ImportBatch,OrganizationInvitation,Role,SavedView,SavedViewResource,TeamMember,WorkspaceCapabilities} from '../../shared/types/domain'
import type {Json} from '../../generated/database.types'
import {candidateCvExtractionSchema,type CandidateCvExtraction,type CvParseResult} from '../candidates/cvParsing'
import {candidateProfileDraftSchema,candidateProfileTemplateConfigSchema,hasStaleProfileInputs,type CandidateProfileGeneration,type CandidateProfileJob,type CandidateProfileTemplate,type CandidateProfileVersion} from '../candidates/candidateProfile'
import type {CandidateProfileLists} from './repository'

function fail(error:{message:string;code?:string}|null,fallback:string):never{
  /* Raw RPC identifiers (`invalid_nonnegative_value`, `permission_denied`, ...) used to reach the user
   * verbatim, because this threw error.message unchanged. humanizeRpcError turns the ones the
   * migrations actually raise into sentences and keeps the token as the AppError code, so callers can
   * still branch on it. */
  const humanized=error?.message?humanizeRpcError(error.message):null
  if(humanized)throw new AppError(humanized.message,humanized.code,error)
  /* Postgres's own constraint violations are the other half of the leak, and the worse-looking half:
   * a unique-violation message is `duplicate key value violates unique constraint
   * "candidate_active_email_unique"`, which is what a recruitment consultant was shown when they
   * re-entered someone already in the database. For these SQLSTATEs the caller's fallback is the better
   * sentence by construction -- the caller knows which write it was attempting, the constraint name
   * does not. */
  if(error?.code&&CONSTRAINT_CODES.has(error.code))throw new AppError(fallback,error.code,error)
  throw new AppError(error?.message||fallback,error?.code||'database_error',error)
}
/* 23505 unique, 23503 foreign key, 23514 check, 23502 not-null: the four whose default text names a
 * constraint or a column rather than describing anything a user did. */
const CONSTRAINT_CODES=new Set(['23505','23503','23514','23502'])
async function invoke<T>(name:string,body:Record<string,unknown>):Promise<T>{const {data,error}=await supabase.functions.invoke(name,{body});if(error)throw new AppError(error.message,'function_error',error);if((data as {error?:{message?:string;code?:string}})?.error)throw new AppError((data as {error:{message?:string}}).error.message||'Request failed.',(data as {error:{code?:string}}).error.code||'function_error',data);return data as T}

export async function listTeamMembers(organizationId:string){const {data,error}=await supabase.from('organization_members').select('id,organization_id,user_id,job_title,status,is_vendor_support,profiles:user_id(full_name,email),member_roles(roles(id,name,role_key))').eq('organization_id',organizationId).order('joined_at');if(error)fail(error,'Could not load team members');return rows(data,teamMemberSchema,'Team member rows did not match the expected shape') as TeamMember[]}
export async function listOrganizationRoles(organizationId:string){const {data,error}=await supabase.from('roles').select('id,name,role_key,is_system,role_permissions(permission_key)').eq('organization_id',organizationId).order('name');if(error)fail(error,'Could not load roles');return rows(data,roleSchema,'Role rows did not match the expected shape') as Role[]}
export async function listInvitations(organizationId:string){const [invitations,deliveries]=await Promise.all([supabase.from('organization_invitations').select('id,email,role_id,expires_at,accepted_at,revoked_at,delivery_status,last_sent_at,roles(name)').eq('organization_id',organizationId).order('created_at',{ascending:false}),supabase.from('email_deliveries').select('id,status,error_message,related_entity_id').eq('organization_id',organizationId).eq('email_type','team_invitation')]);if(invitations.error)fail(invitations.error,'Could not load invitations');if(deliveries.error)fail(deliveries.error,'Could not load invitation delivery status');const deliveryByInvitation=new Map((deliveries.data||[]).map((delivery)=>[delivery.related_entity_id,delivery]));return (rows(invitations.data,organizationInvitationSchema,'Invitation rows did not match the expected shape') as OrganizationInvitation[]).map((invitation)=>{const delivery=deliveryByInvitation.get(invitation.id);return {...invitation,email_delivery:delivery?{id:delivery.id,status:delivery.status as DeliveryStatus,error_message:delivery.error_message}:null}})}
export function sendTeamInvitation(organizationId:string,email:string,roleId:string,requestKey:string){return invoke<{invitationId:string;deliveryId:string;expiresAt:string;deliveryStatus:string;errorMessage?:string;previewUrl?:string}>('send-invitation',{organizationId,email,roleId,requestKey})}
export function retryTeamInvitation(organizationId:string,deliveryId:string){return invoke<{invitationId:string;deliveryId:string;expiresAt:string;deliveryStatus:string;errorMessage?:string}>('send-invitation',{action:'retry',organizationId,deliveryId})}
export async function revokeInvitation(invitationId:string){const {error}=await supabase.rpc('revoke_organization_invitation',{p_invitation_id:invitationId});if(error)fail(error,'Could not revoke invitation')}
export async function updateMemberAccess(organizationId:string,memberId:string,status:'active'|'suspended',roleId:string){const {error}=await supabase.rpc('update_member_access',{p_organization_id:organizationId,p_member_id:memberId,p_status:status,p_role_id:roleId});if(error)fail(error,'Could not update member access')}
export async function updateOrganizationSalaryPeriod(organizationId:string,salaryPeriod:'annual'|'monthly'){const {error}=await supabase.rpc('update_organization_salary_period',{p_organization_id:organizationId,p_salary_period:salaryPeriod});if(error)fail(error,'Could not update salary period')}
export async function getCandidateRetentionOverview(organizationId:string){const [settings,preview]=await Promise.all([supabase.from('organization_settings').select('candidate_retention_months').eq('organization_id',organizationId).single(),supabase.rpc('preview_candidate_retention',{p_organization_id:organizationId})]);if(settings.error)fail(settings.error,'Could not load the retention policy');if(preview.error)fail(preview.error,'Could not preview candidate retention');const counts=preview.data?.[0];return {months:settings.data.candidate_retention_months,dueCount:Number(counts?.due_count||0),legalHoldCount:Number(counts?.legal_hold_count||0),oldestDueAt:counts?.oldest_due_at||null}}
/* The retention worker runs on pg_cron inside this project (20260810000000_scheduled_maintenance.sql).
 * A schedule that stops has to be visible where an owner actually looks, not only in an operator's
 * logs -- this is what backs the staleness banner on the Admin page. */
export type MaintenanceHealth={jobKey:string;lastSuccessfulRunAt:string|null;lastRunAt:string|null;lastStatus:string;lastError:string|null;staleAfterHours:number;isStale:boolean}
export async function getMaintenanceHealth(organizationId:string):Promise<MaintenanceHealth[]>{
  const {data,error}=await supabase.rpc('get_maintenance_health',{p_organization_id:organizationId})
  if(error)fail(error,'Could not load background job health')
  return (data||[]).map((item)=>({jobKey:item.job_key,lastSuccessfulRunAt:item.last_successful_run_at,lastRunAt:item.last_run_at,lastStatus:item.last_status,lastError:item.last_error,staleAfterHours:item.stale_after_hours,isStale:item.is_stale}))
}
export async function updateCandidateRetentionMonths(organizationId:string,months:number){if(!Number.isInteger(months)||months<1||months>120)throw new AppError('Choose a retention period from 1 to 120 months.','invalid_retention_period');const {error}=await supabase.from('organization_settings').update({candidate_retention_months:months,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error)fail(error,'Could not update the retention policy')}
export async function updateOrganizationAccent(organizationId:string,primaryColor:string){if(!/^#[0-9a-f]{6}$/i.test(primaryColor))throw new AppError('Choose a valid six-digit hex color.','invalid_accent');const {error}=await supabase.from('organization_settings').update({primary_color:primaryColor,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error)fail(error,'Could not update organization branding')}
export async function uploadOrganizationLogo(organizationId:string,file:File,previousPath?:string|null){const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.type))throw new AppError('Use a PNG, JPG, or WebP logo.','invalid_logo_type');if(file.size>2*1024*1024)throw new AppError('Logo files are limited to 2 MB.','logo_too_large');const extension=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const storagePath=`${organizationId}/logo-${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from('organization-assets').upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(upload.error)fail(upload.error,'Could not upload organization logo');const {error}=await supabase.from('organization_settings').update({logo_path:storagePath,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error){await supabase.storage.from('organization-assets').remove([storagePath]);fail(error,'Could not save organization logo')}if(previousPath&&previousPath!==storagePath)await supabase.storage.from('organization-assets').remove([previousPath]);return storagePath}
/* The mandatory client profile template prints a banner across the footer of every page. It is a
 * distinct asset from the navigation logo -- different artwork, different aspect ratio -- but it is
 * stored inside the settings blob rather than its own column, so it needs no schema change. Both
 * writes read-modify-write that blob; there is one settings row per organization and only an owner
 * can reach this screen, so the race is not worth an RPC. */
async function patchOrganizationSettings(organizationId:string,change:Record<string,unknown>){
  const current=await supabase.from('organization_settings').select('settings').eq('organization_id',organizationId).maybeSingle()
  if(current.error)fail(current.error,'Could not read organization settings')
  const merged={...(current.data?.settings as Record<string,unknown>||{}),...change}
  const {error}=await supabase.from('organization_settings').update({settings:merged as unknown as Json,updated_at:new Date().toISOString()}).eq('organization_id',organizationId)
  if(error)fail(error,'Could not save organization settings')
}

/* Both were hardcoded in the candidate page: a 62 country code and an English opening line, in a
 * product sold to agencies that are not all Indonesian and do not all write to candidates in English.
 * Validated here rather than only in the form, because this blob is also the thing a future import or
 * script would write to. */
export async function updateWhatsAppSettings(organizationId:string,input:{countryCode:string;template:string}){
  const code=input.countryCode.replace(/\D/g,'')
  if(!/^\d{1,4}$/.test(code))throw new AppError('Country code must be 1–4 digits, without a plus sign.','invalid_country_code')
  await patchOrganizationSettings(organizationId,{whatsapp_country_code:code,whatsapp_template:input.template.trim()||null})
}
export async function uploadOrganizationProfileBanner(organizationId:string,file:File,previousPath?:string|null){const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.type))throw new AppError('Use a PNG, JPG, or WebP banner.','invalid_banner_type');if(file.size>2*1024*1024)throw new AppError('Banner files are limited to 2 MB.','banner_too_large');const extension=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const storagePath=`${organizationId}/profile-banner-${crypto.randomUUID()}.${extension}`;const upload=await supabase.storage.from('organization-assets').upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(upload.error)fail(upload.error,'Could not upload profile banner');try{await patchOrganizationSettings(organizationId,{profile_footer_banner_path:storagePath})}catch(error){await supabase.storage.from('organization-assets').remove([storagePath]);throw error}if(previousPath&&previousPath!==storagePath)await supabase.storage.from('organization-assets').remove([previousPath]);return storagePath}
export async function removeOrganizationProfileBanner(organizationId:string,bannerPath:string){await patchOrganizationSettings(organizationId,{profile_footer_banner_path:null});const removed=await supabase.storage.from('organization-assets').remove([bannerPath]);if(removed.error)fail(removed.error,'Banner setting was cleared, but the old file could not be removed')}

export async function removeOrganizationLogo(organizationId:string,logoPath:string){const {error}=await supabase.from('organization_settings').update({logo_path:null,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);if(error)fail(error,'Could not remove organization logo');const removed=await supabase.storage.from('organization-assets').remove([logoPath]);if(removed.error)fail(removed.error,'Logo setting was cleared, but the old file could not be removed')}

export async function listCalendarConnections(organizationId:string){const {data,error}=await supabase.from('google_calendar_connections').select('id,organization_id,member_id,google_email,calendar_id,status,connected_at,last_synced_at,last_error').eq('organization_id',organizationId);if(error)fail(error,'Could not load Calendar connections');return rows(data,calendarConnectionSchema,'Calendar connection rows did not match the expected shape') as CalendarConnection[]}
export function startCalendarConnection(organizationId:string,returnPath:string){return invoke<{authorizationUrl:string}>('calendar-auth-start',{organizationId,returnPath})}
export function disconnectCalendar(organizationId:string){return invoke<{status:string}>('calendar-disconnect',{organizationId})}
export function syncInterviewCalendar(organizationId:string,interviewId:string){return invoke<{status:string;eventId?:string}>('calendar-sync',{organizationId,interviewId,action:'sync'})}
export function cancelInterviewWithNotifications(organizationId:string,interviewId:string){return invoke<{status:'cancelled';calendarStatus:'cancelled'|'not_connected'|'not_required'|'failed';notificationStatus:'sent'|'pending'|'partial'|'failed'|'not_required';recipientCount:number;failedRecipientCount:number}>('calendar-sync',{organizationId,interviewId,action:'cancel'})}
export async function listSubmissionCandidateDocuments(organizationId:string,jobId:string){const {data,error}=await supabase.from('job_candidates').select('id,candidate_id,candidates(id,full_name,current_company,current_position,status,availability,notice_period_days,candidate_private_details(consent_status,expected_salary,salary_currency),document_links(documents(id,file_name,original_filename,mime_type,storage_path,size_bytes,created_at,deleted_at)))').eq('organization_id',organizationId).eq('job_id',jobId);if(error)fail(error,'Could not load submission candidates');return rows(data,submissionCandidateDocumentRowSchema,'Submission candidate document rows did not match the expected shape')}
export function sendClientSubmission(input:{organizationId:string;jobId:string;requestKey:string;contactId?:string;title:string;message?:string;recipientName?:string;recipientEmail:string;expiryDays:number;items:Array<Record<string,unknown>>}){return invoke<{packageId:string;deliveryId:string;expiresAt:string;deliveryStatus:string;errorMessage?:string;previewUrl?:string}>('send-submission',input)}
export function retryClientSubmission(organizationId:string,deliveryId:string){return invoke<{packageId:string;deliveryId:string;expiresAt:string;deliveryStatus:string;errorMessage?:string}>('send-submission',{action:'retry',organizationId,deliveryId})}
export async function revokeSubmissionLink(linkId:string){const {error}=await supabase.rpc('revoke_submission_link',{p_link_id:linkId});if(error)fail(error,'Could not revoke submission link')}
/* Proxies Google Places Autocomplete through location-autocomplete so the API key stays server-side.
 * `sessionToken` must be the same value across every keystroke of one search and a fresh one after a
 * selection or an abandoned field -- LocationField owns that lifecycle, this just forwards it. */
export function searchLocations(input:string,sessionToken:string){return invoke<{suggestions:Array<{id:string;label:string}>}>('location-autocomplete',{input,sessionToken})}

export async function getCandidateDetail(organizationId:string,candidateId:string){const {data,error}=await supabase.from('candidates').select('*,candidate_private_details(*),candidate_employment(*),candidate_education(*),candidate_languages(*),candidate_skills(skill_id,proficiency,years_experience,skills(id,name)),candidate_tags(tag_id,tags(id,name,color))').eq('organization_id',organizationId).eq('id',candidateId).single();if(error)fail(error,'Could not load candidate');return row(data,candidateDetailSchema,'Candidate detail did not match the expected shape') as CandidateDetail}
export async function updateCandidateProfile(organizationId:string,candidateId:string,values:Record<string,unknown>,privateValues:Record<string,unknown>){const {error}=await supabase.rpc('update_candidate_profile',{p_organization_id:organizationId,p_candidate_id:candidateId,p_candidate:values as Json,p_private:privateValues as Json});if(error)fail(error,'Could not update candidate')}
export async function updateCandidateWithProfile(organizationId:string,candidateId:string,values:Record<string,unknown>,privateValues:Record<string,unknown>,profile:CandidateProfileLists){const {error}=await supabase.rpc('update_candidate_with_profile',{p_organization_id:organizationId,p_candidate_id:candidateId,p_candidate:values as Json,p_private:privateValues as Json,p_employment:(profile.employment||[]) as unknown as Json,p_education:(profile.education||[]) as unknown as Json,p_languages:(profile.languages||[]) as unknown as Json,p_skills:(profile.skills||[]) as unknown as Json});if(error)fail(error,'Could not update candidate')}
export async function replaceCandidateProfileSection(organizationId:string,candidateId:string,section:'employment'|'education'|'languages'|'skills',items:readonly unknown[]){const {error}=await supabase.rpc('replace_candidate_profile_section',{p_organization_id:organizationId,p_candidate_id:candidateId,p_section:section,p_items:items as unknown as Json});if(error)fail(error,`Could not save candidate ${section}`)}
export async function setCandidateArchived(organizationId:string,candidateId:string,archived:boolean){const {error}=await supabase.from('candidates').update({deleted_at:archived?new Date().toISOString():null,status:archived?'archived':'active'}).eq('organization_id',organizationId).eq('id',candidateId);if(error)fail(error,archived?'Could not archive candidate':'Could not restore candidate')}
export async function setCandidateLegalHold(organizationId:string,candidateId:string,legalHold:boolean,reason:string){const {error}=await supabase.rpc('set_candidate_legal_hold',{p_organization_id:organizationId,p_candidate_id:candidateId,p_legal_hold:legalHold,p_reason:reason});if(error)fail(error,'Could not change the candidate legal hold')}
export async function mergeCandidates(organizationId:string,keptCandidateId:string,mergedCandidateId:string,reason:string){const {data,error}=await supabase.rpc('merge_candidates',{p_organization_id:organizationId,p_kept_candidate_id:keptCandidateId,p_merged_candidate_id:mergedCandidateId,p_reason:reason});if(error)fail(error,error.message.includes('merge_conflicting_job_assignments')?'These candidates are both assigned to the same vacancy. Resolve that pipeline conflict before merging.':'Could not merge candidates');return data as string}
export async function listCandidateDocuments(organizationId:string,candidateId:string){const {data,error}=await supabase.from('document_links').select('documents!inner(id,file_name,original_filename,mime_type,storage_path,size_bytes,document_type,created_at,deleted_at)').eq('organization_id',organizationId).eq('candidate_id',candidateId);if(error)fail(error,'Could not load documents');const validated=rows(data,documentLinkRowSchema,'Document link rows did not match the expected shape');const documents=validated.flatMap((item)=>{const value=item.documents as CandidateDocument|CandidateDocument[];return Array.isArray(value)?value:[value]}).filter((document)=>document&&!('deleted_at' in document&&document.deleted_at));return Promise.all(documents.map(async(document)=>{const {data:signed}=await supabase.storage.from('candidate-documents').createSignedUrl(document.storage_path,300);return {...document,signedUrl:signed?.signedUrl}}))}
export async function uploadCandidateDocument(organizationId:string,candidateId:string,userId:string,file:File){if(file.size>25*1024*1024)throw new AppError('Documents are limited to 25 MB.','file_too_large');const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/${candidateId}/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:file.type||'application/octet-stream',upsert:false});if(upload.error)fail(upload.error,'Could not upload document');const {data:document,error}=await supabase.from('documents').insert({organization_id:organizationId,file_name:safeName,original_filename:file.name,storage_path:storagePath,mime_type:file.type||'application/octet-stream',size_bytes:file.size,document_type:'resume',uploaded_by:userId}).select('id').single();if(error){await supabase.storage.from('candidate-documents').remove([storagePath]);fail(error,'Could not register document')}const link=await supabase.from('document_links').insert({organization_id:organizationId,document_id:document.id,candidate_id:candidateId});if(link.error){await Promise.all([supabase.from('documents').delete().eq('id',document.id),supabase.storage.from('candidate-documents').remove([storagePath])]);fail(link.error,'Could not link document')}return document.id as string}
export async function uploadCandidateProfileDocument(organizationId:string,candidateId:string,userId:string,file:File){const allowed=['application/vnd.openxmlformats-officedocument.wordprocessingml.document'];if(!allowed.includes(file.type))throw new AppError('Candidate profiles must be DOCX.','invalid_profile_document');const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/${candidateId}/profiles/${crypto.randomUUID()}-${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:file.type,upsert:false});if(upload.error)fail(upload.error,'Could not upload generated profile');const {data:document,error}=await supabase.from('documents').insert({organization_id:organizationId,file_name:safeName,original_filename:file.name,storage_path:storagePath,mime_type:file.type,size_bytes:file.size,document_type:'candidate_profile',uploaded_by:userId}).select('id').single();if(error){await supabase.storage.from('candidate-documents').remove([storagePath]);fail(error,'Could not register generated profile')}const link=await supabase.from('document_links').insert({organization_id:organizationId,document_id:document.id,candidate_id:candidateId});if(link.error){await Promise.all([supabase.from('documents').delete().eq('id',document.id),supabase.storage.from('candidate-documents').remove([storagePath])]);fail(link.error,'Could not link generated profile')}return {id:document.id as string,storagePath}}
export async function discardCandidateProfileDocument(organizationId:string,document:{id:string;storagePath:string}){await Promise.all([supabase.from('documents').delete().eq('organization_id',organizationId).eq('id',document.id),supabase.storage.from('candidate-documents').remove([document.storagePath])])}
export async function deleteCandidateDocument(organizationId:string,documentId:string,storagePath:string){const {error}=await supabase.from('documents').update({deleted_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',documentId);if(error)fail(error,'Could not archive document');await supabase.storage.from('candidate-documents').remove([storagePath])}
const pdfMime='application/pdf';const docxMime='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
function cvMime(file:File){if(file.type===pdfMime||file.type===docxMime)return file.type;const name=file.name.toLowerCase();if(name.endsWith('.pdf'))return pdfMime;if(name.endsWith('.docx'))return docxMime;throw new AppError('Upload a PDF or DOCX CV.','unsupported_cv_type')}
export async function startCandidateCvParse(organizationId:string,userId:string,file:File,targetCandidateId?:string|null){const mimeType=cvMime(file);const max=mimeType===docxMime?10*1024*1024:25*1024*1024;if(file.size<1||file.size>max)throw new AppError(mimeType===docxMime?'DOCX CVs are limited to 10 MB.':'PDF CVs are limited to 25 MB.','cv_too_large');const parseId=crypto.randomUUID();const safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const storagePath=`${organizationId}/cv-drafts/${userId}/${parseId}/${safeName}`;const upload=await supabase.storage.from('candidate-documents').upload(storagePath,file,{contentType:mimeType,upsert:false});if(upload.error)fail(upload.error,'Could not upload CV');try{await invoke<{parseId:string}>('parse-candidate-cv',{action:'start',organizationId,parseId,storagePath,originalFilename:file.name,mimeType,targetCandidateId:targetCandidateId||null});return parseId}catch(error){await supabase.storage.from('candidate-documents').remove([storagePath]);throw error}}
export async function getCandidateCvParse(organizationId:string,parseId:string){const result=await invoke<CvParseResult>('parse-candidate-cv',{action:'status',organizationId,parseId});if(result.extraction)result.extraction=candidateCvExtractionSchema.parse(result.extraction);return result}
export async function retryCandidateCvParse(organizationId:string,parseId:string){return invoke<{parseId:string}>('parse-candidate-cv',{action:'retry',organizationId,parseId})}
export async function cancelCandidateCvParse(organizationId:string,parseId:string){return invoke<{parseId:string}>('parse-candidate-cv',{action:'cancel',organizationId,parseId})}
export async function acceptCandidateCvParse(organizationId:string,parseId:string,extraction:CandidateCvExtraction,targetCandidateId?:string|null){const payload=candidateCvExtractionSchema.parse(extraction);const {data,error}=await supabase.rpc('accept_candidate_cv_parse',{p_organization_id:organizationId,p_parse_id:parseId,p_payload:payload as unknown as Json,p_target_candidate_id:targetCandidateId||undefined});if(error)fail(error,error.message.includes('duplicate_candidate')?'A candidate with this email already exists.':'Could not save the parsed CV');return data as string}
export async function listCandidateJobs(organizationId:string,candidateId:string):Promise<CandidateProfileJob[]>{const {data,error}=await supabase.from('job_candidates').select('jobs!inner(id,title,deleted_at,companies(name))').eq('organization_id',organizationId).eq('candidate_id',candidateId);if(error)fail(error,'Could not load linked vacancies');const validated=rows(data,candidateJobLinkRowSchema,'Candidate job link rows did not match the expected shape');return validated.map((item)=>item.jobs).filter((job)=>job&&!job.deleted_at).map((job)=>({id:job.id,title:job.title,company_name:job.companies?.name||null}))}
export async function hasOrganizationPermission(organizationId:string,permission:string){const {data,error}=await supabase.rpc('has_permission',{p_organization_id:organizationId,p_permission:permission});if(error)fail(error,'Could not check workspace permissions');return Boolean(data)}
/* Replaces the 15-parallel-has_permission fan-out that used to back useWorkspaceCapabilities. The
 * RPC always returns exactly one row -- an all-false row for a non-member -- so the empty fallback
 * here is for a genuinely unreachable response shape, not for the ordinary "no access" case. */
export async function getWorkspaceCapabilities(organizationId:string):Promise<WorkspaceCapabilities>{
  const {data,error}=await supabase.rpc('get_my_workspace_capabilities',{p_organization_id:organizationId})
  if(error)fail(error,'Could not load workspace permissions')
  const capabilities=data?.[0]
  if(!capabilities)return {roleKeys:[],canWriteCandidates:false,canWriteClients:false,canWriteJobs:false,canMovePipeline:false,canSubmit:false,canManageInterviews:false,canManageOffers:false,canManagePlacements:false,canManageCommercialTerms:false,canViewTeamReports:false,canManageFinance:false,canImport:false,canManageOrganization:false,canManageWorkspace:false,canManageTemplates:false,canViewAdmin:false,readOnly:true}
  return {
    roleKeys:capabilities.role_keys||[],
    canWriteCandidates:capabilities.can_write_candidates,canWriteClients:capabilities.can_write_clients,canWriteJobs:capabilities.can_write_jobs,
    canMovePipeline:capabilities.can_move_pipeline,canSubmit:capabilities.can_submit,canManageInterviews:capabilities.can_manage_interviews,
    canManageOffers:capabilities.can_manage_offers,canManagePlacements:capabilities.can_manage_placements,canManageCommercialTerms:capabilities.can_manage_commercial_terms,
    canViewTeamReports:capabilities.can_view_team_reports,canManageFinance:capabilities.can_manage_finance,canImport:capabilities.can_import,
    canManageOrganization:capabilities.can_manage_organization,canManageWorkspace:capabilities.can_manage_workspace,canManageTemplates:capabilities.can_manage_templates,
    canViewAdmin:capabilities.can_view_admin,readOnly:capabilities.read_only,
  }
}
export async function listCandidateProfileTemplates(organizationId:string):Promise<CandidateProfileTemplate[]>{const {data,error}=await supabase.from('templates').select('id,name,configuration,version,is_default,created_at,updated_at').eq('organization_id',organizationId).eq('template_type','candidate_profile').is('deleted_at',null).order('is_default',{ascending:false}).order('name');if(error)fail(error,'Could not load candidate profile templates');return (data||[]).map((item)=>({...item,configuration:candidateProfileTemplateConfigSchema.parse(item.configuration)}))}
// The generated type requires p_template_id:string, but the RPC's own SQL (create_candidate_profile
// template) declares it as a bare `uuid` with no default and explicitly branches on `is null` to tell
// insert from update -- Postgres function parameters have no NOT NULL syntax at all, so this is
// genuinely nullable at the database level; the type generator just doesn't infer that for a
// no-default parameter. `null` here is required, not a workaround -- it's what tells the RPC to
// create a new template rather than update an existing one.
export async function saveCandidateProfileTemplate(organizationId:string,input:{id?:string;name:string;configuration:unknown;isDefault:boolean}){const configuration=candidateProfileTemplateConfigSchema.parse(input.configuration);const {data,error}=await supabase.rpc('save_candidate_profile_template',{p_organization_id:organizationId,p_template_id:(input.id||null) as string,p_name:input.name,p_configuration:configuration as unknown as Json,p_is_default:input.isDefault});if(error)fail(error,'Could not save candidate profile template');return data as string}
export async function archiveCandidateProfileTemplate(organizationId:string,templateId:string){const {error}=await supabase.rpc('archive_candidate_profile_template',{p_organization_id:organizationId,p_template_id:templateId});if(error)fail(error,error.message.includes('last_template_required')?'Keep at least one candidate profile template.':'Could not archive candidate profile template')}
export async function generateCandidateProfile(input:{organizationId:string;candidateId:string;jobId:string;templateId:string;anonymize:boolean}):Promise<CandidateProfileGeneration>{const result=await invoke<CandidateProfileGeneration>('generate-candidate-profile',input);return {...result,draft:candidateProfileDraftSchema.parse(result.draft),evaluation:{...result.evaluation,evidence:candidateProfileDraftSchema.shape.requirement_evidence.parse(result.evaluation.evidence)}}}
export async function listCandidateProfileVersions(organizationId:string,candidateId:string):Promise<CandidateProfileVersion[]>{const {data,error}=await supabase.from('candidate_profile_versions').select('id,version,status,candidate_id,job_id,template_id,template_version,generated_content,reviewed_content,input_versions,anonymized,docx_document_id,pdf_document_id,created_at,finalized_at,jobs(title,updated_at),templates(name,version),candidates!candidate_id(updated_at)').eq('organization_id',organizationId).eq('candidate_id',candidateId).order('created_at',{ascending:false});if(error)fail(error,'Could not load candidate profile versions');const validated=rows(data,candidateProfileVersionRowSchema,'Candidate profile version rows did not match the expected shape');return validated.map((item)=>{const {jobs:job,templates:template,candidates:candidate,input_versions:inputVersions,...rest}=item;return {...rest,generated_content:candidateProfileDraftSchema.parse(item.generated_content),reviewed_content:item.reviewed_content?candidateProfileDraftSchema.parse(item.reviewed_content):null,input_versions:inputVersions,job_title:job.title,template_name:template.name,stale:hasStaleProfileInputs(inputVersions,{candidateUpdatedAt:candidate.updated_at,jobUpdatedAt:job.updated_at,templateVersion:template.version})}}) as CandidateProfileVersion[]}
/* DOCX is the only client-facing output; the mandatory client template is a Word file consultants
 * still complete by hand. p_pdf_document_id is retained on the RPC for signature stability and is
 * ignored, so it is always passed null. */
export async function finalizeCandidateProfile(input:{organizationId:string;profileVersionId:string;reviewedContent:unknown;anonymized:boolean;docxDocumentId:string;editedFieldCount:number}){const reviewed=candidateProfileDraftSchema.parse(input.reviewedContent);
  // Same class of gap as p_fee_percentage/p_fixed_fee below: supabase gen types infers a no-default
  // plpgsql parameter as its bare declared type (string), not string | null, because it has no way to
  // introspect a function parameter's true nullability the way it can a column's NOT NULL. Passing
  // null here is correct -- see the type's own comment -- the generated signature is just incomplete.
  const {data,error}=await supabase.rpc('finalize_candidate_profile',{p_organization_id:input.organizationId,p_profile_version_id:input.profileVersionId,p_reviewed_content:reviewed as unknown as Json,p_anonymized:input.anonymized,p_docx_document_id:input.docxDocumentId,p_pdf_document_id:null as unknown as string,p_edited_field_count:input.editedFieldCount});if(error)fail(error,'Could not finalize candidate profile');return data as string}
export async function recordCandidateProfileExportFailure(organizationId:string,profileVersionId:string,reason:string){const {error}=await supabase.rpc('record_candidate_profile_export_failure',{p_organization_id:organizationId,p_profile_version_id:profileVersionId,p_reason:reason.slice(0,500)});if(error)console.error('Could not record candidate profile export failure',error)}
// started_on_precision/ended_on_precision are optional so the plain one-field-at-a-time add form
// (which never captured precision) keeps its old "day if a date was entered" default, while callers
// that do collect a precision (the shared list editors) can pass the consultant's actual choice
// through instead of it being silently downgraded to 'day'.
export async function addCandidateEmployment(organizationId:string,candidateId:string,values:{company_name:string;title:string;location?:string|null;started_on?:string|null;ended_on?:string|null;is_current:boolean;summary?:string|null;started_on_precision?:string|null;ended_on_precision?:string|null}){const {error}=await supabase.from('candidate_employment').insert({organization_id:organizationId,candidate_id:candidateId,company_name:values.company_name,title:values.title,location:values.location||null,is_current:values.is_current,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on_precision??(values.started_on?'day':null),ended_on_precision:values.ended_on_precision??(values.ended_on?'day':null),summary:values.summary||null});if(error)fail(error,'Could not add employment')}
export async function addCandidateEducation(organizationId:string,candidateId:string,values:{institution:string;degree?:string|null;field_of_study?:string|null;started_on?:string|null;ended_on?:string|null;started_on_precision?:string|null;ended_on_precision?:string|null}){const {error}=await supabase.from('candidate_education').insert({organization_id:organizationId,candidate_id:candidateId,institution:values.institution,degree:values.degree||null,field_of_study:values.field_of_study||null,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on_precision??(values.started_on?'day':null),ended_on_precision:values.ended_on_precision??(values.ended_on?'day':null)});if(error)fail(error,'Could not add education')}
export async function addCandidateLanguage(organizationId:string,candidateId:string,language:string,proficiency:string){const {error}=await supabase.from('candidate_languages').insert({organization_id:organizationId,candidate_id:candidateId,language:language.trim(),proficiency:proficiency.trim()||null});if(error)fail(error,'Could not add language')}
// Shared by add and update: skills are resolved through the org's `skills` table by
// normalized_name, so renaming a skill on a candidate means finding-or-creating the *target*
// skill_id, not editing the name in place.
async function resolveSkillId(organizationId:string,name:string){const normalized=name.trim().toLowerCase().replace(/\s+/g,' ');const existing=await supabase.from('skills').select('id').eq('organization_id',organizationId).eq('normalized_name',normalized).maybeSingle();if(existing.error)fail(existing.error,'Could not find skill');if(existing.data)return existing.data.id as string;const created=await supabase.from('skills').insert({organization_id:organizationId,name:name.trim(),normalized_name:normalized}).select('id').single();if(created.error)fail(created.error,'Could not create skill');return created.data.id as string}
export async function addCandidateSkill(organizationId:string,candidateId:string,name:string,proficiency:string,yearsExperience?:number){const skillId=await resolveSkillId(organizationId,name);const {error}=await supabase.from('candidate_skills').upsert({organization_id:organizationId,candidate_id:candidateId,skill_id:skillId,proficiency:proficiency.trim()||null,years_experience:yearsExperience??null});if(error)fail(error,'Could not add skill')}
export async function addCandidateTag(organizationId:string,candidateId:string,name:string){const normalized=name.trim();let tagId:string;const existing=await supabase.from('tags').select('id').eq('organization_id',organizationId).ilike('name',normalized).maybeSingle();if(existing.error)fail(existing.error,'Could not find tag');if(existing.data)tagId=existing.data.id;else{const created=await supabase.from('tags').insert({organization_id:organizationId,name:normalized}).select('id').single();if(created.error)fail(created.error,'Could not create tag');tagId=created.data.id}const {error}=await supabase.from('candidate_tags').upsert({organization_id:organizationId,candidate_id:candidateId,tag_id:tagId});if(error)fail(error,'Could not add tag')}
export async function removeCandidateSkill(organizationId:string,candidateId:string,skillId:string){const {error}=await supabase.from('candidate_skills').delete().eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('skill_id',skillId);if(error)fail(error,'Could not remove skill')}
export async function removeCandidateTag(organizationId:string,candidateId:string,tagId:string){const {error}=await supabase.from('candidate_tags').delete().eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('tag_id',tagId);if(error)fail(error,'Could not remove tag')}
export async function deleteCandidateProfileItem(table:'candidate_employment'|'candidate_education'|'candidate_languages',organizationId:string,id:string){const {error}=await supabase.from(table).delete().eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not remove profile item')}

// The four functions below back Phase 5's in-place panel editing on the candidate detail page --
// they replace the "add one entry at a time, never edit an existing one" flow that AddProfileItem
// used to be the only way to touch these tables.
export async function updateCandidateEmployment(organizationId:string,id:string,values:{company_name:string;title:string;location?:string|null;started_on?:string|null;ended_on?:string|null;is_current:boolean;summary?:string|null;started_on_precision?:string|null;ended_on_precision?:string|null}){const {error}=await supabase.from('candidate_employment').update({company_name:values.company_name,title:values.title,location:values.location||null,is_current:values.is_current,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on_precision??(values.started_on?'day':null),ended_on_precision:values.ended_on_precision??(values.ended_on?'day':null),summary:values.summary||null}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update employment')}
export async function updateCandidateEducation(organizationId:string,id:string,values:{institution:string;degree?:string|null;field_of_study?:string|null;started_on?:string|null;ended_on?:string|null;started_on_precision?:string|null;ended_on_precision?:string|null}){const {error}=await supabase.from('candidate_education').update({institution:values.institution,degree:values.degree||null,field_of_study:values.field_of_study||null,started_on:values.started_on||null,ended_on:values.ended_on||null,started_on_precision:values.started_on_precision??(values.started_on?'day':null),ended_on_precision:values.ended_on_precision??(values.ended_on?'day':null)}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update education')}
export async function updateCandidateLanguage(organizationId:string,id:string,language:string,proficiency:string){const {error}=await supabase.from('candidate_languages').update({language:language.trim(),proficiency:proficiency.trim()||null}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update language')}
// Renaming to a name that resolves to the same skill_id is a plain update; renaming to a different
// skill is a move -- drop the old pairing and upsert the new one, mirroring addCandidateSkill.
export async function updateCandidateSkill(organizationId:string,candidateId:string,previousSkillId:string,name:string,proficiency:string,yearsExperience?:number){const skillId=await resolveSkillId(organizationId,name);if(skillId===previousSkillId){const {error}=await supabase.from('candidate_skills').update({proficiency:proficiency.trim()||null,years_experience:yearsExperience??null}).eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('skill_id',previousSkillId);if(error)fail(error,'Could not update skill');return}const removed=await supabase.from('candidate_skills').delete().eq('organization_id',organizationId).eq('candidate_id',candidateId).eq('skill_id',previousSkillId);if(removed.error)fail(removed.error,'Could not update skill');const {error}=await supabase.from('candidate_skills').upsert({organization_id:organizationId,candidate_id:candidateId,skill_id:skillId,proficiency:proficiency.trim()||null,years_experience:yearsExperience??null});if(error)fail(error,'Could not update skill')}

export async function getCompanyDetail(organizationId:string,id:string){const {data,error}=await supabase.from('companies').select('*,contacts(id,full_name,position,email,phone,contact_status),jobs(id,title,status,priority,updated_at)').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load company');return data as Record<string,unknown>}
export async function updateCompany(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('companies').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update company')}
export async function listCompanyCommercialTerms(organizationId:string,companyId:string){const {data,error}=await supabase.from('commercial_terms').select('id,fee_type,fee_percentage,fixed_fee,currency,guarantee_days,effective_from,effective_to,status,updated_at,payment_terms_days,tax_treatment,replacement_terms,agreement_document_url,approval_status,notes').eq('organization_id',organizationId).eq('company_id',companyId).order('effective_from',{ascending:false}).limit(10);if(error)fail(error,'Could not load commercial terms');return data??[]}
export async function setCompanyDefaultFee(organizationId:string,companyId:string,input:{feeType:'percentage'|'fixed'|'retained';feePercentage?:number;fixedFee?:number;currency:string;guaranteeDays:number;paymentTermsDays?:number;taxTreatment?:string;replacementTerms?:string;agreementDocumentUrl?:string;approvalStatus?:'draft'|'pending_approval'|'approved'|'rejected';notes?:string}){const {data,error}=await supabase.rpc('set_company_default_fee',{p_organization_id:organizationId,p_company_id:companyId,p_fee_type:input.feeType,// The generated type marks these `number`, not `number | null`: supabase gen types has no way to
      // introspect nullability of a plpgsql parameter (unlike a table column's NOT NULL), so it falls back
      // to the bare declared type. The function body itself branches on `is null` for whichever of the two
      // doesn't apply to the chosen fee_type, so passing null here is the correct runtime call.
      p_fee_percentage:(input.feePercentage??null) as number,p_fixed_fee:(input.fixedFee??null) as number,p_currency:input.currency,p_guarantee_days:input.guaranteeDays,p_payment_terms_days:input.paymentTermsDays??undefined,p_tax_treatment:input.taxTreatment||undefined,p_replacement_terms:input.replacementTerms||undefined,p_agreement_document_url:input.agreementDocumentUrl||undefined,p_approval_status:input.approvalStatus||'approved',p_notes:input.notes||undefined});if(error)fail(error,'Could not save account fee defaults');return data as string}
export async function listCompanyPipeline(organizationId:string){const {data,error}=await supabase.rpc('list_company_pipeline',{p_organization_id:organizationId});if(error)fail(error,'Could not load the client pipeline');return rows(data,companyPipelineRowSchema,'Company pipeline rows did not match the expected shape') as CompanyPipelineRow[]}
export async function setCompanyBdStage(organizationId:string,companyId:string,stage:string,note?:string){const {error}=await supabase.rpc('set_company_bd_stage',{p_organization_id:organizationId,p_company_id:companyId,p_stage:stage,p_note:note||undefined});if(error)fail(error,error.message.includes('invalid_bd_stage')?'That business development stage is not recognised.':'Could not move this account')}

export async function listSavedViews(organizationId:string,resource:SavedViewResource){const {data,error}=await supabase.from('saved_views').select('id,organization_id,owner_member_id,resource,name,filters,columns,is_shared,is_default,updated_at').eq('organization_id',organizationId).eq('resource',resource).order('name');if(error)fail(error,'Could not load saved views');return rows(data,savedViewSchema,'Saved view rows did not match the expected shape') as SavedView[]}
export async function saveView(organizationId:string,memberId:string,resource:SavedViewResource,input:{id?:string;name:string;filters:Record<string,unknown>;columns:string[];isShared:boolean;isDefault:boolean}){
  const row={organization_id:organizationId,owner_member_id:memberId,resource,name:input.name.trim(),filters:input.filters as Json,columns:input.columns as unknown as Json,is_shared:input.isShared,is_default:input.isDefault,updated_at:new Date().toISOString()}
  // A member may only hold one default per resource, so promoting one demotes the rest first. Doing
  // this before the write means a failed write cannot leave the member with no default at all.
  if(input.isDefault){const {error}=await supabase.from('saved_views').update({is_default:false}).eq('organization_id',organizationId).eq('owner_member_id',memberId).eq('resource',resource);if(error)fail(error,'Could not update the default view')}
  const result=input.id
    ?await supabase.from('saved_views').update(row).eq('id',input.id).select('id').single()
    :await supabase.from('saved_views').insert(row).select('id').single()
  if(result.error)fail(result.error,result.error.code==='23505'?'You already have a view with that name.':'Could not save this view')
  return result.data.id as string
}
export async function deleteSavedView(id:string){const {error}=await supabase.from('saved_views').delete().eq('id',id);if(error)fail(error,'Could not delete this view')}

export async function getContactDetail(organizationId:string,id:string){const {data,error}=await supabase.from('contacts').select('*,companies(id,name),job_contacts(jobs(id,title,status))').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load contact');return data as Record<string,unknown>}
export async function updateContact(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('contacts').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update contact')}
export async function getJobDetail(organizationId:string,id:string){const {data,error}=await supabase.from('jobs').select('*,companies(id,name),job_contacts(contacts(id,full_name,email)),job_team_members(organization_members(id,profiles:user_id(full_name,email)))').eq('organization_id',organizationId).eq('id',id).single();if(error)fail(error,'Could not load vacancy');return data as Record<string,unknown>}
export async function updateJob(organizationId:string,id:string,values:Record<string,unknown>){const {error}=await supabase.from('jobs').update({...values,updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not update vacancy')}
export async function updateJobAssociations(organizationId:string,jobId:string,contactIds:string[],memberIds:string[]){const [contactsDelete,teamDelete]=await Promise.all([supabase.from('job_contacts').delete().eq('organization_id',organizationId).eq('job_id',jobId),supabase.from('job_team_members').delete().eq('organization_id',organizationId).eq('job_id',jobId)]);if(contactsDelete.error)fail(contactsDelete.error,'Could not update vacancy contacts');if(teamDelete.error)fail(teamDelete.error,'Could not update vacancy team');const results=await Promise.all([contactIds.length?supabase.from('job_contacts').insert(contactIds.map((contactId,index)=>({organization_id:organizationId,job_id:jobId,contact_id:contactId,is_primary:index===0}))):Promise.resolve({error:null}),memberIds.length?supabase.from('job_team_members').insert(memberIds.map((memberId)=>({organization_id:organizationId,job_id:jobId,member_id:memberId,team_role:'consultant'}))):Promise.resolve({error:null})]);if(results[0].error)fail(results[0].error,'Could not save vacancy contacts');if(results[1].error)fail(results[1].error,'Could not save vacancy team')}
export async function setRecordArchived(table:'companies'|'contacts'|'jobs',organizationId:string,id:string,archived:boolean){const deletedAt=archived?new Date().toISOString():null;if(table==='jobs'){const {error}=await supabase.from('jobs').update({deleted_at:deletedAt,status:archived?'cancelled':'open'}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status');return}if(table==='companies'){const {error}=await supabase.from('companies').update({deleted_at:deletedAt}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status');return}const {error}=await supabase.from('contacts').update({deleted_at:deletedAt}).eq('organization_id',organizationId).eq('id',id);if(error)fail(error,'Could not change archive status')}

export async function listImportBatches(organizationId:string){const {data,error}=await supabase.from('imports').select('id,entity_type,file_name,source_format,status,total_rows,valid_rows,failed_rows,validation_summary,reconciliation_summary,created_at,completed_at,rolled_back_at').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)fail(error,'Could not load imports');return rows(data,importBatchSchema,'Import batch rows did not match the expected shape') as ImportBatch[]}
export async function listImportErrors(organizationId:string,importId:string){const {data,error}=await supabase.from('import_rows').select('row_number,source_data,errors').eq('organization_id',organizationId).eq('import_id',importId).eq('status','invalid').order('row_number');if(error)fail(error,'Could not load import errors');return data||[]}
export function stageImport(organizationId:string,entityType:string,fileName:string,sourceFormat:'csv'|'xlsx',rows:Array<Record<string,unknown>>){return invoke<{importId:string;totalRows:number;validRows:number;failedRows:number;status:string}>('execute-import',{organizationId,action:'stage',entityType,fileName,sourceFormat,rows})}
export function commitImport(organizationId:string,importId:string){return invoke<{status:string;committedRows:number}>('execute-import',{organizationId,action:'commit',importId})}
export function rollbackImport(organizationId:string,importId:string,rollbackReason:string){return invoke<{status:string}>('execute-import',{organizationId,action:'rollback',importId,rollbackReason})}

export async function getAgencyPerformance(organizationId:string,from:string,to:string){
  const [jobs,activeJobs,packages,interviews,offers,placements,tasks]=await Promise.all([
    supabase.from('jobs').select('id,status,owner_member_id').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
    supabase.from('jobs').select('id,status,owner_member_id').eq('organization_id',organizationId).eq('status','open').is('deleted_at',null),
    supabase.from('submission_packages').select('id,created_by,candidate_submissions(id,job_candidate_id)').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
    supabase.from('interviews').select('id,job_candidate_id,created_by,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
    supabase.from('offers').select('id,job_candidate_id,created_by,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
    supabase.from('placements').select('id,job_candidate_id,created_by,placement_fee,currency,status').eq('organization_id',organizationId).gte('created_at',from).lte('created_at',to),
    supabase.from('tasks').select('id,owner_member_id,status,due_at,deleted_at').eq('organization_id',organizationId).is('deleted_at',null),
  ])
  for(const result of [jobs,activeJobs,packages,interviews,offers,placements,tasks])if(result.error)fail(result.error,'Could not load agency performance')
  const submissions=(packages.data||[]).flatMap((pack)=>(pack.candidate_submissions||[]).map((submission)=>({...submission,created_by:pack.created_by})))
  return {jobs:jobs.data||[],activeJobs:activeJobs.data||[],submissions,interviews:interviews.data||[],offers:offers.data||[],placements:placements.data||[],tasks:tasks.data||[]}
}

export async function createRevenueSplit(organizationId:string,placementId:string,memberId:string,percentage:number){const {error}=await supabase.rpc('create_placement_revenue_split',{p_organization_id:organizationId,p_placement_id:placementId,p_member_id:memberId,p_percentage:percentage});if(error)fail(error,error.message.includes('split_total_exceeds_100')?'Consultant credits cannot exceed 100%.':'Could not create revenue split')}
export async function createInvoice(organizationId:string,placementId:string,invoiceNumber:string,amount:number,currency:string,dueDate:string){const {error}=await supabase.from('placement_invoices').insert({organization_id:organizationId,placement_id:placementId,invoice_reference:invoiceNumber,amount,currency,due_on:dueDate,status:'draft'});if(error)fail(error,'Could not create invoice')}
export async function updateInvoiceStatus(organizationId:string,invoiceId:string,status:'issued'|'paid'|'void'){const values=status==='issued'?{status,issued_on:new Date().toISOString().slice(0,10)}:status==='paid'?{status,paid_on:new Date().toISOString().slice(0,10)}:{status};const {error}=await supabase.from('placement_invoices').update(values).eq('organization_id',organizationId).eq('id',invoiceId);if(error)fail(error,'Could not update invoice')}
