import { supabase } from '../../shared/lib/supabase'
import { AppError } from '../../shared/lib/errors'
import type { Candidate, Company, Contact, Interview, Job, JobCandidate, Offer, PipelineStage, Placement, PublicReview, Task } from '../../shared/types/domain'
import type {Json,TablesInsert} from '../../generated/database.types'

function fail(error: {message:string;code?:string}|null, fallback:string): never { throw new AppError(error?.message||fallback,error?.code||'database_error',error) }

export async function listCandidates(organizationId:string, query='') {
  let request=supabase.from('candidates').select('id,organization_id,full_name,current_company,current_position,location,linkedin_url,status,source,availability,owner_member_id,created_at,candidate_private_details(email,phone,current_salary,expected_salary,salary_currency,consent_status)').eq('organization_id',organizationId).is('deleted_at',null).order('updated_at',{ascending:false}).limit(100)
  if(query) request=request.or(`full_name.ilike.%${query}%,current_company.ilike.%${query}%,current_position.ilike.%${query}%`)
  const {data,error}=await request;if(error)fail(error,'Could not load candidates');return (data??[]) as unknown as Candidate[]
}

export async function listCandidatesPage(organizationId:string,query='',page=0,pageSize=50){
  let request=supabase.from('candidates').select('id,organization_id,full_name,current_company,current_position,location,linkedin_url,status,source,availability,owner_member_id,created_at,candidate_private_details(email,phone,current_salary,expected_salary,salary_currency,consent_status)',{count:'exact'}).eq('organization_id',organizationId).is('deleted_at',null).order('updated_at',{ascending:false}).range(page*pageSize,page*pageSize+pageSize-1)
  if(query.trim())request=request.or(`full_name.ilike.%${query.trim()}%,current_company.ilike.%${query.trim()}%,current_position.ilike.%${query.trim()}%`)
  const {data,error,count}=await request;if(error)fail(error,'Could not load candidates');return {rows:(data??[]) as unknown as Candidate[],count:count??0}
}

export async function createCandidate(organizationId:string,userId:string,input:{full_name:string;email?:string;phone?:string;current_company?:string;current_position?:string;location?:string;source?:string;expected_salary?:number;salary_currency?:string}) {
  const {data,error}=await supabase.from('candidates').insert({organization_id:organizationId,full_name:input.full_name,current_company:input.current_company||null,current_position:input.current_position||null,location:input.location||null,source:input.source||null,status:'active',created_by:userId}).select('id').single()
  if(error)fail(error,error.code==='23505'?'A candidate with this email already exists.':'Could not create candidate')
  const privateResult=await supabase.from('candidate_private_details').insert({candidate_id:data.id,organization_id:organizationId,email:input.email||null,phone:input.phone||null,expected_salary:input.expected_salary??null,salary_currency:input.salary_currency||null})
  if(privateResult.error){await supabase.from('candidates').delete().eq('id',data.id);fail(privateResult.error,privateResult.error.code==='23505'?'A candidate with this email already exists.':'Could not save candidate private details')}
  return data.id as string
}

export async function listCompanies(organizationId:string){const {data,error}=await supabase.from('companies').select('*').eq('organization_id',organizationId).is('deleted_at',null).order('updated_at',{ascending:false});if(error)fail(error,'Could not load companies');return (data??[]) as unknown as Company[]}
export async function createCompany(organizationId:string,userId:string,input:{name:string;industry?:string;location?:string;website?:string;account_status:string}){const {data,error}=await supabase.from('companies').insert({...input,organization_id:organizationId,created_by:userId}).select('id').single();if(error)fail(error,'Could not create company');return data.id as string}

export async function listContacts(organizationId:string){const {data,error}=await supabase.from('contacts').select('id,organization_id,company_id,full_name,position,email,phone,contact_status,next_follow_up_at,companies(id,name)').eq('organization_id',organizationId).is('deleted_at',null).order('updated_at',{ascending:false});if(error)fail(error,'Could not load contacts');return (data??[]) as unknown as Contact[]}
export async function createContact(organizationId:string,userId:string,input:{company_id:string;full_name:string;position?:string;email?:string;phone?:string}){const {data,error}=await supabase.from('contacts').insert({...input,organization_id:organizationId,created_by:userId}).select('id').single();if(error)fail(error,'Could not create contact');return data.id as string}

export async function listJobs(organizationId:string){const {data,error}=await supabase.from('jobs').select('id,organization_id,company_id,pipeline_id,title,location,priority,status,currency,placement_fee_percentage,opened_at,updated_at,companies(id,name)').eq('organization_id',organizationId).is('deleted_at',null).order('updated_at',{ascending:false});if(error)fail(error,'Could not load jobs');return (data??[]) as unknown as Job[]}
export async function createJob(organizationId:string,input:{company_id:string;title:string;owner_member_id?:string}){const {data,error}=await supabase.rpc('create_job_with_pipeline',{p_organization_id:organizationId,p_company_id:input.company_id,p_title:input.title,p_owner_member_id:input.owner_member_id});if(error)fail(error,'Could not create job');return data as string}

export async function getPipeline(job:Job){if(!job.pipeline_id)return {stages:[],items:[]};const [stageResult,itemResult]=await Promise.all([supabase.from('pipeline_stages').select('*').eq('pipeline_id',job.pipeline_id).order('position'),supabase.from('job_candidates').select('id,job_id,candidate_id,current_stage_id,updated_at,candidates(id,organization_id,full_name,current_company,current_position,location,linkedin_url,status,source,availability,owner_member_id,created_at),pipeline_stages(id,pipeline_id,name,stage_key,stage_type,position,color)').eq('job_id',job.id)]);if(stageResult.error)fail(stageResult.error,'Could not load pipeline');if(itemResult.error)fail(itemResult.error,'Could not load pipeline candidates');return {stages:(stageResult.data??[]) as unknown as PipelineStage[],items:(itemResult.data??[]) as unknown as JobCandidate[]}}
export async function addCandidateToJob(organizationId:string,userId:string,job:Job,candidateId:string){if(!job.pipeline_id)throw new AppError('This job has no pipeline.');const {data:stage,error:stageError}=await supabase.from('pipeline_stages').select('id').eq('pipeline_id',job.pipeline_id).order('position').limit(1).single();if(stageError)fail(stageError,'Could not find the first stage');const {error}=await supabase.from('job_candidates').insert({organization_id:organizationId,job_id:job.id,candidate_id:candidateId,current_stage_id:stage.id,added_by:userId});if(error)fail(error,error.code==='23505'?'Candidate is already in this job.':'Could not add candidate')}
export async function moveCandidate(jobCandidateId:string,stageId:string){const {error}=await supabase.rpc('move_job_candidate_stage',{p_job_candidate_id:jobCandidateId,p_stage_id:stageId,p_source:'kanban'});if(error)fail(error,'Could not move candidate')}

export async function listTasks(organizationId:string){const {data,error}=await supabase.from('tasks').select('*,organization_members:owner_member_id(profiles:user_id(full_name,email)),task_links(candidate_id,company_id,contact_id,job_id,candidates(full_name),companies(name),contacts(full_name),jobs(title))').eq('organization_id',organizationId).is('deleted_at',null).order('due_at',{ascending:true,nullsFirst:false});if(error)fail(error,'Could not load tasks');return (data??[]) as unknown as Task[]}
export async function createTask(organizationId:string,userId:string,input:{title:string;description?:string;priority:string;due_at?:string;owner_member_id?:string;link?:{type:'candidate'|'company'|'contact'|'job';id:string}}){const {link,...task}=input;const {data,error}=await supabase.from('tasks').insert({...task,owner_member_id:task.owner_member_id||null,due_at:task.due_at||null,organization_id:organizationId,created_by:userId}).select('id').single();if(error)fail(error,'Could not create task');if(link){const linkRow:TablesInsert<'task_links'>={organization_id:organizationId,task_id:data.id,candidate_id:null,company_id:null,contact_id:null,job_id:null};linkRow[`${link.type}_id`]=link.id;const {error:linkError}=await supabase.from('task_links').insert(linkRow);if(linkError){await supabase.from('tasks').delete().eq('id',data.id);fail(linkError,'Could not link task')}}return data.id as string}
export async function completeTask(id:string){const {error}=await supabase.from('tasks').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id);if(error)fail(error,'Could not complete task')}

export async function listActivities(organizationId:string){const {data,error}=await supabase.from('activities').select('*').eq('organization_id',organizationId).order('occurred_at',{ascending:false}).limit(100);if(error)fail(error,'Could not load activities');return data??[]}
export async function createActivity(organizationId:string,userId:string,input:{activity_type:string;direction:string;subject?:string;summary:string}){const {error}=await supabase.from('activities').insert({...input,organization_id:organizationId,created_by:userId});if(error)fail(error,'Could not log activity')}

export async function listPlacements(organizationId:string){const {data,error}=await supabase.from('placements').select('id,candidate_id,job_id,company_id,start_date,salary,placement_fee,currency,guarantee_ends_on,status,candidates(full_name),jobs(title),companies(name),placement_revenue_splits(id,member_id,split_percentage,split_amount,organization_members:member_id(profiles:user_id(full_name,email))),placement_invoices(id,invoice_reference,amount,currency,issued_on,due_on,status,paid_on)').eq('organization_id',organizationId).order('start_date',{ascending:false});if(error)fail(error,'Could not load placements');return (data??[]) as unknown as Placement[]}
export async function createPlacement(organizationId:string,userId:string,input:{job_candidate_id:string;candidate_id:string;job_id:string;company_id:string;start_date:string;salary:number;placement_fee:number;currency:string;guarantee_days:number}){const {error}=await supabase.from('placements').insert({...input,organization_id:organizationId,created_by:userId});if(error)fail(error,error.code==='23505'?'This candidate already has a placement for the job.':'Could not create placement')}
export async function listInterviews(organizationId:string){const {data,error}=await supabase.from('interviews').select('id,job_candidate_id,interview_type,stage_label,starts_at,ends_at,timezone,location,meeting_url,status,organizer_member_id,attendee_emails,create_google_meet,calendar_event_id,calendar_event_url,calendar_sync_status,calendar_last_error,calendar_last_synced_at,calendar_retry_count,calendar_sync_version,calendar_synced_version,job_candidates(candidates(full_name),jobs(title))').eq('organization_id',organizationId).order('starts_at',{ascending:true});if(error)fail(error,'Could not load interviews');return (data??[]) as unknown as Interview[]}
export async function createInterview(organizationId:string,userId:string,input:{job_candidate_id:string;starts_at:string;ends_at:string;timezone:string;interview_type?:string;location?:string;meeting_url?:string;organizer_member_id?:string;attendee_emails?:string[];create_google_meet?:boolean}){const {data,error}=await supabase.from('interviews').insert({...input,organizer_member_id:input.organizer_member_id||null,attendee_emails:input.attendee_emails||[],calendar_sync_status:input.organizer_member_id?'pending':'not_requested',organization_id:organizationId,created_by:userId}).select('id').single();if(error)fail(error,'Could not schedule interview');return data.id as string}
export async function updateInterview(organizationId:string,interviewId:string,input:{starts_at:string;ends_at:string;timezone:string;location?:string;meeting_url?:string;attendee_emails?:string[];create_google_meet?:boolean}){const {error}=await supabase.from('interviews').update({...input,attendee_emails:input.attendee_emails||[],updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',interviewId);if(error)fail(error,'Could not update interview')}
export async function cancelInterview(organizationId:string,interviewId:string){const {error}=await supabase.from('interviews').update({status:'cancelled',cancelled_at:new Date().toISOString(),calendar_sync_status:'pending',updated_at:new Date().toISOString()}).eq('organization_id',organizationId).eq('id',interviewId);if(error)fail(error,'Could not cancel interview')}
export async function listOffers(organizationId:string){const {data,error}=await supabase.from('offers').select('id,job_candidate_id,salary,currency,offered_at,start_date,status,notes,job_candidates(candidates(full_name),jobs(title))').eq('organization_id',organizationId).order('offered_at',{ascending:false});if(error)fail(error,'Could not load offers');return (data??[]) as unknown as Offer[]}
export async function createOffer(organizationId:string,userId:string,input:{job_candidate_id:string;salary:number;currency:string;start_date?:string}){const {error}=await supabase.from('offers').insert({...input,organization_id:organizationId,created_by:userId,status:'presented'});if(error)fail(error,'Could not create offer')}
export async function updateOfferStatus(id:string,status:'accepted'|'declined'|'withdrawn'){const {error}=await supabase.from('offers').update({status}).eq('id',id);if(error)fail(error,'Could not update offer')}
export async function convertOfferToPlacement(offerId:string,fee:number,guaranteeDays=90){const {data,error}=await supabase.rpc('create_placement_from_offer',{p_offer_id:offerId,p_fee:fee,p_guarantee_days:guaranteeDays});if(error)fail(error,'Could not convert accepted offer to placement');return data as string}

export async function listSubmissionPackages(organizationId:string){const {data,error}=await supabase.from('submission_packages').select('id,title,message,status,created_at,jobs(title,companies(name)),candidate_submissions(id,status),public_submission_links(id,recipient_email,expires_at,revoked_at,last_accessed_at)').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)fail(error,'Could not load submissions');return data??[]}
export async function createSubmission(organizationId:string,input:{job_id:string;contact_id?:string;title:string;message?:string;items:Array<{job_candidate_id:string;candidate_summary:string;recruiter_comments?:string}>;recipient_name?:string;recipient_email?:string}){const {data,error}=await supabase.rpc('create_submission_package',{p_organization_id:organizationId,p_job_id:input.job_id,p_contact_id:input.contact_id,p_title:input.title,p_message:input.message,p_items:input.items as Json,p_recipient_name:input.recipient_name,p_recipient_email:input.recipient_email,p_expiry_days:7});if(error)fail(error,'Could not create submission');return data as {package_id:string;link_id:string;token:string;expires_at:string}}

export async function resolveReview(token:string){const {data,error}=await supabase.functions.invoke('public-review',{body:{action:'resolve',token},timeout:10_000});if(error)fail(error,'This review link is unavailable.');if((data as {error?:{message?:string}})?.error)throw new AppError((data as {error:{message?:string}}).error.message||'This review link is unavailable.','link_unavailable',data);return data as unknown as PublicReview}
export async function sendReviewFeedback(token:string,submissionId:string,decision:string,comments:string,reviewerName:string){const {data,error}=await supabase.functions.invoke('public-review',{body:{action:'feedback',token,submissionId,decision,comments,reviewerName},timeout:10_000});if(error)fail(error,'Could not save feedback');if((data as {error?:{message?:string}})?.error)throw new AppError((data as {error:{message?:string}}).error.message||'Could not save feedback','feedback_failed',data)}

export async function searchWorkspace(organizationId:string,query:string){const {data,error}=await supabase.rpc('search_workspace',{p_organization_id:organizationId,p_query:query,p_limit:30});if(error)fail(error,'Search failed');return (data??[]) as Array<{entity_type:string;entity_id:string;title:string;subtitle:string;rank:number}>}

export async function dashboardSummary(organizationId:string){
  const now=new Date().toISOString();const soon=new Date(Date.now()+7*86400000).toISOString()
  const [jobs,candidates,tasks,interviews,offers,placements,activities,companies,contacts,pipelineEntries,members,settings]=await Promise.all([
    supabase.from('jobs').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).eq('status','open').is('deleted_at',null),
    supabase.from('candidates').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).is('deleted_at',null),
    supabase.from('tasks').select('id,title,due_at,priority').eq('organization_id',organizationId).in('status',['open','in_progress']).lt('due_at',now).order('due_at').limit(8),
    supabase.from('interviews').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).gte('starts_at',now).lte('starts_at',soon),
    supabase.from('offers').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).in('status',['draft','presented']),
    supabase.from('placements').select('placement_fee,currency').eq('organization_id',organizationId).gte('created_at',new Date(new Date().getFullYear(),0,1).toISOString()),
    supabase.from('activities').select('id,activity_type,subject,summary,occurred_at').eq('organization_id',organizationId).order('occurred_at',{ascending:false}).limit(8),
    supabase.from('companies').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).is('deleted_at',null),
    supabase.from('contacts').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).is('deleted_at',null),
    supabase.from('job_candidates').select('id',{count:'exact',head:true}).eq('organization_id',organizationId),
    supabase.from('organization_members').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).eq('status','active'),
    supabase.from('organization_settings').select('settings').eq('organization_id',organizationId).maybeSingle(),
  ])
  for(const result of [jobs,candidates,tasks,interviews,offers,placements,activities,companies,contacts,pipelineEntries,members,settings])if(result.error)fail(result.error,'Could not load dashboard')
  const setupDismissedAt=(settings.data?.settings as {setup_dismissed_at?:string}|null)?.setup_dismissed_at??null
  return {activeJobs:jobs.count??0,candidates:candidates.count??0,overdueTasks:tasks.data??[],interviews:interviews.count??0,offers:offers.count??0,placements:placements.data??[],activities:activities.data??[],
    companies:companies.count??0,contacts:contacts.count??0,pipelineEntries:pipelineEntries.count??0,members:members.count??0,setupDismissedAt}
}

// Merges rather than replaces: `settings` is shared jsonb, so a blind write would clobber
// unrelated keys. Only the owner can reach this (organization.manage), so the read-modify-write
// window is not contended.
export async function dismissSetupChecklist(organizationId:string){
  const {data,error:readError}=await supabase.from('organization_settings').select('settings').eq('organization_id',organizationId).maybeSingle()
  if(readError)fail(readError,'Could not update setup preferences')
  const current=(data?.settings as Record<string,unknown>|null)??{}
  const {error}=await supabase.from('organization_settings').update({settings:{...current,setup_dismissed_at:new Date().toISOString()},updated_at:new Date().toISOString()}).eq('organization_id',organizationId)
  if(error)fail(error,'Could not hide the setup guide')
}

export async function listMembers(organizationId:string){const {data,error}=await supabase.from('organization_members').select('id,user_id,job_title,status,profiles:user_id(full_name,email)').eq('organization_id',organizationId).order('joined_at');if(error)fail(error,'Could not load team');return data??[]}
export async function listRoles(organizationId:string){const {data,error}=await supabase.from('roles').select('id,name,role_key,is_system,role_permissions(permission_key)').eq('organization_id',organizationId).order('name');if(error)fail(error,'Could not load roles');return data??[]}
export async function createInvitation(organizationId:string,email:string,roleId:string){const {data,error}=await supabase.rpc('create_organization_invitation',{p_organization_id:organizationId,p_email:email,p_role_id:roleId,p_expiry_days:7});if(error)fail(error,'Could not create invitation');return data as {invitation_id:string;token:string;expires_at:string}}
export async function acceptInvitation(token:string){const {data,error}=await supabase.rpc('accept_organization_invitation',{p_token:token});if(error)fail(error,error.message.includes('email_mismatch')?'Sign in with the email address that was invited.':'Could not accept invitation');if(!data)throw new AppError('This invitation is invalid, expired, or revoked.','invitation_unavailable');return data as {organization_id:string;organization_slug:string;member_id:string}}
