import { useState } from 'react'
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import { resolveReview,sendReviewFeedback } from '../core/repository'
import type { PublicSubmission } from '../../shared/types/domain'
import { Button } from '../../shared/ui/Button'
import { Field,Input,Textarea } from '../../shared/ui/Field'
import { Badge } from '../../shared/ui/Page'
import { ErrorState,LoadingState } from '../../shared/ui/States'
import { formatMoney } from '../../shared/lib/format'

function ReviewCandidate({token,candidate}:{token:string;candidate:PublicSubmission}){const cache=useQueryClient();const [decision,setDecision]=useState(candidate.feedback?.decision||'');const [comments,setComments]=useState(candidate.feedback?.comments||'');const [name,setName]=useState(candidate.feedback?.reviewer_name||'');const mutation=useMutation({mutationFn:()=>sendReviewFeedback(token,candidate.submission_id,decision,comments,name),onSuccess:()=>cache.invalidateQueries({queryKey:['public-review',token]})});return <article className="review-card"><h2>{candidate.candidate_name}</h2><p className="muted">{[candidate.current_position,candidate.current_company,candidate.location].filter(Boolean).join(' · ')}</p><p>{candidate.candidate_summary}</p>{candidate.suitability_assessment&&<><h3>Suitability</h3><p>{candidate.suitability_assessment}</p></>}<dl><dt>Expected salary</dt><dd>{formatMoney(candidate.expected_salary,candidate.currency)}</dd><dt>Notice period</dt><dd>{candidate.notice_period||'Not provided'}</dd><dt>Availability</dt><dd>{candidate.availability||'Not provided'}</dd></dl>{candidate.feedback&&<Badge tone="info">Current decision: {candidate.feedback.decision}</Badge>}<div className="decision-row"><Button variant={decision==='approve'?'primary':'secondary'} onClick={()=>setDecision('approve')}>Approve</Button><Button variant={decision==='interview'?'primary':'secondary'} onClick={()=>setDecision('interview')}>Request interview</Button><Button variant={decision==='hold'?'primary':'secondary'} onClick={()=>setDecision('hold')}>Hold</Button><Button variant={decision==='reject'?'danger':'secondary'} onClick={()=>setDecision('reject')}>Reject</Button></div><div className="stack"><Field label="Your name"><Input value={name} onChange={(event)=>setName(event.target.value)}/></Field><Field label="Feedback"><Textarea value={comments} onChange={(event)=>setComments(event.target.value)}/></Field>{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<Button disabled={!decision||mutation.isPending} onClick={()=>mutation.mutate()}>{mutation.isPending?'Saving…':'Save feedback'}</Button></div></article>}

export function PublicReviewPage(){const {token=''}=useParams();const query=useQuery({queryKey:['public-review',token],enabled:Boolean(token),queryFn:()=>resolveReview(token)});if(query.isLoading)return <LoadingState label="Opening secure candidate review…"/>;if(query.error||!query.data)return <ErrorState error={query.error}/>;return <main className="review-page"><header className="review-header"><p className="eyebrow">Confidential candidate review</p><h1>{query.data.package.title}</h1><p>{query.data.package.job_title} · {query.data.package.company_name}</p>{query.data.package.message&&<p>{query.data.package.message}</p>}{query.data.documents?.length?<div className="review-documents"><strong>Shared documents</strong>{query.data.documents.map((document)=><a href={document.url} target="_blank" rel="noreferrer" key={document.id}>{document.filename}</a>)}</div>:null}</header><section className="review-grid">{query.data.candidates.map((candidate)=><ReviewCandidate key={candidate.submission_id} token={token} candidate={candidate}/>)}</section></main>}
