import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Download,Plus} from 'lucide-react'
import {useOrganization} from '../../app/OrganizationProvider'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {useAuth} from '../../app/AuthProvider'
import {createPlacement,getPipeline,listJobs,listPlacements} from '../core/repository'
import {createInvoice,createRevenueSplit,listTeamMembers,updateInvoiceStatus} from '../core/commercialRepository'
import type {Placement} from '../../shared/types/domain'
import {Button} from '../../shared/ui/Button'
import {ConfirmDialog} from '../../shared/ui/ConfirmDialog'
import {Field,Input,Select} from '../../shared/ui/Field'
import {currencyOptions} from '../../shared/lib/currencies'
import {Modal} from '../../shared/ui/Modal'
import {useToast} from '../../shared/ui/Toast'
import {Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {invoiceStatus,placementStatus} from '../../shared/lib/status'
import {EmptyState,ErrorState,LoadingState} from '../../shared/ui/States'
import {Table} from '../../shared/ui/Table'
import {KpiGrid,KpiTile} from '../../shared/ui/KpiTile'
import {csvFilename,downloadCsv,toCsv} from '../../shared/lib/csv'
import {formatDate,formatMoney} from '../../shared/lib/format'

const invoiceStatusMessage={issued:'Invoice issued.',paid:'Invoice marked paid.',void:'Invoice voided.'} as const

export function PlacementsPage(){
  const {organization,memberships}=useOrganization();const {user}=useAuth();const cache=useQueryClient();const toast=useToast();const [open,setOpen]=useState(false);const [voiding,setVoiding]=useState<string|null>(null);const [financePlacement,setFinancePlacement]=useState<Placement|null>(null);const [jobId,setJobId]=useState('');const [jobCandidateId,setJobCandidateId]=useState('');const [startDate,setStartDate]=useState('');const [salary,setSalary]=useState('');const [fee,setFee]=useState('');const [currency,setCurrency]=useState(organization?.base_currency||'USD');const [splitMember,setSplitMember]=useState('');const [splitPercent,setSplitPercent]=useState('');const [invoiceReference,setInvoiceReference]=useState('');const [invoiceAmount,setInvoiceAmount]=useState('');const [invoiceDue,setInvoiceDue]=useState('')
  const capabilities=useWorkspaceCapabilities();const jobs=useQuery({queryKey:['jobs',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobs(organization!.id)});const job=jobs.data?.find((item)=>item.id===jobId);const pipeline=useQuery({queryKey:['pipeline',jobId],enabled:Boolean(job),queryFn:()=>getPipeline(job!)});const placements=useQuery({queryKey:['placements',organization?.id],enabled:Boolean(organization),queryFn:()=>listPlacements(organization!.id)});const team=useQuery({queryKey:['team',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)});const selected=pipeline.data?.items.find((item)=>item.id===jobCandidateId);const currentMembership=memberships.find((item)=>item.organization_id===organization?.id&&item.user_id===user?.id);const currentTeamMember=team.data?.find((item)=>item.id===currentMembership?.id);const canManageFinance=currentTeamMember?.member_roles?.some((item)=>['owner','admin','finance'].includes(item.roles?.role_key||''))||false
  const refresh=async()=>{await cache.invalidateQueries({queryKey:['placements',organization?.id]});const updated=await listPlacements(organization!.id);setFinancePlacement((current)=>updated.find((item)=>item.id===current?.id)||null)}
  /* This page moves money and used to do it in total silence -- recording a placement, crediting a
   * consultant, issuing an invoice and marking one paid all reported nothing on success and nothing on
   * failure. A consultant who has learned that the rest of the app confirms its writes reasonably
   * reads silence here as "it worked". */
  const mutation=useMutation({mutationFn:()=>createPlacement(organization!.id,user!.id,{job_candidate_id:jobCandidateId,candidate_id:selected!.candidate_id,job_id:job!.id,company_id:job!.company_id,start_date:startDate,salary:Number(salary),placement_fee:Number(fee),currency,guarantee_days:90}),onSuccess:async()=>{toast.success(`${selected?.candidates?.full_name||'The candidate'} is placed.`,`Fee ${formatMoney(Number(fee),currency)} · 90-day guarantee.`);setOpen(false);await refresh()},onError:(error)=>toast.error(error,'The placement was not recorded.')})
  const splitMutation=useMutation({mutationFn:()=>createRevenueSplit(organization!.id,financePlacement!.id,splitMember,Number(splitPercent)),onSuccess:async()=>{toast.success(`${team.data?.find((member)=>member.id===splitMember)?.profiles?.full_name||'The consultant'} credited ${Number(splitPercent)}%.`);setSplitMember('');setSplitPercent('');await refresh()},onError:(error)=>toast.error(error,'The revenue credit was not saved.')})
  const invoiceMutation=useMutation({mutationFn:()=>createInvoice(organization!.id,financePlacement!.id,invoiceReference,Number(invoiceAmount),financePlacement!.currency,invoiceDue),onSuccess:async()=>{toast.success(`Draft invoice ${invoiceReference||'created'}.`,`${formatMoney(Number(invoiceAmount),financePlacement?.currency)} due ${formatDate(invoiceDue)}.`);setInvoiceReference('');setInvoiceAmount('');setInvoiceDue('');await refresh()},onError:(error)=>toast.error(error,'The invoice was not created.')})
  /* The least-finished page in the app: a bare table of rows with no summary and no way to get the
   * numbers out, on the one screen whose whole subject is money. Both are computed from the rows
   * already loaded, so the tiles and the export can never disagree with what is on screen.
   *
   * Fees are summed per currency rather than added together. There is no exchange rate anywhere in
   * this product, and inventing one to make a single total would produce a number that looks
   * authoritative and is fiction -- the same reason buildConsultantRows only sums base-currency fees. */
  const rows=placements.data||[]
  const active=rows.filter((placement)=>placement.status!=='cancelled')
  const guaranteeOpen=active.filter((placement)=>placement.guarantee_ends_on&&new Date(placement.guarantee_ends_on)>new Date()).length
  const feeByCurrency=active.reduce<Record<string,number>>((totals,placement)=>{const code=placement.currency||organization?.base_currency||'';totals[code]=(totals[code]||0)+Number(placement.placement_fee||0);return totals},{})
  const feeSummary=Object.entries(feeByCurrency).map(([code,total])=>formatMoney(total,code)).join(' · ')||'—'
  const exportView=useMutation({
    mutationFn:async()=>rows,
    onSuccess:(exported)=>{
      downloadCsv(csvFilename('placements'),toCsv(exported.map((placement)=>({candidate:placement.candidates?.full_name||'',vacancy:placement.jobs?.title||'',client:placement.companies?.name||'',start_date:placement.start_date||'',placement_fee:placement.placement_fee??'',currency:placement.currency||'',guarantee_ends_on:placement.guarantee_ends_on||'',status:placement.status}))))
      toast.success(`Exported ${exported.length} ${exported.length===1?'placement':'placements'}.`)
    },
    onError:(error)=>toast.error(error,'Nothing was exported.'),
  })
  const setInvoiceStatus=useMutation({mutationFn:({id,status}:{id:string;status:'issued'|'paid'|'void'})=>updateInvoiceStatus(organization!.id,id,status),onSuccess:async(_result,variables)=>{toast.success(invoiceStatusMessage[variables.status]);setVoiding(null);await refresh()},onError:(error,variables)=>toast.error(error,`The invoice was not marked ${variables.status}.`)})
  return <Page title="Placements" eyebrow="Commercial outcomes" description="Track starts and guarantees for consultants; owner and finance roles also control revenue credits and invoice state." actions={<>{rows.length>0&&<Button variant="secondary" leadingIcon={<Download size={15}/>} loading={exportView.isPending} onClick={()=>exportView.mutate()}>Export</Button>}{capabilities.data?.canManagePlacements&&<Button leadingIcon={<Plus size={15}/>} onClick={()=>setOpen(true)}>Record placement</Button>}</>}>
    {rows.length>0&&<KpiGrid><KpiTile label="Placements" value={active.length} definition="Recorded placements that have not been cancelled."/><KpiTile label="Fees" value={feeSummary} definition="Placement fees, summed separately per currency -- no exchange rate is applied."/><KpiTile label="Guarantees running" value={guaranteeOpen} definition="Placements whose guarantee period has not yet ended."/><KpiTile label="Cancelled" value={rows.length-active.length} tone={rows.length-active.length?"alert":undefined} definition="Placements later cancelled, usually a candidate who did not start or left inside the guarantee."/></KpiGrid>}
    <Panel>{placements.isLoading?<LoadingState/>:placements.error?<ErrorState error={placements.error}/>:placements.data?.length===0?<EmptyState title="No placements" description="Convert a successful candidate and vacancy into a commercial outcome."/>:<Table headers={['Candidate','Vacancy','Client','Start date',{label:'Fee',align:'right'},'Guarantee ends','Status','Finance']}>{placements.data?.map((placement)=><tr key={placement.id}><td>{placement.candidates?.full_name||'—'}</td><td>{placement.jobs?.title||'—'}</td><td>{placement.companies?.name||'—'}</td><td>{formatDate(placement.start_date)}</td><td className="money">{formatMoney(placement.placement_fee,placement.currency)}</td><td>{formatDate(placement.guarantee_ends_on)}</td><td><StatusBadge map={placementStatus} value={placement.status}/></td><td>{canManageFinance?<Button variant="secondary" onClick={()=>setFinancePlacement(placement)}>Splits & invoices</Button>:<span>Owner controlled</span>}</td></tr>)}</Table>}</Panel>
    <Modal title="Record placement" open={open} onClose={()=>setOpen(false)}><div className="form-grid"><Field label="Vacancy"><Select value={jobId} onChange={(event)=>{setJobId(event.target.value);setJobCandidateId('')}}><option value="">Select vacancy</option>{jobs.data?.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</Select></Field><Field label="Candidate"><Select value={jobCandidateId} onChange={(event)=>setJobCandidateId(event.target.value)}><option value="">Select candidate</option>{pipeline.data?.items.map((item)=><option key={item.id} value={item.id}>{item.candidates?.full_name}</option>)}</Select></Field><Field label="Start date"><Input type="date" value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></Field><Field label="Salary"><Input type="number" min="0" value={salary} onChange={(event)=>setSalary(event.target.value)}/></Field><Field label="Placement fee"><Input type="number" min="0" value={fee} onChange={(event)=>setFee(event.target.value)}/></Field><Field label="Currency"><Select value={currency} onChange={(event)=>setCurrency(event.target.value)}>{currencyOptions(organization?.base_currency).map((option)=><option key={option.code} value={option.code}>{option.code} — {option.name}</option>)}</Select></Field>{mutation.error&&<p className="form-error full" role="alert">{mutation.error.message}</p>}<div className="form-actions full"><Button variant="quiet" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={mutation.isPending} disabled={!selected||!startDate||!salary||!fee} onClick={()=>mutation.mutate()}>Record placement</Button></div></div></Modal>
    <ConfirmDialog open={Boolean(voiding)} title="Void this invoice?" confirmLabel="Void invoice" loading={setInvoiceStatus.isPending}
      body="A voided invoice cannot be reissued or marked paid. Create a new invoice instead if the amount or reference needs to change."
      onClose={()=>setVoiding(null)} onConfirm={()=>{if(voiding)setInvoiceStatus.mutate({id:voiding,status:'void'})}}/>
    <Modal title="Placement finance" open={Boolean(financePlacement)} onClose={()=>setFinancePlacement(null)}><div className="stack"><div><strong>{financePlacement?.candidates?.full_name}</strong><p className="muted">Fee {formatMoney(financePlacement?.placement_fee,financePlacement?.currency)}</p></div><section><h3>Consultant revenue credits</h3><div className="settings-list">{financePlacement?.placement_revenue_splits?.map((split)=><article key={split.id} className="finance-row"><span>{split.organization_members?.profiles?.full_name||split.organization_members?.profiles?.email}</span><strong>{Number(split.split_percentage)}%</strong></article>)}{!financePlacement?.placement_revenue_splits?.length&&<p className="muted">No consultant credits assigned.</p>}</div><div className="form-grid"><Field label="Consultant"><Select value={splitMember} onChange={(event)=>setSplitMember(event.target.value)}><option value="">Select consultant</option>{team.data?.filter((member)=>member.status==='active').map((member)=><option value={member.id} key={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select></Field><Field label="Credit percentage"><Input type="number" min="0.001" max="100" step="0.001" value={splitPercent} onChange={(event)=>setSplitPercent(event.target.value)}/></Field></div>{splitMutation.error&&<p className="form-error" role="alert">{splitMutation.error.message}</p>}<Button variant="secondary" loading={splitMutation.isPending} disabled={!splitMember||!splitPercent} onClick={()=>splitMutation.mutate()}>Save consultant credit</Button></section><section><h3>Invoices</h3><div className="settings-list">{financePlacement?.placement_invoices?.map((invoice)=><article key={invoice.id} className="finance-row"><div><strong>{invoice.invoice_reference||'Unnumbered invoice'}</strong><span>{formatMoney(invoice.amount,invoice.currency)} · due {formatDate(invoice.due_on)}</span></div><div className="table-actions"><StatusBadge map={invoiceStatus} value={invoice.status}/>{invoice.status==='draft'&&<Button variant="secondary" onClick={()=>setInvoiceStatus.mutate({id:invoice.id,status:'issued'})}>Issue</Button>}{invoice.status==='issued'&&<Button onClick={()=>setInvoiceStatus.mutate({id:invoice.id,status:'paid'})}>Mark paid</Button>}{/* Voiding cannot be undone -- the status check constraint has no path back out of 'void' -- so it
                  takes the danger tier and a confirmation, rather than the quiet button that sat one pixel
                  from "Mark paid". */}
                {!['paid','void'].includes(invoice.status)&&<Button variant="caution" onClick={()=>setVoiding(invoice.id)}>Void</Button>}</div></article>)}{!financePlacement?.placement_invoices?.length&&<p className="muted">No invoice recorded.</p>}</div><div className="form-grid"><Field label="Invoice reference"><Input value={invoiceReference} onChange={(event)=>setInvoiceReference(event.target.value)}/></Field><Field label="Amount"><Input type="number" min="0" value={invoiceAmount} onChange={(event)=>setInvoiceAmount(event.target.value)}/></Field><Field label="Due date"><Input type="date" value={invoiceDue} onChange={(event)=>setInvoiceDue(event.target.value)}/></Field></div>{invoiceMutation.error&&<p className="form-error" role="alert">{invoiceMutation.error.message}</p>}<Button variant="secondary" loading={invoiceMutation.isPending} disabled={!invoiceAmount||!invoiceDue} onClick={()=>invoiceMutation.mutate()}>Create draft invoice</Button></section></div></Modal>
  </Page>
}
