import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Building2,CalendarCheck,CalendarX,Copy,ImageUp,RefreshCw,ShieldCheck,Trash2,UserPlus} from 'lucide-react'
import {useSearchParams} from 'react-router-dom'
import {useOrganization} from '../../app/OrganizationProvider'
import {useAuth} from '../../app/AuthProvider'
import {disconnectCalendar,listCalendarConnections,listInvitations,listOrganizationRoles,listTeamMembers,removeOrganizationLogo,revokeInvitation,sendTeamInvitation,startCalendarConnection,updateMemberAccess,updateOrganizationAccent,uploadOrganizationLogo} from '../core/commercialRepository'
import {Button} from '../../shared/ui/Button'
import {Field,Input,Select} from '../../shared/ui/Field'
import {Modal} from '../../shared/ui/Modal'
import {Badge,Page,Panel} from '../../shared/ui/Page'
import {ErrorState,LoadingState} from '../../shared/ui/States'
import type {TeamMember} from '../../shared/types/domain'

export function SettingsPage(){
  const {organization,memberships,refresh}=useOrganization();const {user}=useAuth();const [params]=useSearchParams();const cache=useQueryClient();const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [roleId,setRoleId]=useState('');const [previewLink,setPreviewLink]=useState('');const [accent,setAccent]=useState(organization?.primary_color||'#196f52')
  const members=useQuery({queryKey:['members',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  const roles=useQuery({queryKey:['roles',organization?.id],enabled:Boolean(organization),queryFn:()=>listOrganizationRoles(organization!.id)})
  const invitations=useQuery({queryKey:['invitations',organization?.id],enabled:Boolean(organization),queryFn:()=>listInvitations(organization!.id)})
  const calendar=useQuery({queryKey:['calendar-connections',organization?.id],enabled:Boolean(organization),queryFn:()=>listCalendarConnections(organization!.id)})
  const refreshTeam=()=>Promise.all([cache.invalidateQueries({queryKey:['members',organization?.id]}),cache.invalidateQueries({queryKey:['invitations',organization?.id]}),cache.invalidateQueries({queryKey:['calendar-connections',organization?.id]})])
  const invite=useMutation({mutationFn:()=>sendTeamInvitation(organization!.id,email,roleId),onSuccess:async(result)=>{setOpen(false);setEmail('');setRoleId('');setPreviewLink(result.previewUrl||'');await refreshTeam()}})
  const access=useMutation({mutationFn:({member,status,nextRoleId}:{member:TeamMember;status:'active'|'suspended';nextRoleId:string})=>updateMemberAccess(organization!.id,member.id,status,nextRoleId),onSuccess:refreshTeam})
  const revoke=useMutation({mutationFn:revokeInvitation,onSuccess:refreshTeam})
  const connect=useMutation({mutationFn:()=>startCalendarConnection(organization!.id,`/app/${organization!.slug}/settings`),onSuccess:(result)=>window.location.assign(result.authorizationUrl)})
  const disconnect=useMutation({mutationFn:()=>disconnectCalendar(organization!.id),onSuccess:refreshTeam})
  const saveBrand=useMutation({mutationFn:()=>updateOrganizationAccent(organization!.id,accent),onSuccess:()=>refresh()})
  const uploadLogo=useMutation({mutationFn:(file:File)=>uploadOrganizationLogo(organization!.id,file,organization?.logo_path),onSuccess:()=>refresh()})
  const removeLogo=useMutation({mutationFn:()=>removeOrganizationLogo(organization!.id,organization!.logo_path!),onSuccess:()=>refresh()})
  if(members.isLoading||roles.isLoading||invitations.isLoading||calendar.isLoading)return <LoadingState/>;if(members.error||roles.error||invitations.error||calendar.error)return <ErrorState error={members.error||roles.error||invitations.error||calendar.error}/>
  const currentMembership=memberships.find((item)=>item.user_id===user?.id);const currentTeamMember=members.data?.find((item)=>item.user_id===user?.id);const canManageOrganization=currentTeamMember?.member_roles?.some((item)=>['owner','admin'].includes(item.roles?.role_key||''))??false;const ownConnection=calendar.data?.find((item)=>item.member_id===currentMembership?.id)
  return <Page title="Settings" eyebrow="Organization controls" description="Invitation-only access, database-authoritative roles, and individual Google Calendar connections." actions={<Button onClick={()=>setOpen(true)}><UserPlus size={15}/>Invite team member</Button>}>
    {params.get('calendar')==='connected'&&<p className="success-box" role="status">Google Calendar connected successfully.</p>}{params.get('calendar')&&params.get('calendar')!=='connected'&&<p className="form-error" role="alert">Calendar connection was not completed. Try reconnecting.</p>}
    {previewLink&&<Panel title="Development invitation preview" action={<Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(previewLink)}><Copy size={14}/>Copy</Button>}><p className="muted">Email delivery is not configured locally. This raw link is shown only for development.</p><code>{previewLink}</code></Panel>}
    <div className="settings-section-heading"><Building2 size={18}/><div><h2>Workspace identity</h2><p>Agency details and white-label presentation.</p></div></div>
    <div className="two-column"><Panel title="Workspace"><div className="settings-list"><article><strong>Name</strong><p>{organization?.name}</p></article><article><strong>Slug</strong><p>{organization?.slug}</p></article><article><strong>Base currency</strong><p>{organization?.base_currency}</p></article><article><strong>Timezone</strong><p>{organization?.timezone}</p></article><article><strong>Access model</strong><p><ShieldCheck size={15}/> Invitation-only Google accounts</p></article></div></Panel>
      {canManageOrganization&&<Panel title="Brand presentation" subtitle="Used in navigation and client-facing identity."><div className="branding-editor"><div className="brand-preview"><span style={{background:accent}}>{organization?.logo_url?<img src={organization.logo_url} alt="Organization logo preview"/>:organization?.name.slice(0,2).toUpperCase()}</span><div><strong>{organization?.name}</strong><small>Executive recruitment workspace</small></div></div><Field label="Accent color"><div className="color-field"><input type="color" value={accent} onChange={(event)=>setAccent(event.target.value)}/><Input value={accent} maxLength={7} onChange={(event)=>setAccent(event.target.value)}/><Button variant="secondary" loading={saveBrand.isPending} onClick={()=>saveBrand.mutate()}>Save color</Button></div></Field><div className="form-actions branding-actions"><label className="button button-secondary button-md"><ImageUp size={15}/><span>{uploadLogo.isPending?'Uploading…':'Upload logo'}</span><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" disabled={uploadLogo.isPending} onChange={(event)=>{const file=event.target.files?.[0];if(file)uploadLogo.mutate(file);event.currentTarget.value='' }}/></label>{organization?.logo_path&&<Button variant="danger" leadingIcon={<Trash2 size={14}/>} loading={removeLogo.isPending} onClick={()=>removeLogo.mutate()}>Remove</Button>}</div><p className="muted">PNG, JPG, or WebP · maximum 2 MB. If no logo is uploaded, the agency initials are used.</p>{(saveBrand.error||uploadLogo.error||removeLogo.error)&&<p className="form-error" role="alert">{(saveBrand.error||uploadLogo.error||removeLogo.error)?.message}</p>}</div></Panel>}
      <Panel title="My Google Calendar"><div className="settings-list">{ownConnection?.status==='connected'?<><article><strong>{ownConnection.google_email}</strong><p>Connected · last sync {ownConnection.last_synced_at?new Date(ownConnection.last_synced_at).toLocaleString():'not yet'}</p></article>{ownConnection.last_error&&<p className="form-error">{ownConnection.last_error}</p>}<div className="form-actions"><Button variant="secondary" disabled={connect.isPending} onClick={()=>connect.mutate()}><RefreshCw size={14}/>Reconnect</Button><Button variant="danger" disabled={disconnect.isPending} onClick={()=>disconnect.mutate()}><CalendarX size={14}/>Disconnect</Button></div></>:<><p className="muted">Connect your own Google account so ATS interview changes create and update events on your primary Calendar.</p><Button disabled={connect.isPending} onClick={()=>connect.mutate()}><CalendarCheck size={15}/>Connect Google Calendar</Button></>}</div>{(connect.error||disconnect.error)&&<p className="form-error" role="alert">{(connect.error||disconnect.error)?.message}</p>}</Panel>
    </div>
    <Panel title="Team access"><div className="list">{members.data?.map((member)=>{const role=member.member_roles?.[0]?.roles;return <article className="team-access-row" key={member.id}><div><strong>{member.profiles?.full_name||'Team member'}</strong><span>{member.profiles?.email}</span></div><Select aria-label={`Role for ${member.profiles?.email||'member'}`} value={role?.id||''} disabled={access.isPending} onChange={(event)=>access.mutate({member,status:member.status==='suspended'?'suspended':'active',nextRoleId:event.target.value})}>{roles.data?.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Badge tone={member.status==='active'?'good':'warn'}>{member.status}</Badge><Button variant={member.status==='active'?'danger':'secondary'} disabled={!role||access.isPending} onClick={()=>role&&access.mutate({member,status:member.status==='active'?'suspended':'active',nextRoleId:role.id})}>{member.status==='active'?'Suspend':'Reactivate'}</Button></article>})}</div>{access.error&&<p className="form-error" role="alert">{access.error.message}</p>}</Panel>
    <Panel title="Pending and recent invitations"><div className="list">{invitations.data?.length===0?<p className="muted">No invitations yet.</p>:invitations.data?.map((invitation)=><article className="list-row" key={invitation.id}><div><strong>{invitation.email}</strong><span>{invitation.roles?.name||'Role'} · expires {new Date(invitation.expires_at).toLocaleDateString()}</span></div><div><Badge tone={invitation.accepted_at?'good':invitation.revoked_at?'bad':invitation.delivery_status==='sent'?'info':'warn'}>{invitation.accepted_at?'accepted':invitation.revoked_at?'revoked':invitation.delivery_status}</Badge>{!invitation.accepted_at&&!invitation.revoked_at&&<Button variant="danger" disabled={revoke.isPending} onClick={()=>revoke.mutate(invitation.id)}>Revoke</Button>}</div></article>)}</div>{revoke.error&&<p className="form-error" role="alert">{revoke.error.message}</p>}</Panel>
    <Modal title="Invite team member" open={open} onClose={()=>setOpen(false)}><div className="stack"><Field label="Exact Google email"><Input type="email" value={email} onChange={(event)=>setEmail(event.target.value)} autoComplete="off"/></Field><Field label="Role"><Select value={roleId} onChange={(event)=>setRoleId(event.target.value)}><option value="">Select role</option>{roles.data?.filter((role)=>['owner','admin','consultant'].includes(role.role_key)).map((role)=><option value={role.id} key={role.id}>{role.name}</option>)}</Select></Field><p className="muted">The invitation expires in seven days and can only be accepted by this exact Google account.</p>{invite.error&&<p className="form-error" role="alert">{invite.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!email||!roleId||invite.isPending} onClick={()=>invite.mutate()}>{invite.isPending?'Sending…':'Send invitation'}</Button></div></div></Modal>
  </Page>
}
