import { useState } from 'react'
import { useMutation,useQuery } from '@tanstack/react-query'
import { Copy,UserPlus } from 'lucide-react'
import { useOrganization } from '../../app/OrganizationProvider'
import { createInvitation,listMembers,listRoles } from '../core/repository'
import { Button } from '../../shared/ui/Button'
import { Field,Input,Select } from '../../shared/ui/Field'
import { Modal } from '../../shared/ui/Modal'
import { Badge,Page,Panel } from '../../shared/ui/Page'
import { ErrorState,LoadingState } from '../../shared/ui/States'

export function SettingsPage(){const {organization}=useOrganization();const [open,setOpen]=useState(false);const [email,setEmail]=useState('');const [roleId,setRoleId]=useState('');const [inviteLink,setInviteLink]=useState('');const members=useQuery({queryKey:['members',organization?.id],enabled:Boolean(organization),queryFn:()=>listMembers(organization!.id)});const roles=useQuery({queryKey:['roles',organization?.id],enabled:Boolean(organization),queryFn:()=>listRoles(organization!.id)});const invite=useMutation({mutationFn:()=>createInvitation(organization!.id,email,roleId),onSuccess:(result)=>{setInviteLink(`${window.location.origin}/invite/${result.token}`);setOpen(false)}});if(members.isLoading||roles.isLoading)return <LoadingState/>;if(members.error||roles.error)return <ErrorState error={members.error||roles.error}/>;return <Page title="Settings" eyebrow="Organization controls" description="Workspace identity, team membership, invitations, and database-authoritative roles." actions={<Button onClick={()=>setOpen(true)}><UserPlus size={15}/>Invite recruiter</Button>}>
  {inviteLink&&<Panel title="Invitation created" action={<Button variant="secondary" onClick={()=>void navigator.clipboard.writeText(inviteLink)}><Copy size={14}/>Copy link</Button>}><div className="settings-list"><code>{inviteLink}</code><p className="muted">Share this seven-day link with the invited email address. A production email adapter can deliver it later.</p></div></Panel>}
  <div className="two-column"><Panel title="Workspace"><div className="settings-list"><article><strong>Name</strong><p>{organization?.name}</p></article><article><strong>Slug</strong><p>{organization?.slug}</p></article><article><strong>Base currency</strong><p>{organization?.base_currency}</p></article><article><strong>Timezone</strong><p>{organization?.timezone}</p></article></div></Panel><Panel title="Team"><div className="list">{members.data?.map((member)=><article className="list-row" key={String(member.id)}><div><strong>{String((member.profiles as {full_name?:string}|null)?.full_name||'Team member')}</strong><span>{String((member.profiles as {email?:string}|null)?.email||'')}</span></div><Badge tone="good">{String(member.status)}</Badge></article>)}</div></Panel><Panel title="Role templates" className="full"><div className="settings-list">{roles.data?.map((role)=><article key={String(role.id)}><strong>{String(role.name)}</strong><p className="muted">{Array.isArray(role.role_permissions)?role.role_permissions.length:0} permission grants · {role.is_system?'Seeded template':'Custom role'}</p></article>)}</div></Panel></div>
  <Modal title="Invite team member" open={open} onClose={()=>setOpen(false)}><div className="stack"><Field label="Email"><Input type="email" value={email} onChange={(event)=>setEmail(event.target.value)}/></Field><Field label="Role"><Select value={roleId} onChange={(event)=>setRoleId(event.target.value)}><option value="">Select role</option>{roles.data?.map((role)=><option value={String(role.id)} key={String(role.id)}>{String(role.name)}</option>)}</Select></Field>{invite.error&&<p className="form-error" role="alert">{invite.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!email||!roleId||invite.isPending} onClick={()=>invite.mutate()}>Create invitation</Button></div></div></Modal>
</Page>}
