import { useState, type FormEvent } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { supabase } from '../../shared/lib/supabase'
import { env } from '../../shared/lib/env'
import { Button } from '../../shared/ui/Button'
import { Field, Input } from '../../shared/ui/Field'
import { useAuth } from '../../app/AuthProvider'

function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="auth-page"><section className="auth-brand"><p className="eyebrow">Recruitment operating system</p><h1>{env.productName}</h1><p>One connected workspace for candidates, clients, vacancies, submissions, placements, and revenue.</p></section><section className="auth-card"><h2>{title}</h2><p>{subtitle}</p>{children}</section></main>}

export function LoginPage(){const {user}=useAuth();const location=useLocation();const navigate=useNavigate();const [email,setEmail]=useState('owner@northstar.local');const [password,setPassword]=useState('LocalTest!123');const [error,setError]=useState('');const [busy,setBusy]=useState(false);if(user)return <Navigate to="/app" replace/>;async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');const result=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setError(result.error.message);else navigate((location.state as {from?:string}|null)?.from||'/app')}return <AuthFrame title="Welcome back" subtitle="Sign in to your agency workspace."><form onSubmit={submit} className="stack"><Field label="Email"><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required autoComplete="email"/></Field><Field label="Password"><Input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required autoComplete="current-password"/></Field>{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={busy}>{busy?'Signing in…':'Sign in'}</Button></form><div className="auth-links"><Link to="/reset-password">Forgot password?</Link><Link to="/signup">Create account</Link></div></AuthFrame>}

export function SignupPage(){const navigate=useNavigate();const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();const {error:signError}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(signError)setError(signError.message);else navigate('/onboarding')}return <AuthFrame title="Create your account" subtitle="Your organization is created after secure signup."><form onSubmit={submit} className="stack"><Field label="Full name"><Input value={name} onChange={(e)=>setName(e.target.value)} required/></Field><Field label="Work email"><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></Field><Field label="Password"><Input type="password" minLength={8} value={password} onChange={(e)=>setPassword(e.target.value)} required/></Field>{error&&<p className="form-error">{error}</p>}<Button>Create account</Button></form><div className="auth-links"><Link to="/login">Back to sign in</Link></div></AuthFrame>}

export function ResetPasswordPage(){const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();const {error:resetError}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(resetError)setError(resetError.message);else setSent(true)}return <AuthFrame title="Reset password" subtitle="We will email a secure recovery link.">{sent?<p className="success-box">Check your inbox for the recovery link.</p>:<form onSubmit={submit} className="stack"><Field label="Email"><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></Field>{error&&<p className="form-error">{error}</p>}<Button>Send recovery link</Button></form>}<div className="auth-links"><Link to="/login">Back to sign in</Link></div></AuthFrame>}

export function OnboardingPage(){const {user}=useAuth();const navigate=useNavigate();const [name,setName]=useState('');const [slug,setSlug]=useState('');const [currency,setCurrency]=useState('USD');const [error,setError]=useState('');if(!user)return <Navigate to="/login"/>;async function submit(event:FormEvent){event.preventDefault();const {error:rpcError}=await supabase.rpc('create_organization',{p_name:name,p_slug:slug,p_currency:currency,p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});if(rpcError)setError(rpcError.message);else{localStorage.setItem('agency_active_org',slug);window.location.assign('/app')}}return <AuthFrame title="Create your agency workspace" subtitle="This becomes the isolated home for your team and recruitment data."><form onSubmit={submit} className="stack"><Field label="Agency name"><Input value={name} onChange={(e)=>{setName(e.target.value);setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}} required/></Field><Field label="Workspace slug"><Input value={slug} onChange={(e)=>setSlug(e.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></Field><Field label="Base currency"><Input value={currency} onChange={(e)=>setCurrency(e.target.value.toUpperCase())} maxLength={3} required/></Field>{error&&<p className="form-error">{error}</p>}<Button>Create workspace</Button></form></AuthFrame>}

