import { createClient } from '@supabase/supabase-js'
import { beforeAll,describe,expect,it } from 'vitest'

const url=process.env.SUPABASE_URL||'http://127.0.0.1:55321'
const anon=process.env.SUPABASE_ANON_KEY
if(!anon)throw new Error('SUPABASE_ANON_KEY is required; RLS tests must not silently skip.')
const owner=createClient(url,anon,{auth:{persistSession:false}})
const rival=createClient(url,anon,{auth:{persistSession:false}})
const consultant=createClient(url,anon,{auth:{persistSession:false}})
const required=<T,>(value:T|null|undefined,what:string):T=>{if(value===null||value===undefined)throw new Error(`${what} is required`);return value}
beforeAll(async()=>{const first=await owner.auth.signInWithPassword({email:'owner@northstar.local',password:'LocalTest!123'});const second=await rival.auth.signInWithPassword({email:'owner@rival.local',password:'LocalTest!123'});const third=await consultant.auth.signInWithPassword({email:'consultant@northstar.local',password:'LocalTest!123'});if(first.error||second.error||third.error)throw first.error||second.error||third.error})
describe('organization isolation',()=>{it('cannot read a foreign organization by known UUID',async()=>{const result=await owner.from('organizations').select('id').eq('id','30000000-0000-0000-0000-000000000002');expect(result.error).toBeNull();expect(result.data).toEqual([])});it('cannot insert a candidate into a foreign organization',async()=>{const result=await owner.from('candidates').insert({organization_id:'30000000-0000-0000-0000-000000000002',full_name:'Cross tenant attack',created_by:'10000000-0000-0000-0000-000000000001'});expect(result.error).not.toBeNull()});it('keeps each owner inside their own candidate set',async()=>{const [northstarResult,rivalResult]=await Promise.all([owner.from('candidates').select('organization_id'),rival.from('candidates').select('organization_id')]);expect(northstarResult.data?.every((row)=>row.organization_id==='30000000-0000-0000-0000-000000000001')).toBe(true);expect(rivalResult.data?.every((row)=>row.organization_id==='30000000-0000-0000-0000-000000000002')).toBe(true)})})

describe('pilot permission matrix',()=>{
  it('grants consultants operational writes but not administration, imports, or finance',async()=>{const keys=['companies.write','contacts.write','tasks.write','finance.write','imports.manage','organization.manage'];const checks=await Promise.all(keys.map((permission)=>consultant.rpc('has_permission',{p_organization_id:'30000000-0000-0000-0000-000000000001',p_permission:permission})));expect(checks.map((result)=>result.data)).toEqual([true,true,true,false,false,false])})
  it('keeps encrypted Calendar refresh tokens outside normal authenticated access',async()=>{const result=await owner.from('google_calendar_secrets').select('id,encrypted_refresh_token');expect(result.error?.code).toBe('42501');expect(result.data).toBeNull()})
  it('does not expose team invitations to consultants',async()=>{const result=await consultant.from('organization_invitations').select('id,email').eq('organization_id','30000000-0000-0000-0000-000000000001');expect(result.error).toBeNull();expect(result.data).toEqual([])})
  it('keeps CV extraction drafts private to their uploader and tenant',async()=>{const own=await consultant.from('candidate_cv_parses').select('id,extracted_data');expect(own.error).toBeNull();expect(own.data?.map((row)=>row.id)).toEqual(['71000000-0000-0000-0000-000000000001']);const ownerView=await owner.from('candidate_cv_parses').select('id,extracted_data');expect(ownerView.error).toBeNull();expect(ownerView.data).toEqual([]);const rivalView=await rival.from('candidate_cv_parses').select('id,extracted_data').eq('id','71000000-0000-0000-0000-000000000001');expect(rivalView.error).toBeNull();expect(rivalView.data).toEqual([])})
  it('prevents authenticated clients from bypassing the hardened public-review Edge Function',async()=>{const result=await consultant.rpc('resolve_submission_link',{p_token:'x'.repeat(43)});expect(result.error?.code).toBe('42501')})
  it('prevents authenticated clients from calling submit_submission_feedback directly',async()=>{const result=await consultant.rpc('submit_submission_feedback',{p_token:'x'.repeat(43),p_candidate_submission_id:'00000000-0000-0000-0000-000000000000',p_decision:'approve'});expect(result.error?.code).toBe('42501')})
  it('keeps the profile AI spend aggregate service_role-only',async()=>{const result=await owner.rpc('candidate_profile_token_spend_this_month',{p_organization_id:'30000000-0000-0000-0000-000000000001'});expect(result.error?.code).toBe('42501')})
  it('removes database access immediately when a member is suspended',async()=>{const role=await owner.from('roles').select('id').eq('organization_id','30000000-0000-0000-0000-000000000001').eq('role_key','consultant').single();expect(role.error).toBeNull();const roleId=role.data?.id;if(!roleId)throw new Error('Seeded consultant role is required');const suspend=await owner.rpc('update_member_access',{p_organization_id:'30000000-0000-0000-0000-000000000001',p_member_id:'40000000-0000-0000-0000-000000000003',p_status:'suspended',p_role_id:roleId});expect(suspend.error).toBeNull();const blocked=await consultant.from('candidates').select('id');expect(blocked.data).toEqual([]);const restore=await owner.rpc('update_member_access',{p_organization_id:'30000000-0000-0000-0000-000000000001',p_member_id:'40000000-0000-0000-0000-000000000003',p_status:'active',p_role_id:roleId});expect(restore.error).toBeNull()})
})

describe('candidate profile boundaries',()=>{
  const northstar='30000000-0000-0000-0000-000000000001'
  it('exposes only same-organization templates',async()=>{const [first,second]=await Promise.all([owner.from('templates').select('organization_id').eq('template_type','candidate_profile'),rival.from('templates').select('organization_id').eq('template_type','candidate_profile')]);expect(first.error).toBeNull();expect(second.error).toBeNull();expect(first.data?.length).toBeGreaterThan(0);expect(first.data?.every((row)=>row.organization_id===northstar)).toBe(true);expect(second.data?.every((row)=>row.organization_id==='30000000-0000-0000-0000-000000000002')).toBe(true)})
  it('lets consultants use but not manage templates',async()=>{const template=await consultant.from('templates').select('id,name,configuration').eq('organization_id',northstar).eq('template_type','candidate_profile').limit(1).single();expect(template.error).toBeNull();const data=required(template.data,'candidate profile template');const direct=await consultant.from('templates').update({name:'Consultant takeover'}).eq('id',data.id).select('id');expect(direct.data??[]).toEqual([]);const rpc=await consultant.rpc('save_candidate_profile_template',{p_organization_id:northstar,p_template_id:data.id,p_name:'Consultant takeover',p_configuration:data.configuration,p_is_default:true});expect(rpc.error).not.toBeNull();expect(rpc.error?.message).toContain('permission_denied')})
  it('lets owners save their own controlled template but not a rival template',async()=>{const template=await owner.from('templates').select('id,name,configuration,is_default').eq('organization_id',northstar).eq('template_type','candidate_profile').limit(1).single();expect(template.error).toBeNull();const data=required(template.data,'candidate profile template');const saved=await owner.rpc('save_candidate_profile_template',{p_organization_id:northstar,p_template_id:data.id,p_name:data.name,p_configuration:data.configuration,p_is_default:data.is_default});expect(saved.error).toBeNull();const attack=await rival.rpc('save_candidate_profile_template',{p_organization_id:northstar,p_template_id:data.id,p_name:'Rival takeover',p_configuration:data.configuration,p_is_default:true});expect(attack.error).not.toBeNull()})
  it('prevents authenticated users from forging AI evidence',async()=>{const inserted=await owner.from('ai_evaluations').insert({organization_id:northstar,candidate_id:'70000000-0000-0000-0000-000000000001',job_id:'80000000-0000-0000-0000-000000000001',evaluation_type:'candidate_profile',provider:'forged',model:'forged',prompt_version:'forged',status:'completed',requested_by:'10000000-0000-0000-0000-000000000001'});expect(inserted.error).not.toBeNull()})
  it('never returns foreign evaluations or profile versions',async()=>{const [evaluations,versions]=await Promise.all([rival.from('ai_evaluations').select('organization_id').eq('organization_id',northstar),rival.from('candidate_profile_versions').select('organization_id').eq('organization_id',northstar)]);expect(evaluations.data).toEqual([]);expect(versions.data).toEqual([])})
})
