import {useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {BriefcaseBusiness,CalendarPlus,CheckCircle2,FileText,Handshake,Mail,MoveRight,TriangleAlert} from 'lucide-react'
import {Link} from 'react-router-dom'
import {useAuth} from '../../app/AuthProvider'
import {useOrganization} from '../../app/OrganizationProvider'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {convertOfferToPlacement,createInterview,createOffer,listContacts,listJobHealth,moveCandidate,type PlacementFeeSource} from '../core/repository'
import {getCandidateDetail,listCalendarConnections,listSubmissionCandidateDocuments,sendClientSubmission,syncInterviewCalendar} from '../core/commercialRepository'
import type {Interview,Job,JobCandidate,Offer,PipelineStage,Placement} from '../../shared/types/domain'
import {Button} from '../../shared/ui/Button'
import {Drawer} from '../../shared/ui/Drawer'
import {Field,Input,Select,Textarea} from '../../shared/ui/Field'
import {Badge,StatusBadge} from '../../shared/ui/Page'
import {consentStatus,offerStatus} from '../../shared/lib/status'
import {formatMoney} from '../../shared/lib/format'
import {recommendedCandidateAction} from '../workflow/workflow'
import {recordWorkflowEvent} from '../../shared/lib/productAnalytics'

type ActionName='submit'|'check_feedback'|'interview'|'offer'|'placement'|'move'
interface DocumentRow{id:string;file_name:string;original_filename:string|null;deleted_at:string|null}
interface SubmissionCandidateRow{id:string;candidate_id:string;candidates?:{document_links?:Array<{documents:DocumentRow|DocumentRow[]|null}>}|null}

export interface JobCandidatePanelProps {job:Job;item:JobCandidate;stage:PipelineStage;stages:PipelineStage[];currentMemberId?:string;interviews:Interview[];offers:Offer[];placement:Placement|null;hasSubmission:boolean;action:string|null;readOnly:boolean;onAction:(action:string|null)=>void;onClose:()=>void;onUpdated:()=>Promise<unknown>}

const localValue=(date:Date)=>{const offset=date.getTimezoneOffset()*60_000;return new Date(date.valueOf()-offset).toISOString().slice(0,16)}

export function JobCandidatePanel({job,item,stage,stages,currentMemberId,interviews,offers,placement,hasSubmission,action:requestedAction,readOnly,onAction,onClose,onUpdated}:JobCandidatePanelProps){
  const {organization}=useOrganization();const {user}=useAuth();const capabilities=useWorkspaceCapabilities();const cache=useQueryClient()
  const details=useQuery({queryKey:['candidate-detail',organization?.id,item.candidate_id],queryFn:()=>getCandidateDetail(organization!.id,item.candidate_id)})
  const submissionRows=useQuery({queryKey:['submission-candidates',organization?.id,job.id],queryFn:()=>listSubmissionCandidateDocuments(organization!.id,job.id)})
  const connections=useQuery({queryKey:['calendar-connections',organization?.id],queryFn:()=>listCalendarConnections(organization!.id)})
  const contacts=useQuery({queryKey:['contacts',organization?.id],queryFn:()=>listContacts(organization!.id)})
  const [recipientName,setRecipientName]=useState('');const [recipientEmail,setRecipientEmail]=useState('');const [message,setMessage]=useState('Please review this candidate for the role.');const [selectedDocuments,setSelectedDocuments]=useState<string[]>([])
  const startDefault=useMemo(()=>{const start=new Date();start.setDate(start.getDate()+1);start.setHours(9,0,0,0);return start},[])
  const [startsAt,setStartsAt]=useState(localValue(startDefault));const [endsAt,setEndsAt]=useState(localValue(new Date(startDefault.valueOf()+60*60*1000)));const [location,setLocation]=useState('');const [attendeeEmails,setAttendeeEmails]=useState('');const [createMeet,setCreateMeet]=useState(true)
  const [salary,setSalary]=useState('');const [startDate,setStartDate]=useState('');const [fee,setFee]=useState('');const [moveStage,setMoveStage]=useState(item.current_stage_id)
  /* Which source set the fee is recorded, not inferred. Accepting the suggested figure states the
   * agreement that produced it; typing anything else is a manual price, and saying so is what keeps
   * a later fee-agreement change from making this placement look mispriced. */
  const [feeSource,setFeeSource]=useState<PlacementFeeSource>('manual')
  const privateData=Array.isArray(details.data?.candidate_private_details)?details.data.candidate_private_details[0]:details.data?.candidate_private_details
  useEffect(()=>{if(privateData?.email&&!attendeeEmails)setAttendeeEmails(privateData.email)},[privateData?.email,attendeeEmails])
  const documents=useMemo(()=>{const rows=(submissionRows.data||[]) as unknown as SubmissionCandidateRow[];const row=rows.find((candidate)=>candidate.id===item.id);return (row?.candidates?.document_links||[]).flatMap((link)=>Array.isArray(link.documents)?link.documents:link.documents?[link.documents]:[]).filter((document)=>!document.deleted_at)},[item.id,submissionRows.data])
  const health=useQuery({queryKey:['job-health',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobHealth(organization!.id)})
  const jobHealth=health.data?.find((entry)=>entry.id===job.id)
  const expectedFee=jobHealth?.expected_fee!=null?Number(jobHealth.expected_fee):null
  const expectedSource:PlacementFeeSource|null=jobHealth?.fee_source==='Job override'?'job_override':jobHealth?.fee_source==='Account agreement'?'account_agreement':null
  const acceptedOffer=offers.find((offer)=>offer.status==='accepted');const recommendation=recommendedCandidateAction({stage,hasSubmission,interviews,offers,hasPlacement:Boolean(placement)})
  const calendarConnected=connections.data?.some((connection)=>connection.member_id===currentMemberId&&connection.status==='connected')||false
  const clientContacts=(contacts.data||[]).filter((contact)=>contact.company_id===job.company_id&&contact.contact_status!=='do_not_contact')
  const compliant=details.isSuccess&&item.candidates?.status!=='do_not_contact'&&privateData?.consent_status==='granted'
  const selectContact=(contactId:string)=>{const contact=clientContacts.find((entry)=>entry.id===contactId);setRecipientName(contact?.full_name||'');setRecipientEmail(contact?.email||'')}
  const trackAction=(eventName:'action_started'|'action_completed'|'action_abandoned',actionKey:string)=>recordWorkflowEvent({organizationId:organization!.id,eventName,surface:'job_candidate_panel',actionKey})
  const refresh=async()=>{await Promise.all([cache.invalidateQueries({queryKey:['interviews',organization?.id]}),cache.invalidateQueries({queryKey:['offers',organization?.id]}),cache.invalidateQueries({queryKey:['placements',organization?.id]}),cache.invalidateQueries({queryKey:['submissions',organization?.id]}),onUpdated()])}
  const submit=useMutation({mutationFn:()=>sendClientSubmission({organizationId:organization!.id,jobId:job.id,title:`${item.candidates?.full_name} · ${job.title}`,message,recipientName:recipientName||undefined,recipientEmail,expiryDays:7,items:[{job_candidate_id:item.id,candidate_summary:`${item.candidates?.full_name} — ${item.candidates?.current_position||'Experienced candidate'}${item.candidates?.current_company?` at ${item.candidates.current_company}`:''}.`,document_ids:selectedDocuments}]}),onSuccess:async()=>{trackAction('action_completed','submit');onAction(null);await refresh()}})
  const interview=useMutation({mutationFn:async()=>{const id=await createInterview(organization!.id,user!.id,{job_candidate_id:item.id,starts_at:new Date(startsAt).toISOString(),ends_at:new Date(endsAt).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,location,attendee_emails:attendeeEmails.split(',').map((email)=>email.trim()).filter(Boolean),create_google_meet:createMeet&&calendarConnected,organizer_member_id:calendarConnected?currentMemberId:undefined,interview_type:'client_interview'});if(calendarConnected)await syncInterviewCalendar(organization!.id,id);return id},onSuccess:async()=>{trackAction('action_completed','interview');onAction(null);await refresh()}})
  const offer=useMutation({mutationFn:()=>createOffer(organization!.id,user!.id,{job_candidate_id:item.id,salary:Number(salary),currency:job.currency||organization!.base_currency,start_date:startDate||undefined}),onSuccess:async()=>{trackAction('action_completed','offer');onAction(null);await refresh()}})
  const place=useMutation({mutationFn:()=>convertOfferToPlacement(acceptedOffer!.id,Number(fee),90,feeSource),onSuccess:async()=>{trackAction('action_completed','placement');onAction(null);await refresh()}})
  const move=useMutation({mutationFn:()=>moveCandidate(item.id,moveStage),onSuccess:async()=>{trackAction('action_completed','move');onAction(null);await refresh()}})
  const chooseAction=(value:ActionName)=>{trackAction('action_started',value);onAction(value)};const action=readOnly?null:requestedAction
  const closePanel=()=>{if(action)trackAction('action_abandoned',action);onClose()}
  return <Drawer title={item.candidates?.full_name||'Candidate'} description={`${stage.name} · ${job.title}`} eyebrow="Candidate action" open onClose={closePanel}>
    <div className="candidate-context"><div className="candidate-context-summary"><span className="candidate-context-avatar">{item.candidates?.full_name?.split(/\s+/).slice(0,2).map((part)=>part[0]).join('')}</span><div><strong>{item.candidates?.current_position||'Role not recorded'}</strong><p>{[item.candidates?.current_company,item.candidates?.location].filter(Boolean).join(' · ')||'Profile details need review'}</p></div></div><div className="context-badges"><Badge tone="info">{stage.name}</Badge>{privateData&&<StatusBadge map={consentStatus} value={privateData.consent_status}/>}</div><Link className="record-link" to={`/app/${organization!.slug}/candidates/${item.candidate_id}`}>Open full candidate profile</Link></div>
    <section className="next-action-card"><span><MoveRight size={18}/></span><div><p className="eyebrow">Recommended next action</p><strong>{readOnly?'Waiting':recommendation.label}</strong><p>{readOnly?'This job is closed to recruitment actions. Its history remains available.':recommendation.reason}</p></div>{!readOnly&&<>{recommendation.key==='submit'&&capabilities.data?.canSubmit&&<Button disabled={!compliant} onClick={()=>chooseAction('submit')}>Submit to client</Button>}{recommendation.key==='schedule_interview'&&capabilities.data?.canManagePlacements&&<Button onClick={()=>chooseAction('interview')}>Schedule interview</Button>}{['record_outcome','record_offer'].includes(recommendation.key)&&capabilities.data?.canManagePlacements&&<Button onClick={()=>chooseAction('offer')}>Record offer</Button>}{recommendation.key==='create_placement'&&capabilities.data?.canManagePlacements&&<Button onClick={()=>chooseAction('placement')}>Create placement</Button>}{recommendation.key==='check_feedback'&&<Button onClick={()=>chooseAction('check_feedback')}>Check feedback</Button>}</>}</section>
    {!compliant&&<p className="warning-box">Submission is unavailable because consent is not granted or the candidate is marked do not contact. Update the candidate record before sharing information.</p>}
    {action==='submit'&&<section className="context-action-form"><h3>Submit to client</h3>{clientContacts.length>0&&<Field label="Client contact"><Select defaultValue="" onChange={(event)=>selectContact(event.target.value)}><option value="">Select a suggested contact</option>{clientContacts.map((contact)=><option key={contact.id} value={contact.id}>{contact.full_name}{contact.position?` · ${contact.position}`:''}</option>)}</Select></Field>}<Field label="Recipient name"><Input value={recipientName} onChange={(event)=>setRecipientName(event.target.value)}/></Field><Field label="Recipient email"><Input type="email" value={recipientEmail} onChange={(event)=>setRecipientEmail(event.target.value)}/></Field><Field label="Message"><Textarea value={message} onChange={(event)=>setMessage(event.target.value)}/></Field><fieldset><legend>Documents to share</legend><div className="checkbox-list">{documents.map((document)=><label key={document.id}><input type="checkbox" checked={selectedDocuments.includes(document.id)} onChange={(event)=>setSelectedDocuments((current)=>event.target.checked?[...current,document.id]:current.filter((id)=>id!==document.id))}/><span><FileText size={14}/>{document.original_filename||document.file_name}</span></label>)}{documents.length===0&&<p className="muted">No candidate documents are available. You can still send the written summary.</p>}</div></fieldset>{submit.error&&<p className="form-error" role="alert">{submit.error.message}</p>}<ActionButtons onCancel={()=>onAction(null)} label="Send secure submission" loading={submit.isPending} disabled={!recipientEmail||!compliant} onSave={()=>submit.mutate()}/></section>}
    {action==='check_feedback'&&<section className="context-action-form"><h3>Client review</h3><p>{hasSubmission?'The submission is active. Review recent activity or follow up with the client contact.':'No submission is recorded for this candidate.'}</p><Button variant="secondary" onClick={()=>onAction(null)}>Back to candidate</Button></section>}
    {action==='interview'&&<section className="context-action-form"><h3>Schedule interview</h3><div className="form-grid"><Field label="Starts"><Input type="datetime-local" value={startsAt} onChange={(event)=>setStartsAt(event.target.value)}/></Field><Field label="Ends"><Input type="datetime-local" value={endsAt} onChange={(event)=>setEndsAt(event.target.value)}/></Field></div><Field label="Location or call details"><Input value={location} onChange={(event)=>setLocation(event.target.value)}/></Field><Field label="Attendee emails"><Input value={attendeeEmails} onChange={(event)=>setAttendeeEmails(event.target.value)}/></Field><label className="check-row"><input type="checkbox" checked={createMeet} disabled={!calendarConnected} onChange={(event)=>setCreateMeet(event.target.checked)}/><span>Create a Google Meet link and synchronize my Calendar</span></label>{!calendarConnected&&<p className="muted">Calendar is not connected. The interview will still be saved in the ATS.</p>}{interview.error&&<p className="form-error" role="alert">{interview.error.message}</p>}<ActionButtons onCancel={()=>onAction(null)} label="Schedule interview" loading={interview.isPending} disabled={!startsAt||!endsAt} onSave={()=>interview.mutate()}/></section>}
    {action==='offer'&&<section className="context-action-form"><h3>Record offer</h3><Field label="Salary"><Input type="number" min="0" value={salary} onChange={(event)=>setSalary(event.target.value)}/></Field><Field label="Currency"><Input value={job.currency||organization!.base_currency} disabled/></Field><Field label="Proposed start"><Input type="date" value={startDate} onChange={(event)=>setStartDate(event.target.value)}/></Field>{offer.error&&<p className="form-error" role="alert">{offer.error.message}</p>}<ActionButtons onCancel={()=>onAction(null)} label="Record offer" loading={offer.isPending} disabled={!salary} onSave={()=>offer.mutate()}/></section>}
    {action==='placement'&&<section className="context-action-form"><h3>Create placement</h3>{acceptedOffer?<><p className="success-box"><CheckCircle2 size={15}/>Accepted offer · {formatMoney(acceptedOffer.salary,acceptedOffer.currency)}</p>{expectedFee!=null&&expectedSource
      ?<p className="fee-suggestion"><span>Expected fee <strong>{formatMoney(expectedFee,jobHealth?.currency||job.currency||undefined)}</strong> · {jobHealth?.fee_source}</span><Button size="sm" variant="secondary" type="button" onClick={()=>{setFee(String(expectedFee));setFeeSource(expectedSource)}}>Use this fee</Button></p>
      :<p className="warning-box"><TriangleAlert size={15}/>This job has no agreed fee terms, so the placement fee will be recorded as manually priced.</p>}<Field label="Placement fee"><Input type="number" min="0" value={fee} onChange={(event)=>{setFee(event.target.value);setFeeSource('manual')}}/></Field><p className="muted">Recorded as <strong>{feeSource==='manual'?'manually priced':feeSource==='job_override'?'the job fee override':'the account fee agreement'}</strong>. The 90-day guarantee default will be applied.</p>{place.error&&<p className="form-error" role="alert">{place.error.message}</p>}<ActionButtons onCancel={()=>onAction(null)} label="Create placement" loading={place.isPending} disabled={!fee} onSave={()=>place.mutate()}/></>:<p className="warning-box">An accepted offer is required before creating a placement.</p>}</section>}
    {action==='move'&&<section className="context-action-form"><h3>Move candidate</h3><Field label="Detailed stage"><Select value={moveStage} onChange={(event)=>setMoveStage(event.target.value)}>{stages.map((option)=><option value={option.id} key={option.id}>{option.name}</option>)}</Select></Field><ActionButtons onCancel={()=>onAction(null)} label="Move candidate" loading={move.isPending} disabled={moveStage===item.current_stage_id} onSave={()=>move.mutate()}/></section>}
    {!action&&<section className="context-history"><h3>Recruitment milestones</h3><div className="milestone-list"><article><Mail size={15}/><span><strong>Client submission</strong><small>{hasSubmission?'Sent to client':'Not yet sent'}</small></span></article><article><CalendarPlus size={15}/><span><strong>Interview</strong><small>{interviews.find((entry)=>entry.status==='scheduled')?'Scheduled':interviews.length?'Recorded':'Not scheduled'}</small></span></article><article><BriefcaseBusiness size={15}/><span><strong>Latest offer</strong><small>{offers[0]?<StatusBadge map={offerStatus} value={offers[0].status}/>: 'Not recorded'}</small></span></article><article><Handshake size={15}/><span><strong>Placement</strong><small>{placement?'Recorded':'Not recorded'}</small></span></article></div>{!readOnly&&<div className="context-secondary-actions">{capabilities.data?.canManagePlacements&&<><Button variant="secondary" onClick={()=>chooseAction('interview')}><CalendarPlus size={14}/>Interview</Button><Button variant="secondary" onClick={()=>chooseAction('offer')}><BriefcaseBusiness size={14}/>Offer</Button></>}{capabilities.data?.canMovePipeline&&<Button variant="quiet" onClick={()=>chooseAction('move')}>Move stage</Button>}</div>}</section>}
  </Drawer>
}

function ActionButtons({onCancel,label,loading,disabled,onSave}:{onCancel:()=>void;label:string;loading:boolean;disabled:boolean;onSave:()=>void}){return <div className="form-actions"><Button variant="quiet" onClick={onCancel}>Cancel</Button><Button loading={loading} disabled={disabled} onClick={onSave}>{label}</Button></div>}
