import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Plus,Search} from 'lucide-react'
import {Link,useNavigate} from 'react-router-dom'
import {useOrganization} from '../../app/OrganizationProvider'
import {useAuth} from '../../app/AuthProvider'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {createJob,listCompanies,listJobHealth} from '../core/repository'
import {listTeamMembers,updateJob} from '../core/commercialRepository'
import {formatMoney,formatSalary} from '../../shared/lib/format'
import {jobStatus} from '../../shared/lib/status'
import {useOpenOnNewParam} from '../../shared/lib/useOpenOnNewParam'
import {Button} from '../../shared/ui/Button'
import {Drawer} from '../../shared/ui/Drawer'
import {Field,Input,Select} from '../../shared/ui/Field'
import {Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {EmptyState,ErrorState,LoadingState} from '../../shared/ui/States'
import {Table} from '../../shared/ui/Table'
import {filterJobHealth,phaseSegments,type JobHealthFilter} from './jobHealth'

const filters:Array<[JobHealthFilter,string]>=[['all','All active'],['unowned','Unowned'],['empty','No candidates'],['stale','Stale'],['interview','Interview'],['offer','Offer'],['high_value','High value'],['urgent','Urgent']]

export function JobsPage(){
  const {organization,memberships}=useOrganization();const {user}=useAuth();const capabilities=useWorkspaceCapabilities();const cache=useQueryClient();const navigate=useNavigate();const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [filter,setFilter]=useState<JobHealthFilter>('all')
  const currentMember=memberships.find((item)=>item.organization_id===organization?.id&&item.user_id===user?.id);const [companyId,setCompanyId]=useState('');const [title,setTitle]=useState('');const [owner,setOwner]=useState(currentMember?.id||'');const [location,setLocation]=useState('');const [priority,setPriority]=useState('normal')
  useOpenOnNewParam(setOpen)
  const jobs=useQuery({queryKey:['job-health',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobHealth(organization!.id)});const companies=useQuery({queryKey:['companies',organization?.id],enabled:Boolean(organization),queryFn:()=>listCompanies(organization!.id)});const team=useQuery({queryKey:['team',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  const mutation=useMutation({mutationFn:async()=>{const id=await createJob(organization!.id,{company_id:companyId,title,owner_member_id:owner||undefined});await updateJob(organization!.id,id,{location:location||null,priority});return id},onSuccess:async(id)=>{setOpen(false);setTitle('');setLocation('');await Promise.all([cache.invalidateQueries({queryKey:['jobs',organization?.id]}),cache.invalidateQueries({queryKey:['job-health',organization?.id]})]);navigate(`/app/${organization!.slug}/jobs/${id}`)}})
  const assign=useMutation({mutationFn:({id,ownerId}:{id:string;ownerId:string})=>updateJob(organization!.id,id,{owner_member_id:ownerId||null}),onSuccess:()=>cache.invalidateQueries({queryKey:['job-health',organization?.id]})})
  if(jobs.isLoading||companies.isLoading||team.isLoading||capabilities.isLoading)return <LoadingState label="Opening job health…"/>;if(jobs.error||companies.error||team.error)return <ErrorState error={jobs.error||companies.error||team.error}/>
  const needle=search.trim().toLowerCase();const visible=filterJobHealth((jobs.data||[]).filter((job)=>['open','draft','on_hold'].includes(job.status)),filter).filter((job)=>!needle||[job.title,job.company_name,job.location,job.owner_name].some((value)=>value?.toLowerCase().includes(needle))).sort((a,b)=>(a.priority==='urgent'?0:a.priority==='high'?1:2)-(b.priority==='urgent'?0:b.priority==='high'?1:2)||b.days_open-a.days_open)
  return <Page title="Jobs" eyebrow="Recruitment delivery" description="See pipeline health, ownership, commercial value, and the next action before opening a job." actions={capabilities.data?.canWriteJobs?<Button leadingIcon={<Plus size={15}/>} onClick={()=>setOpen(true)} disabled={!companies.data?.length}>Create job</Button>:undefined}>
    <Panel><div className="toolbar"><div className="search-box"><Search size={15}/><Input aria-label="Search jobs" placeholder="Job, client, location, or owner" value={search} onChange={(event)=>setSearch(event.target.value)}/></div><div className="segmented-control job-health-filters" aria-label="Job health filter">{filters.map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div></div>
      {visible.length===0?<EmptyState title="No matching jobs" description={companies.data?.length?'Create a job or change the filters.':'Add a client before creating the first job.'}/>:<Table caption="Active job health" headers={['Job','Client and owner','Pipeline','Candidates','Salary and fee','Next action']}>{visible.map((job)=><tr key={job.id}><td><Link className="record-link" to={`/app/${organization?.slug}/jobs/${job.id}`}><strong>{job.title}</strong></Link><span>{job.days_open} days open · {job.location||'Location not set'}</span><StatusBadge map={jobStatus} value={job.status}/></td><td><strong>{job.company_name}</strong>{capabilities.data?.canWriteJobs?<Select aria-label={`Owner for ${job.title}`} value={job.owner_member_id||''} onChange={(event)=>assign.mutate({id:job.id,ownerId:event.target.value})}><option value="">Unassigned</option>{team.data?.filter((member)=>member.status==='active').map((member)=><option value={member.id} key={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select>:<span>{job.owner_name||'Unassigned'}</span>}</td><td><div className="pipeline-mini" aria-label={`${job.candidate_count} candidates by phase`}>{phaseSegments(job).map((segment)=><span key={segment.key} className={`phase-${segment.key}`} style={{flexGrow:segment.count}} title={`${segment.key.replace('_',' ')}: ${segment.count}`}/>)}</div><small>{phaseSegments(job).map((segment)=>`${segment.count} ${segment.key.replace('_',' ')}`).join(' · ')||'Empty pipeline'}</small></td><td><strong>{job.candidate_count}</strong><span>{job.waiting_count} waiting</span></td><td><span>{formatSalary(job.salary_min,job.currency)}{job.salary_max?` – ${formatSalary(job.salary_max,job.currency)}`:''}</span><strong>{formatMoney(job.expected_fee,job.currency)}</strong><small>{job.fee_source||'Fee not set'}</small></td><td><Link className="button button-secondary button-sm" to={`/app/${organization?.slug}/jobs/${job.id}`}>{job.next_action||'Review job'}</Link></td></tr>)}</Table>}
    </Panel>
    <Drawer title="Create job" description="Start with the client and role. The default pipeline is added automatically." open={open} onClose={()=>setOpen(false)}><div className="stack"><Field label="Client"><Select value={companyId} onChange={(event)=>setCompanyId(event.target.value)}><option value="">Select client</option>{companies.data?.map((company)=><option value={company.id} key={company.id}>{company.name}</option>)}</Select></Field><Field label="Job title"><Input autoFocus value={title} onChange={(event)=>setTitle(event.target.value)}/></Field><div className="form-grid"><Field label="Owner"><Select value={owner} onChange={(event)=>setOwner(event.target.value)}><option value="">Unassigned</option>{team.data?.filter((member)=>member.status==='active').map((member)=><option value={member.id} key={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select></Field><Field label="Location"><Input value={location} onChange={(event)=>setLocation(event.target.value)}/></Field><Field label="Priority"><Select value={priority} onChange={(event)=>setPriority(event.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></Select></Field></div>{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={mutation.isPending} disabled={!companyId||title.trim().length<2} onClick={()=>mutation.mutate()}>Create job</Button></div></div></Drawer>
  </Page>
}
