import {useState} from 'react'
import {DndContext,PointerSensor,useDraggable,useDroppable,useSensor,useSensors,type DragEndEvent} from '@dnd-kit/core'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {ArrowLeft,BriefcaseBusiness,ChevronRight,Layers3,Plus} from 'lucide-react'
import {Link,useParams,useSearchParams} from 'react-router-dom'
import {useAuth} from '../../app/AuthProvider'
import {useOrganization} from '../../app/OrganizationProvider'
import {useWorkspaceCapabilities} from '../../app/useWorkspaceCapabilities'
import {addCandidateToJob,getPipeline,listCandidatesPage,listInterviews,listJobs,listOffers,listPlacements,listSubmissionPackages,moveCandidate} from '../core/repository'
import {listTeamMembers,updateJob} from '../core/commercialRepository'
import type {Job,JobCandidate,PipelineStage} from '../../shared/types/domain'
import {Button} from '../../shared/ui/Button'
import {Field,Input,Select,Textarea} from '../../shared/ui/Field'
import {Modal} from '../../shared/ui/Modal'
import {Badge,Page,Panel,StatusBadge} from '../../shared/ui/Page'
import {jobPriority,jobStatus} from '../../shared/lib/status'
import {ErrorState,LoadingState} from '../../shared/ui/States'
import {ActivityFeed} from '../activities/ActivityFeed'
import {groupPipelineStages,jobNeedsCandidateAction,phaseForStage,pipelinePhases} from '../workflow/workflow'
import {JobCandidatePanel} from './JobCandidatePanel'

type WorkspaceView='pipeline'|'activity'|'details'

function PhaseColumn({id,label,count,children}:{id:string;label:string;count:number;children:React.ReactNode}){
  const {setNodeRef,isOver}=useDroppable({id})
  return <section ref={setNodeRef} className={`kanban-column workflow-column ${isOver?'kanban-over':''}`}><header><strong>{label}</strong><span>{count}</span></header>{children}</section>
}

function CandidateCard({item,onOpen,onMove,targets,canMove}:{item:JobCandidate;onOpen:()=>void;onMove:(stageId:string)=>void;targets:Array<{id:string;label:string}>;canMove:boolean}){
  const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:item.id,data:{stageId:item.current_stage_id}})
  const style=transform?{transform:`translate3d(${transform.x}px, ${transform.y}px, 0)`}:undefined
  return <article ref={setNodeRef} style={style} className={`candidate-card workflow-candidate-card ${isDragging?'dragging':''}`} {...(canMove?listeners:{})} {...attributes}><button className="candidate-card-open" onPointerDown={(event)=>event.stopPropagation()} onClick={onOpen}><strong>{item.candidates?.full_name}</strong><span>{item.candidates?.current_position||'Role not recorded'}</span><small>{item.candidates?.current_company||item.candidates?.location||'Profile needs review'}</small><ChevronRight size={15}/></button>{canMove&&<label onPointerDown={(event)=>event.stopPropagation()}><span className="sr-only">Move {item.candidates?.full_name}</span><Select aria-label={`Move ${item.candidates?.full_name}`} value={targets.find((target)=>target.id===item.current_stage_id)?.id||item.current_stage_id} onChange={(event)=>onMove(event.target.value)}>{targets.map((target)=><option value={target.id} key={target.id}>{target.label}</option>)}</Select></label>}</article>
}

export function JobWorkspacePage(){
  const {jobId=''}=useParams();const {organization,memberships}=useOrganization();const {user}=useAuth();const capabilities=useWorkspaceCapabilities();const cache=useQueryClient();const [params,setParams]=useSearchParams();const [addOpen,setAddOpen]=useState(false);const [candidateId,setCandidateId]=useState('');const [detailed,setDetailed]=useState(false);const [editOpen,setEditOpen]=useState(false)
  const jobs=useQuery({queryKey:['jobs',organization?.id],enabled:Boolean(organization),queryFn:()=>listJobs(organization!.id)});const job=jobs.data?.find((item)=>item.id===jobId)
  const pipeline=useQuery({queryKey:['pipeline',jobId],enabled:Boolean(job),queryFn:()=>getPipeline(job!)});const candidates=useQuery({queryKey:['job-add-candidates',organization?.id],enabled:Boolean(organization&&addOpen),queryFn:()=>listCandidatesPage(organization!.id,'',0,100)})
  const interviews=useQuery({queryKey:['interviews',organization?.id],enabled:Boolean(organization),queryFn:()=>listInterviews(organization!.id)});const offers=useQuery({queryKey:['offers',organization?.id],enabled:Boolean(organization),queryFn:()=>listOffers(organization!.id)});const placements=useQuery({queryKey:['placements',organization?.id],enabled:Boolean(organization),queryFn:()=>listPlacements(organization!.id)});const packages=useQuery({queryKey:['submissions',organization?.id],enabled:Boolean(organization),queryFn:()=>listSubmissionPackages(organization!.id)});const members=useQuery({queryKey:['members',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  const refresh=()=>Promise.all([cache.invalidateQueries({queryKey:['pipeline',jobId]}),cache.invalidateQueries({queryKey:['jobs',organization?.id]}),cache.invalidateQueries({queryKey:['today',organization?.id]})])
  const add=useMutation({mutationFn:()=>addCandidateToJob(organization!.id,user!.id,job!,candidateId),onSuccess:async()=>{setAddOpen(false);setCandidateId('');await refresh()}});const move=useMutation({mutationFn:({itemId,stageId}:{itemId:string;stageId:string})=>moveCandidate(itemId,stageId),onSuccess:refresh})
  const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}));const canRecruit=job?.status==='open'&&Boolean(capabilities.data?.canMovePipeline);const onDragEnd=({active,over}:DragEndEvent)=>{if(canRecruit&&over&&active.data.current?.stageId!==over.id)move.mutate({itemId:String(active.id),stageId:String(over.id)})}
  if(jobs.isLoading||pipeline.isLoading||interviews.isLoading||offers.isLoading||placements.isLoading||packages.isLoading||members.isLoading||capabilities.isLoading)return <LoadingState label="Opening job workspace…"/>
  if(jobs.error||pipeline.error||interviews.error||offers.error||placements.error||packages.error||members.error||!job)return <ErrorState error={jobs.error||pipeline.error||interviews.error||offers.error||placements.error||packages.error||members.error||new Error('Job not found')}/>
  const view=(params.get('view') as WorkspaceView)||'pipeline';const selected=pipeline.data!.items.find((item)=>item.id===params.get('candidate'))||null;const phases=groupPipelineStages(pipeline.data!.stages);const activeStages=pipeline.data!.stages.filter((stage)=>!['rejected','withdrawn','on_hold'].includes(stage.stage_type));const outcomeStages=pipeline.data!.stages.filter((stage)=>['rejected','withdrawn','on_hold'].includes(stage.stage_type))
  const columns=detailed?activeStages.map((stage)=>({id:stage.id,label:stage.name,stages:[stage]})):phases.map((phase)=>({id:phase.stages[0]!.id,label:phase.label,stages:phase.stages}))
  const targets=detailed?activeStages.map((stage)=>({id:stage.id,label:stage.name})):columns.map((column)=>({id:column.id,label:column.label}))
  const next=jobNeedsCandidateAction(pipeline.data!.items);const currentMember=memberships.find((item)=>item.organization_id===organization?.id&&item.user_id===user?.id)
  const setView=(nextView:WorkspaceView)=>{const nextParams=new URLSearchParams(params);nextParams.set('view',nextView);nextParams.delete('candidate');nextParams.delete('action');setParams(nextParams)}
  const openCandidate=(item:JobCandidate)=>{const nextParams=new URLSearchParams(params);nextParams.set('candidate',item.id);nextParams.delete('action');setParams(nextParams)}
  return <Page title={job.title} eyebrow={job.companies?.name||'Client job'} description="Pipeline, client review, interviews, offers, and placement in one workspace." metadata={<div className="record-metadata"><StatusBadge map={jobStatus} value={job.status}/><StatusBadge map={jobPriority} value={job.priority}/>{job.location&&<span>{job.location}</span>}</div>} actions={<><Link className="button button-quiet" to={`/app/${organization!.slug}/jobs`}><ArrowLeft size={14}/>Jobs</Link>{next&&canRecruit&&<Button onClick={()=>setAddOpen(true)}><Plus size={14}/>{next.label}</Button>}</>} tabs={<nav className="record-tabs" aria-label="Job workspace views"><button className={view==='pipeline'?'active':''} onClick={()=>setView('pipeline')}>Pipeline</button><button className={view==='activity'?'active':''} onClick={()=>setView('activity')}>Activity</button><button className={view==='details'?'active':''} onClick={()=>setView('details')}>Details</button></nav>}>
    {job.status!=='open'&&<p className="warning-box">This job is {job.status.replace('_',' ')}. Recruitment actions are read-only until it is reopened.</p>}
    {view==='pipeline'&&<><div className="workflow-toolbar"><div><strong>{pipeline.data!.items.length} candidates</strong><span>Move candidates between phases, then open a card for the next action.</span></div><div className="table-actions"><label className="detail-toggle"><input type="checkbox" checked={detailed} onChange={(event)=>setDetailed(event.target.checked)}/><Layers3 size={15}/>Detailed stages</label>{canRecruit&&<Button variant="secondary" onClick={()=>setAddOpen(true)}><Plus size={14}/>Add candidates</Button>}</div></div>{outcomeStages.length>0&&<div className="outcome-summary">{outcomeStages.map((stage)=><Badge key={stage.id}>{stage.name}: {pipeline.data!.items.filter((item)=>item.current_stage_id===stage.id).length}</Badge>)}</div>}<Panel padding="sm"><DndContext sensors={sensors} onDragEnd={onDragEnd}><div className={`kanban workflow-kanban ${detailed?'workflow-kanban-detailed':''}`}>{columns.map((column)=>{const stageIds=new Set(column.stages.map((stage)=>stage.id));const items=pipeline.data!.items.filter((item)=>stageIds.has(item.current_stage_id));return <PhaseColumn id={column.id} label={column.label} count={items.length} key={column.id}>{items.map((item)=><CandidateCard item={item} key={item.id} onOpen={()=>openCandidate(item)} onMove={(stageId)=>move.mutate({itemId:item.id,stageId})} targets={targets} canMove={canRecruit}/>)}</PhaseColumn>})}</div></DndContext></Panel></>}
    {view==='activity'&&<ActivityFeed links={[{job_id:jobId}]} title="Job activity" subtitle="Calls, client updates, submissions, feedback, and stage movement in one history." readOnly={capabilities.data?.readOnly}/>}
    {view==='details'&&<JobDetails job={job} members={members.data||[]} onEdit={capabilities.data?.canWriteJobs?()=>setEditOpen(true):undefined}/>}
    <Modal title="Add candidate to job" open={addOpen} onClose={()=>setAddOpen(false)}><div className="stack"><Field label="Candidate"><Select value={candidateId} onChange={(event)=>setCandidateId(event.target.value)}><option value="">Select candidate</option>{candidates.data?.rows.filter((candidate)=>!pipeline.data!.items.some((item)=>item.candidate_id===candidate.id)).map((candidate)=><option value={candidate.id} key={candidate.id}>{candidate.full_name} · {candidate.current_position||'Profile'}</option>)}</Select></Field>{add.error&&<p className="form-error" role="alert">{add.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={()=>setAddOpen(false)}>Cancel</Button><Button disabled={!candidateId||add.isPending} onClick={()=>add.mutate()}>Add candidate</Button></div></div></Modal>
    {capabilities.data?.canWriteJobs&&<JobEditModal job={job} members={members.data||[]} open={editOpen} onClose={()=>setEditOpen(false)} onSaved={async()=>{setEditOpen(false);await refresh()}}/>}
    {selected&&<JobCandidatePanel job={job} item={selected} stage={pipeline.data!.stages.find((stage)=>stage.id===selected.current_stage_id)!} stages={pipeline.data!.stages} currentMemberId={currentMember?.id} interviews={interviews.data!.filter((item)=>item.job_candidate_id===selected.id)} offers={offers.data!.filter((item)=>item.job_candidate_id===selected.id)} placement={placements.data!.find((item)=>item.job_id===job.id&&item.candidate_id===selected.candidate_id)||null} hasSubmission={(packages.data||[]).some((pack)=>Array.isArray(pack.candidate_submissions)&&pack.candidate_submissions.some((submission)=>submission.job_candidate_id===selected.id))} action={params.get('action')} readOnly={job.status!=='open'} onAction={(action)=>{const nextParams=new URLSearchParams(params);if(action)nextParams.set('action',action);else nextParams.delete('action');setParams(nextParams)}} onClose={()=>{const nextParams=new URLSearchParams(params);nextParams.delete('candidate');nextParams.delete('action');setParams(nextParams)}} onUpdated={refresh}/>}
  </Page>
}

function JobDetails({job,members,onEdit}:{job:Job;members:Array<{id:string;profiles?:{full_name?:string;email?:string}|null}>;onEdit?:()=>void}){
  const owner=members.find((member)=>member.id===job.owner_member_id)
  return <div className="record-overview-grid"><Panel title="Job overview" action={onEdit&&<Button variant="secondary" onClick={onEdit}>Edit job</Button>}><dl className="record-summary"><div><dt>Client</dt><dd>{job.companies?.name||'—'}</dd></div><div><dt>Owner</dt><dd>{owner?.profiles?.full_name||owner?.profiles?.email||'Unassigned'}</dd></div><div><dt>Location</dt><dd>{job.location||'Not set'}</dd></div><div><dt>Status</dt><dd>{job.status.replace('_',' ')}</dd></div><div><dt>Priority</dt><dd>{job.priority}</dd></div><div><dt>Currency</dt><dd>{job.currency||'Not set'}</dd></div></dl></Panel><Panel title="How work progresses"><div className="phase-path">{pipelinePhases.map((phase)=><span key={phase.key}>{phase.label}</span>)}</div></Panel></div>
}

function JobEditModal({job,members,open,onClose,onSaved}:{job:Job;members:Array<{id:string;status:string;profiles?:{full_name?:string;email?:string}|null}>;open:boolean;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [title,setTitle]=useState(job.title);const [location,setLocation]=useState(job.location||'');const [priority,setPriority]=useState(job.priority);const [status,setStatus]=useState(job.status);const [owner,setOwner]=useState(job.owner_member_id||'');const [description,setDescription]=useState('')
  const mutation=useMutation({mutationFn:()=>updateJob(job.organization_id,job.id,{title,location:location||null,priority,status,owner_member_id:owner||null,description:description||undefined}),onSuccess:onSaved})
  return <Modal title="Edit job" open={open} onClose={onClose}><div className="stack"><Field label="Job title"><Input value={title} onChange={(event)=>setTitle(event.target.value)}/></Field><div className="form-grid"><Field label="Owner"><Select value={owner} onChange={(event)=>setOwner(event.target.value)}><option value="">Unassigned</option>{members.filter((member)=>member.status==='active').map((member)=><option value={member.id} key={member.id}>{member.profiles?.full_name||member.profiles?.email}</option>)}</Select></Field><Field label="Location"><Input value={location} onChange={(event)=>setLocation(event.target.value)}/></Field><Field label="Priority"><Select value={priority} onChange={(event)=>setPriority(event.target.value as Job['priority'])}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></Select></Field><Field label="Status"><Select value={status} onChange={(event)=>setStatus(event.target.value as Job['status'])}><option value="draft">Draft</option><option value="open">Open</option><option value="on_hold">On hold</option><option value="filled">Filled</option><option value="closed">Closed</option><option value="cancelled">Cancelled</option></Select></Field></div><details className="advanced-fields"><summary>Advanced details</summary><Field label="Description"><Textarea value={description} onChange={(event)=>setDescription(event.target.value)}/></Field></details>{mutation.error&&<p className="form-error" role="alert">{mutation.error.message}</p>}<div className="form-actions"><Button variant="quiet" onClick={onClose}>Cancel</Button><Button loading={mutation.isPending} disabled={title.trim().length<2} onClick={()=>mutation.mutate()}>Save job</Button></div></div></Modal>
}
