import {useMemo,useState} from 'react'
import {useQuery} from '@tanstack/react-query'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {useOrganization} from '../../app/OrganizationProvider'
import {getAgencyPerformance,listTeamMembers} from '../core/commercialRepository'
import {Field,Input} from '../../shared/ui/Field'
import {Page,Panel} from '../../shared/ui/Page'
import {ErrorState,LoadingState} from '../../shared/ui/States'
import {Table} from '../../shared/ui/Table'
import {ChartCard} from '../../shared/ui/ChartCard'
import {formatMoney} from '../../shared/lib/format'

const dateValue=(date:Date)=>date.toISOString().slice(0,10)

export function ReportsPage(){
  const {organization}=useOrganization();const now=useMemo(()=>new Date(),[])
  const [from,setFrom]=useState(dateValue(new Date(now.getFullYear(),0,1)));const [to,setTo]=useState(dateValue(now))
  const fromIso=new Date(`${from}T00:00:00`).toISOString();const toIso=new Date(`${to}T23:59:59.999`).toISOString()
  const performance=useQuery({queryKey:['agency-performance',organization?.id,from,to],enabled:Boolean(organization&&from&&to),queryFn:()=>getAgencyPerformance(organization!.id,fromIso,toIso)})
  const team=useQuery({queryKey:['team',organization?.id],enabled:Boolean(organization),queryFn:()=>listTeamMembers(organization!.id)})
  if(performance.isLoading||team.isLoading)return <LoadingState label="Preparing agency intelligence…"/>
  if(performance.error||team.error)return <ErrorState error={performance.error||team.error}/>
  const data=performance.data!;const stageTypes=data.history.map((item)=>{const stage=Array.isArray(item.pipeline_stages)?item.pipeline_stages[0]:item.pipeline_stages;return stage?.stage_type});const placements=data.placements
  const baseFees=placements.filter((item)=>item.currency===organization?.base_currency).reduce((sum,item)=>sum+Number(item.placement_fee),0)
  const overdue=data.tasks.filter((item)=>item.status!=='completed'&&item.due_at&&new Date(item.due_at)<now).length
  const rows=(team.data||[]).filter((member)=>member.status==='active').map((member)=>{const userId=member.user_id;const memberId=member.id;const memberPlacements=placements.filter((item)=>item.created_by===userId);return {id:member.id,name:member.profiles?.full_name||member.profiles?.email||'Team member',jobs:data.jobs.filter((item)=>item.owner_member_id===memberId).length,submissions:data.submissions.filter((item)=>item.created_by===userId).length,interviews:data.interviews.filter((item)=>item.created_by===userId).length,offers:data.offers.filter((item)=>item.created_by===userId).length,placements:memberPlacements.length,fees:memberPlacements.filter((item)=>item.currency===organization?.base_currency).reduce((sum,item)=>sum+Number(item.placement_fee),0),overdue:data.tasks.filter((item)=>item.owner_member_id===memberId&&item.status!=='completed'&&item.due_at&&new Date(item.due_at)<now).length}})
  const funnel=[{name:'Submitted',value:data.submissions.length},{name:'Interview',value:Math.max(data.interviews.length,stageTypes.filter((type)=>type==='interview').length)},{name:'Offer',value:Math.max(data.offers.length,stageTypes.filter((type)=>type==='offer').length)},{name:'Placement',value:placements.length}]
  const workload=rows.map((row)=>({name:row.name.split(' ')[0],jobs:row.jobs,submissions:row.submissions,overdue:row.overdue}))
  return <Page title="Reports" eyebrow="Agency intelligence" description="Decision-ready funnel, workload, and commercial outcomes for a selectable period." actions={<div className="date-range"><Field label="From"><Input type="date" value={from} max={to} onChange={(event)=>setFrom(event.target.value)}/></Field><Field label="To"><Input type="date" value={to} min={from} onChange={(event)=>setTo(event.target.value)}/></Field></div>}>
    <div className="kpi-grid"><article className="kpi"><div><p>Jobs opened</p><strong>{data.jobs.length}</strong></div></article><article className="kpi"><div><p>Submissions</p><strong>{data.submissions.length}</strong></div></article><article className="kpi"><div><p>Interviews</p><strong>{data.interviews.length}</strong></div></article><article className="kpi"><div><p>Offers</p><strong>{data.offers.length}</strong></div></article><article className="kpi"><div><p>Placements</p><strong>{placements.length}</strong></div></article><article className="kpi"><div><p>Fees · base currency</p><strong>{formatMoney(baseFees,organization?.base_currency)}</strong></div></article></div>
    <div className="chart-grid">
      <ChartCard title="Recruitment funnel" description="Milestone volume from client submission to placement." summary={<table><caption>Recruitment funnel totals</caption><tbody>{funnel.map((item)=><tr key={item.name}><th>{item.name}</th><td>{item.value}</td></tr>)}</tbody></table>}><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} margin={{top:8,right:12,left:-18,bottom:4}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--color-line-soft)"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'var(--color-canvas)'}}/><Bar dataKey="value" fill="var(--color-accent)" radius={[7,7,0,0]} maxBarSize={58}/></BarChart></ResponsiveContainer></ChartCard>
      <ChartCard title="Consultant workload" description="Active vacancies, submissions, and overdue actions." summary={<table><caption>Consultant workload totals</caption><tbody>{rows.map((row)=><tr key={row.id}><th>{row.name}</th><td>{row.jobs} jobs, {row.submissions} submissions, {row.overdue} overdue</td></tr>)}</tbody></table>}><ResponsiveContainer width="100%" height="100%"><BarChart data={workload} margin={{top:8,right:12,left:-18,bottom:4}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--color-line-soft)"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'var(--color-canvas)'}}/><Bar dataKey="jobs" stackId="a" fill="var(--color-accent)"/><Bar dataKey="submissions" stackId="a" fill="var(--color-bronze)"/><Bar dataKey="overdue" stackId="a" fill="var(--color-danger)" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard>
    </div>
    <div className="two-column"><Panel title="Funnel conversion"><Table caption="Funnel conversion by milestone" headers={['Milestone','Count','Conversion from submissions']}>{funnel.map((item)=><tr key={item.name}><td>{item.name}</td><td>{item.value}</td><td>{data.submissions.length?`${Math.round(item.value/data.submissions.length*100)}%`:'—'}</td></tr>)}</Table></Panel><Panel title="Workload health"><div className="settings-list"><article className="finance-row"><span>Overdue tasks</span><strong className={overdue?'overdue-text':''}>{overdue}</strong></article><article className="finance-row"><span>Accepted offers</span><strong>{data.offers.filter((item)=>item.status==='accepted').length}</strong></article><article className="finance-row"><span>Completed placements</span><strong>{placements.filter((item)=>item.status==='completed').length}</strong></article></div></Panel></div>
    <Panel title="Consultant performance"><Table caption="Consultant performance for selected date range" headers={['Consultant','Active jobs','Submissions','Interviews','Offers','Placements',{label:'Fees',align:'right'},'Overdue tasks']}>{rows.map((row)=><tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.jobs}</td><td>{row.submissions}</td><td>{row.interviews}</td><td>{row.offers}</td><td>{row.placements}</td><td className="money">{formatMoney(row.fees,organization?.base_currency)}</td><td className={row.overdue?'overdue-text':''}>{row.overdue}</td></tr>)}</Table></Panel><p className="muted report-note">Fee totals include only records already denominated in {organization?.base_currency}; no exchange rate is invented.</p>
  </Page>
}
