export type Organization = { id: string; name: string; slug: string; base_currency: string; timezone: string; primary_color?:string;logo_path?:string|null;logo_url?:string|null }
export type Membership = { id: string; organization_id: string; user_id?:string; status: string; organizations: Organization }
export type Candidate = {
  id: string; organization_id: string; full_name: string; current_company: string | null; current_position: string | null;
  location: string | null; linkedin_url: string | null; status: string; source: string | null; availability: string | null;
  owner_member_id: string | null; created_at: string; updated_at?: string; candidate_private_details?: CandidatePrivate | CandidatePrivate[] | null
}
export type CandidatePrivate = { email: string | null; phone: string | null; current_salary: number | null; expected_salary: number | null; salary_currency: string | null; work_authorization?:string|null;consent_status: string;consent_expires_at?:string|null }
export type Company = { id: string; organization_id: string; name: string; industry: string | null; location: string | null; website: string | null; account_status: string; business_development_stage: string; updated_at: string }
export type Contact = { id: string; organization_id: string; company_id: string; full_name: string; position: string | null; email: string | null; phone: string | null; contact_status: string; next_follow_up_at: string | null; companies?: Pick<Company,'id'|'name'> | null }
export type Job = { id: string; organization_id: string; company_id: string; pipeline_id: string | null; title: string; location: string | null; priority: string; status: string; currency: string | null; placement_fee_percentage: number | null; opened_at: string | null; updated_at: string; companies?: Pick<Company,'id'|'name'> | null }
export type PipelineStage = { id: string; pipeline_id: string; name: string; stage_key: string; stage_type: string; position: number; color: string | null }
export type JobCandidate = { id: string; job_id: string; candidate_id: string; current_stage_id: string; updated_at: string; candidates?: Candidate | null; pipeline_stages?: PipelineStage | null }
export type TaskLink={candidate_id:string|null;company_id:string|null;contact_id:string|null;job_id:string|null;candidates?:{full_name:string}|null;companies?:{name:string}|null;contacts?:{full_name:string}|null;jobs?:{title:string}|null}
export type Task = { id: string; title: string; description: string | null; status: string; priority: string; due_at: string | null; owner_member_id: string | null; created_at: string;organization_members?:{profiles?:{full_name:string|null;email:string|null}|null}|null;task_links?:TaskLink[] }
export type RevenueSplit={id:string;member_id:string;split_percentage:number;split_amount:number|null;organization_members?:{profiles?:{full_name:string|null;email:string|null}|null}|null}
export type PlacementInvoice={id:string;invoice_reference:string|null;amount:number;currency:string;issued_on:string|null;due_on:string|null;status:string;paid_on:string|null}
export type Placement = { id: string; candidate_id: string; job_id: string; company_id: string; start_date: string; salary: number; placement_fee: number; currency: string; guarantee_ends_on: string; status: string; candidates?: Pick<Candidate,'full_name'> | null; jobs?: Pick<Job,'title'> | null; companies?: Pick<Company,'name'> | null;placement_revenue_splits?:RevenueSplit[];placement_invoices?:PlacementInvoice[] }
export type Interview = {id:string;job_candidate_id:string;interview_type:string|null;stage_label:string|null;starts_at:string;ends_at:string;timezone:string;location:string|null;meeting_url:string|null;status:string;organizer_member_id:string|null;attendee_emails:string[];create_google_meet:boolean;calendar_event_id:string|null;calendar_event_url:string|null;calendar_sync_status:'not_requested'|'pending'|'synced'|'failed'|'cancelled';calendar_last_error:string|null;calendar_last_synced_at:string|null;calendar_retry_count:number;calendar_sync_version:number;calendar_synced_version:number;job_candidates?:{candidates?:Pick<Candidate,'full_name'>|null;jobs?:Pick<Job,'title'>|null}|null}
export type Offer = {id:string;job_candidate_id:string;salary:number;currency:string;offered_at:string;start_date:string|null;status:string;notes:string|null;job_candidates?:{candidates?:Pick<Candidate,'full_name'>|null;jobs?:Pick<Job,'title'>|null}|null}
export type PublicReview = { package: { id:string; title:string; message:string|null; job_title:string; company_name:string; recipient_name:string|null; expires_at:string }; candidates: PublicSubmission[];documents?:Array<{id:string;filename:string;mimeType:string;url:string}> }
export type PublicSubmission = { submission_id:string; candidate_name:string; current_company:string|null; current_position:string|null; location:string|null; linkedin_url:string|null; portfolio_url:string|null; candidate_summary:string; recruiter_comments:string|null; suitability_assessment:string|null; relevant_experience:string|null; expected_salary:number|null; currency:string|null; notice_period:string|null; availability:string|null; motivation:string|null; relocation_willingness:string|null; interview_availability:string|null; feedback:{decision:string;comments:string|null;reviewer_name:string|null;updated_at:string}|null }

export type TeamMember={id:string;organization_id:string;user_id:string;job_title:string|null;status:'active'|'suspended'|'invited';profiles:{full_name?:string;email?:string}|null;member_roles?:Array<{roles:{id:string;name:string;role_key:string}|null}>}
export type Role={id:string;name:string;role_key:string;is_system:boolean;role_permissions?:Array<{permission_key:string}>}
export type OrganizationInvitation={id:string;email:string;role_id:string;expires_at:string;accepted_at:string|null;revoked_at:string|null;delivery_status:string;last_sent_at:string|null;roles?:{name:string}|null}
export type CalendarConnection={id:string;organization_id:string;member_id:string;google_email:string;calendar_id:string;status:'connected'|'reauthorization_required'|'disconnected'|'error';connected_at:string;last_synced_at:string|null;last_error:string|null}
export type CandidateDocument={id:string;file_name:string;original_filename:string|null;mime_type:string;storage_path:string;size_bytes:number;created_at:string;deleted_at?:string|null;signedUrl?:string}
export type CandidateDetail=Candidate&{updated_at:string;portfolio_url:string|null;notice_period_days:number|null;last_contacted_at:string|null;deleted_at:string|null;candidate_private_details?:CandidatePrivate|CandidatePrivate[]|null;candidate_employment?:Array<{id:string;company_name:string;title:string;started_on:string|null;ended_on:string|null;started_on_precision:string|null;ended_on_precision:string|null;is_current:boolean;summary:string|null}>;candidate_education?:Array<{id:string;institution:string;degree:string|null;field_of_study:string|null;started_on:string|null;ended_on:string|null;started_on_precision:string|null;ended_on_precision:string|null}>;candidate_languages?:Array<{id:string;language:string;proficiency:string|null}>;candidate_skills?:Array<{skill_id:string;proficiency:string|null;years_experience:number|null;skills:{id:string;name:string}|null}>;candidate_tags?:Array<{tag_id:string;tags:{id:string;name:string;color:string|null}|null}>}
export type ImportBatch={id:string;entity_type:string;file_name:string;source_format:string|null;status:string;total_rows:number;valid_rows:number;failed_rows:number;validation_summary:Record<string,unknown>;reconciliation_summary:Record<string,unknown>;created_at:string;completed_at:string|null;rolled_back_at:string|null}
